'use client';

import React, { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import { 
  ArrowLeft, AlertTriangle, TrendingDown, TrendingUp, 
  Activity, MessageSquare, BrainCircuit, Database, LineChart 
} from 'lucide-react';

// Define strict TypeScript interfaces for our API boundaries
interface AnomalyState {
  id: string;
  metric: string;
  agent_name: string;
  created_at: string;
  temporal_context: string;
  root_cause: string;
  forecast: string;
  variance_pct: number;
}

interface ChatMessage {
  role: 'user' | 'agent';
  content: string;
  sql_used?: string;
}

export default function InvestigationDashboard() {
  const params = useParams();
  const router = useRouter();
  const anomalyId = params.id as string;

  const [anomaly, setAnomaly] = useState<AnomalyState | null>(null);
  const [loading, setLoading] = useState(true);
  
  // Localized Deep-Dive State
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [inputMessage, setInputMessage] = useState('');
  const [isQuerying, setIsQuerying] = useState(false);

  // 1. Fetch the Anomaly State (Simulated for this implementation, wire to your Supabase/API)
  useEffect(() => {
    const fetchAnomaly = async () => {
      try {
        // Replace with your actual API call: await fetch(`/api/anomalies/${anomalyId}`)
        // Simulating the payload generated by the Supervisor Agent in Phase 5
        setTimeout(() => {
          setAnomaly({
            id: anomalyId,
            metric: 'Monthly Recurring Revenue (MRR)',
            agent_name: 'Stripe Revenue Watchdog',
            created_at: new Date().toISOString(),
            variance_pct: -12.4,
            temporal_context: 'This marks a continued degradation over 48 hours. It is not an isolated spike.',
            root_cause: 'The drop is primarily driven by a 40% churn increase in the "Enterprise Annual" tier originating from the EU region.',
            forecast: 'Projected Trend: Without intervention, MRR is expected to drop an additional 3% over the next 7 days based on current cancellation velocity.'
          });
          setLoading(false);
        }, 800);
      } catch (error) {
        console.error('Failed to load anomaly state:', error);
        setLoading(false);
      }
    };

    fetchAnomaly();
  }, [anomalyId]);

  // 2. The Deep-Dive Execution Loop (Talk to DuckDB)
  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputMessage.trim()) return;

    const newMsg: ChatMessage = { role: 'user', content: inputMessage };
    setMessages((prev) => [...prev, newMsg]);
    setInputMessage('');
    setIsQuerying(true);

    try {
      // Wire this to your NL2SQL / Chat endpoint
      // const res = await fetch('/api/chat/orchestrate', { method: 'POST', body: JSON.stringify({ prompt: inputMessage, contextId: anomalyId }) });
      
      // Simulating the DuckDB NL2SQL response
      setTimeout(() => {
        setMessages((prev) => [
          ...prev, 
          { 
            role: 'agent', 
            content: 'I pulled the specific accounts that churned. Here is the breakdown.',
            sql_used: 'SELECT account_id, plan, churn_date FROM subscriptions WHERE plan = \'Enterprise Annual\' AND region = \'EU\' AND churn_date >= current_date - interval 2 days;'
          }
        ]);
        setIsQuerying(false);
      }, 1500);
    } catch (error) {
      console.error(error);
      setIsQuerying(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full min-h-screen">
        <div className="animate-pulse flex flex-col items-center gap-4">
          <BrainCircuit className="h-8 w-8 text-primary animate-spin" />
          <p className="text-muted-foreground font-mono text-sm">Loading AI Diagnostics...</p>
        </div>
      </div>
    );
  }

  if (!anomaly) return <div>Anomaly not found.</div>;

  const isDrop = anomaly.variance_pct < 0;

  return (
    <div className="flex flex-col h-full min-h-screen bg-background p-6 lg:p-10 space-y-6">
      {/* Top Navigation & Status */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Button variant="outline" size="icon" onClick={() => router.push('/dashboard')}>
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div>
            <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
              <AlertTriangle className={`h-6 w-6 ${isDrop ? 'text-destructive' : 'text-emerald-500'}`} />
              Incident Investigation
            </h1>
            <p className="text-muted-foreground text-sm">
              Detected by {anomaly.agent_name} at {new Date(anomaly.created_at).toLocaleString()}
            </p>
          </div>
        </div>
        <Badge variant={isDrop ? "destructive" : "default"} className="text-lg py-1 px-3">
          {isDrop ? <TrendingDown className="mr-2 h-5 w-5" /> : <TrendingUp className="mr-2 h-5 w-5" />}
          {Math.abs(anomaly.variance_pct)}% Variance
        </Badge>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 flex-1">
        {/* Left Column: The AI Supervisor Report */}
        <div className="lg:col-span-1 space-y-6">
          <Card className="border-primary/20 shadow-sm">
            <CardHeader className="bg-primary/5 pb-4">
              <CardTitle className="flex items-center gap-2 text-lg">
                <BrainCircuit className="h-5 w-5 text-primary" />
                AI Diagnostic Report
              </CardTitle>
              <CardDescription>Synthesized by the Multi-Agent Supervisor</CardDescription>
            </CardHeader>
            <CardContent className="pt-6 space-y-6">
              
              {/* Phase 3: Memory Context */}
              <div className="space-y-2">
                <h3 className="text-sm font-semibold flex items-center gap-2 text-foreground">
                  <Activity className="h-4 w-4 text-muted-foreground" />
                  Temporal Context
                </h3>
                <p className="text-sm text-muted-foreground leading-relaxed bg-muted/50 p-3 rounded-md">
                  {anomaly.temporal_context}
                </p>
              </div>

              <Separator />

              {/* Phase 1: Diagnostic Context */}
              <div className="space-y-2">
                <h3 className="text-sm font-semibold flex items-center gap-2 text-foreground">
                  <Database className="h-4 w-4 text-muted-foreground" />
                  Root Cause Analysis
                </h3>
                <p className="text-sm text-muted-foreground leading-relaxed bg-muted/50 p-3 rounded-md">
                  {anomaly.root_cause}
                </p>
              </div>

              <Separator />

              {/* Phase 5: Forecasting Context */}
              <div className="space-y-2">
                <h3 className="text-sm font-semibold flex items-center gap-2 text-foreground">
                  <LineChart className="h-4 w-4 text-muted-foreground" />
                  Future Outlook
                </h3>
                <p className="text-sm text-muted-foreground leading-relaxed bg-muted/50 p-3 rounded-md">
                  {anomaly.forecast}
                </p>
              </div>

            </CardContent>
          </Card>
        </div>

        {/* Right Column: Deep Dive Chat (NL2SQL Interface) */}
        <div className="lg:col-span-2 flex flex-col">
          <Card className="flex flex-col flex-1 border-border shadow-sm">
            <CardHeader className="border-b">
              <CardTitle className="text-lg flex items-center gap-2">
                <MessageSquare className="h-5 w-5" />
                Deep Dive Console
              </CardTitle>
              <CardDescription>Ask the agent to query DuckDB for further breakdown.</CardDescription>
            </CardHeader>
            
            <CardContent className="flex-1 p-0 flex flex-col h-[500px]">
              <ScrollArea className="flex-1 p-4">
                {messages.length === 0 ? (
                  <div className="flex flex-col items-center justify-center h-full text-muted-foreground space-y-3 mt-20">
                    <Database className="h-10 w-10 opacity-20" />
                    <p className="text-sm text-center">Need more details? Ask the agent to pull raw rows, group by different dimensions, or chart the data.</p>
                  </div>
                ) : (
                  <div className="space-y-4">
                    {messages.map((msg, i) => (
                      <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                        <div className={`max-w-[80%] rounded-lg p-4 ${msg.role === 'user' ? 'bg-primary text-primary-foreground' : 'bg-muted'}`}>
                          <p className="text-sm whitespace-pre-wrap">{msg.content}</p>
                          {/* If the agent generated DuckDB SQL, show it in a collapsible/dimmed block */}
                          {msg.sql_used && (
                            <div className="mt-3 pt-3 border-t border-border/50">
                              <span className="text-xs font-mono opacity-50 block mb-1">Execution Plan:</span>
                              <code className="text-[11px] font-mono bg-background/50 p-2 rounded block whitespace-pre-wrap opacity-70">
                                {msg.sql_used}
                              </code>
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                    {isQuerying && (
                      <div className="flex justify-start">
                        <div className="bg-muted rounded-lg p-4 flex items-center gap-2">
                          <BrainCircuit className="h-4 w-4 animate-spin text-primary" />
                          <span className="text-sm text-muted-foreground">Writing DuckDB query...</span>
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </ScrollArea>
              
              <div className="p-4 border-t bg-background">
                <form onSubmit={handleSendMessage} className="flex gap-2">
                  <Input 
                    placeholder="e.g., 'Show me the raw rows for the EU churns...'" 
                    value={inputMessage}
                    onChange={(e) => setInputMessage(e.target.value)}
                    disabled={isQuerying}
                    className="flex-1"
                  />
                  <Button type="submit" disabled={isQuerying || !inputMessage.trim()}>
                    Analyze
                  </Button>
                </form>
              </div>
            </CardContent>
          </Card>
        </div>

      </div>
    </div>
  );
}