import { createServerClient } from '@supabase/ssr'
import { NextResponse, type NextRequest } from 'next/server'

export async function middleware(request: NextRequest) {
  // 1. Create a mutable response object
  let supabaseResponse = NextResponse.next({
    request: {
      headers: request.headers,
    },
  })

  // 2. Initialize the Supabase Server Client securely
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll()
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value }) =>
            request.cookies.set(name, value)
          )
          
          supabaseResponse = NextResponse.next({
            request,
          })
          
          cookiesToSet.forEach(({ name, value, options }) =>
            supabaseResponse.cookies.set(name, value, options)
          )
        },
      },
    }
  )

  // 3. Security by Design: Cryptographically verify user token with Supabase
  const {
    data: { user },
  } = await supabase.auth.getUser()

  const pathname = request.nextUrl.pathname

  // 4. Define Route Topologies (Accounting for Next.js Route Groups)
  const isAuthRoute = pathname.startsWith('/login') || 
                      pathname.startsWith('/register') || 
                      pathname.startsWith('/forgot-password')

  // Explicitly protect all root-level paths generated by the (dashboard) group
  const protectedViews = [
    '/dashboard', 
    '/agents', 
    '/datasets', 
    '/investigate', 
    '/chat', 
    '/billing', 
    '/settings'
  ]
  const isProtectedView = protectedViews.some(route => pathname.startsWith(route))

  // API Route Management
  const isApiRoute = pathname.startsWith('/api')
  const isPublicApiRoute = pathname.startsWith('/api/webhooks') // Allow external webhooks (Stripe, etc.) to bypass edge auth

  // 5. Orchestration & Tenant Security Routing
  if (!user) {
    // A. Kick unauthenticated users attempting to view private UI to login
    if (isProtectedView) {
      const url = request.nextUrl.clone()
      url.pathname = '/login'
      // Optional: Pass the original URL as a 'next' param for post-login redirect
      url.searchParams.set('next', pathname) 
      return NextResponse.redirect(url)
    }

    // B. Block unauthorized API requests immediately at the Edge (Hybrid Performance)
    if (isApiRoute && !isPublicApiRoute) {
      return NextResponse.json(
        { error: 'Unauthorized. Edge Security prevented access to this resource.' }, 
        { status: 401 }
      )
    }
  } else {
    // Logged in but hitting auth pages -> Kick to dashboard
    if (isAuthRoute) {
      const url = request.nextUrl.clone()
      url.pathname = '/dashboard'
      return NextResponse.redirect(url)
    }
  }

  // 6. Return mutated response to sync browser tokens
  return supabaseResponse
}

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     * - API OG Image generator (if you have one)
     */
    '/((?!_next/static|_next/image|favicon.ico|api/og|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)',
  ],
}