# api/services/ingestion_service.py

import logging
import uuid
import anyio
from typing import Dict, Any

from sqlalchemy.orm import Session
from api.services.storage_manager import storage_manager
from models import Dataset

logger = logging.getLogger(__name__)

class IngestionPipeline:
    """
    Phase 2: Ingestion & Parquet Pipeline (Refactored for Modularity)
    
    Acts as the Orchestrator. Delegates physical storage, tier resolution, 
    and DuckDB compute entirely to the AdaptiveStorageManager.
    Uses anyio to offload blocking synchronous operations to worker threads.
    """

    def generate_presigned_upload(self, db: Session, tenant_id: str, file_name: str, content_type: str) -> Dict[str, Any]:
        """
        Generates a secure, temporary URL for direct-to-cloud upload.
        Dynamically routes to Supabase/R2 based on the tenant's tier via the StorageManager.
        """
        # Resolve the dynamic storage tier for the tenant
        config = storage_manager._resolve_tenant_config(db, tenant_id)
        s3_client = storage_manager.get_s3_client(db, tenant_id)
        
        # Enforce the strict physical partition defined by the storage manager
        object_key = f"{config.prefix}raw/{uuid.uuid4().hex[:8]}_{file_name}"
        
        try:
            # Generate POST URL with strict size/type conditions
            presigned_post = s3_client.generate_presigned_post(
                Bucket=config.bucket,
                Key=object_key,
                Fields={"Content-Type": content_type},
                Conditions=[
                    {"Content-Type": content_type},
                    ["content-length-range", 0, 104857600] # Max 100MB limit for raw uploads
                ],
                ExpiresIn=3600
            )
            logger.info(f"Generated pre-signed URL for tenant {tenant_id} | File: {file_name}")
            return {
                "url": presigned_post["url"], 
                "fields": presigned_post["fields"], 
                "object_key": object_key
            }
            
        except Exception as e:
            logger.error(f"Failed to generate presigned URL: {str(e)}")
            raise RuntimeError("Storage upload initialization failed.")

    async def process_raw_to_parquet(self, db: Session, tenant_id: str, dataset_id: str, raw_object_key: str) -> Dict[str, Any]:
        """
        Event-Driven Profiling Worker logic.
        Uses thread-offloading to prevent heavy DuckDB compute from blocking the event loop.
        """
        logger.info(f"[Worker] Processing dataset {dataset_id} for tenant {tenant_id}")
        
        try:
            # HYBRID PERFORMANCE: Offload the heavy synchronous DuckDB compute to a separate thread
            # This prevents the FastAPI event loop from stalling during conversion.
            profile_result = await anyio.to_thread.run_sync(
                storage_manager.convert_to_parquet_and_profile, 
                db, 
                tenant_id, 
                raw_object_key
            )
            
            # Update Database via SQLAlchemy (Standardized ORM)
            dataset = db.query(Dataset).filter(
                Dataset.id == dataset_id,
                Dataset.tenant_id == tenant_id
            ).first()
            
            if not dataset:
                raise ValueError(f"Dataset {dataset_id} not found in database.")
                
            dataset.status = "READY"
            
            # Assign the exact path generated by storage manager so compute_engine can find it
            dataset.file_path = profile_result["parquet_path"]
            
            # Contextual RAG prep: Assign the extracted semantic schema directly to the model
            dataset.schema_metadata = profile_result["columns"]
            
            # Persist changes safely
            db.commit()
            logger.info(f"[Worker] Successfully transformed and profiled {dataset_id}.")
            return {"status": "success", "schema": profile_result["columns"]}

        except Exception as e:
            logger.error(f"[Worker] Failed to process dataset {dataset_id}: {str(e)}")
            db.rollback()
            
            # Safe Fail state via ORM
            dataset = db.query(Dataset).filter(Dataset.id == dataset_id).first()
            if dataset:
                dataset.status = "FAILED"
                db.commit()
                
            raise RuntimeError(f"Data processing worker failed: {str(e)}")

# Export singleton instance for dependency injection across routers
ingestion_service = IngestionPipeline()