# api/services/storage_manager.py

import os
import uuid
import logging
from datetime import datetime
from dataclasses import dataclass
from typing import Optional, Any, Dict, List
import boto3
import duckdb
import fsspec
from botocore.config import Config
from sqlalchemy.orm import Session

# Import modern models (ensure these align with your schema)
from models import Dataset, TenantSettings, StorageTier

try:
    import pandas as pd
    import polars as pl
except ImportError:
    pass

logger = logging.getLogger(__name__)

@dataclass
class ResolvedStorage:
    """Immutable data container holding the dynamically resolved storage layer config."""
    endpoint: str
    bucket: str
    access_key: str
    secret_key: str
    prefix: str
    tier: StorageTier


class AdaptiveStorageManager:
    """
    Core infrastructure router. Dynamically shifts multi-tenant operations between 
    Ephemeral memory, Supabase free-tier storage, Cloudflare R2 Pro, and BYOS.
    Supercharged with Native Polars Streaming and DuckDB Secure Secrets.
    """
    def __init__(self):
        # 1. Cloudflare R2 (Pro Tier - Highly Optimized for DuckDB)
        self.r2_endpoint = os.getenv("R2_ENDPOINT_URL")
        self.r2_bucket = os.getenv("R2_BUCKET_NAME", "dataomen-pro-data")
        self.r2_access = os.getenv("R2_ACCESS_KEY_ID")
        self.r2_secret = os.getenv("R2_SECRET_ACCESS_KEY")

        # 2. Supabase Storage (Free Tier - S3 Compatible API)
        self.supa_endpoint = os.getenv("SUPABASE_S3_ENDPOINT")
        self.supa_bucket = os.getenv("SUPABASE_STORAGE_BUCKET", "default-datasets")
        self.supa_access = os.getenv("SUPABASE_S3_ACCESS_KEY")
        self.supa_secret = os.getenv("SUPABASE_S3_SECRET_KEY")

    def _resolve_tenant_config(self, db: Session, tenant_id: str) -> ResolvedStorage:
        """
        Interrogates the database to find the user's current billing/storage tier.
        Applies mathematical tenant_id jailing to strictly isolate data.
        """
        if not tenant_id:
            raise ValueError("Security Violation: tenant_id strictly required for storage resolution.")

        # settings = db.query(TenantSettings).filter(TenantSettings.tenant_id == tenant_id).first()
        # tier = settings.storage_tier if settings else StorageTier.SUPABASE
        
        # Mocking for immediate drop-in replacement (uncomment DB logic in prod)
        tier = StorageTier.R2_PRO if self.r2_endpoint else StorageTier.SUPABASE
        
        # 1.2 STRICT PHYSICAL PARTITIONING: DuckDB and fsspec will ONLY ever see this folder
        prefix = f"tenants/tenant_id={tenant_id}/"

        if tier == StorageTier.EPHEMERAL:
            return ResolvedStorage("", "", "", "", prefix, tier)
        elif tier == StorageTier.R2_PRO:
            return ResolvedStorage(self.r2_endpoint, self.r2_bucket, self.r2_access, self.r2_secret, prefix, tier)

        # Fallback to Supabase S3
        return ResolvedStorage(self.supa_endpoint, self.supa_bucket, self.supa_access, self.supa_secret, prefix, tier)

    def get_s3_client(self, db: Session, tenant_id: str):
        """Returns a Boto3 client pointing to the user's resolved storage tier for API operations."""
        config = self._resolve_tenant_config(db, tenant_id)
        if config.tier == StorageTier.EPHEMERAL:
            raise ValueError("Ephemeral tier does not support persistent S3 access.")

        return boto3.client(
            's3',
            endpoint_url=config.endpoint,
            aws_access_key_id=config.access_key,
            aws_secret_access_key=config.secret_key,
            region_name="auto", 
            config=Config(s3={'addressing_style': 'path'}, signature_version='s3v4')
        )

    def get_fsspec_fs(self, db: Session, tenant_id: str) -> fsspec.AbstractFileSystem:
        """
        1.1 Data Modularity: Returns a zero-copy filesystem interface.
        Allows Polars to stream bytes directly to Cloudflare R2 over the network.
        """
        config = self._resolve_tenant_config(db, tenant_id)
        if config.tier == StorageTier.EPHEMERAL:
            return fsspec.filesystem('memory')

        storage_options = {
            "key": config.access_key,
            "secret": config.secret_key,
            "client_kwargs": {"endpoint_url": config.endpoint}
        }
        return fsspec.filesystem('s3', **storage_options)

    # --------------------------------------------------------------------------
    # Phase 2: Ingestion & Parquet Pipeline Operations
    # --------------------------------------------------------------------------

    def write_dataframe(self, db: Session, df: Any, tenant_id: str, dataset_id: str, format: str = "parquet") -> str:
        """
        The Upgraded Computation Layer: Native Streaming Sink.
        Takes a Polars DataFrame and streams it directly to Cloudflare R2 as ZSTD Parquet.
        Automatically handles Hive partition folder structures generated by sync_engine.py.
        """
        config = self._resolve_tenant_config(db, tenant_id)
        
        # If sync_engine passed a directory (e.g., table/year=2024/month=10), generate a unique batch filename
        if not dataset_id.endswith(".parquet"):
            batch_id = uuid.uuid4().hex[:8]
            timestamp = int(datetime.utcnow().timestamp())
            object_key = f"{dataset_id}/batch_{timestamp}_{batch_id}.parquet"
        else:
            object_key = dataset_id

        # The strict, isolated path within the tenant's R2 territory
        full_s3_uri = f"{config.bucket}/{config.prefix}datasets/{object_key}"
        
        try:
            fs = self.get_fsspec_fs(db, tenant_id)
            
            if format == "parquet":
                if hasattr(df, "write_parquet"):
                    # Native Polars streaming: Zero-copy, maximum CPU efficiency
                    # We stream directly into the fsspec remote file handler
                    with fs.open(full_s3_uri, "wb") as f:
                        df.write_parquet(f, compression="zstd")
                else:
                    raise TypeError("Compute Error: Provided object does not support write_parquet().")
            else:
                raise NotImplementedError(f"Format '{format}' not supported.")
            
            # Return the exact path written so sync_engine can log it
            logger.debug(f"[{tenant_id}] Wrote optimized dataset -> s3://{full_s3_uri}")
            return f"s3://{full_s3_uri}"

        except Exception as e:
            logger.error(f"❌ Storage Write Exception (Tenant: {tenant_id}): {str(e)}")
            raise e

    def get_duckdb_query_path(self, db: Session, dataset: Dataset) -> str:
        """
        Calculates the optimal zero-copy path for DuckDB to execute against.
        Smartly appends glob wildcards if the path is a Hive-partitioned directory.
        """
        if dataset.is_sample and dataset.sample_uri:
            return f"'{dataset.sample_uri}'"

        config = self._resolve_tenant_config(db, dataset.tenant_id)

        # Smart Globbing: If path doesn't end in .parquet, it's a folder containing many partitions
        path_suffix = "/**/*.parquet" if not dataset.file_path.endswith(".parquet") else ""

        # DuckDB natively reads partitioned s3:// URIs via the httpfs extension
        return f"'s3://{config.bucket}/{config.prefix}{dataset.file_path}{path_suffix}'"

    def setup_duckdb_connection(self, db: Session, tenant_id: str) -> duckdb.DuckDBPyConnection:
        """
        1.3 Programmatic RLS Environment (Security Upgraded):
        Spins up an ephemeral, in-memory DuckDB connection.
        Uses modern DuckDB `CREATE SECRET` syntax to strictly isolate S3 credentials to this thread.
        """
        config = self._resolve_tenant_config(db, tenant_id)
        
        con = duckdb.connect(database=':memory:')
        if config.tier == StorageTier.EPHEMERAL:
            return con

        # Load zero-copy networking layers
        con.execute("INSTALL httpfs; LOAD httpfs;")
        
        endpoint_clean = config.endpoint.replace('https://', '').replace('http://', '')
        secret_name = f"s3_secret_{tenant_id.replace('-', '_')}"
        
        # Security by Design: Modern DuckDB Secrets
        # This replaces dangerous global SET variables with scoped cryptographic bindings.
        # Cloudflare R2 works best with URL_STYLE 'vhost' or 'path' depending on the domain.
        con.execute(f"""
            CREATE OR REPLACE SECRET {secret_name} (
                TYPE S3,
                KEY_ID '{config.access_key}',
                SECRET '{config.secret_key}',
                ENDPOINT '{endpoint_clean}',
                URL_STYLE 'path',
                REGION 'auto'
            );
        """)
        
        return con

    def convert_to_parquet_and_profile(self, db: Session, tenant_id: str, raw_object_key: str) -> Dict[str, Any]:
        """
        Event-Driven Profiling Worker (For raw uploaded CSVs/JSONs).
        Uses DuckDB to stream the raw S3 object, rewrite to S3 as ZSTD Parquet, 
        and extract RAG Context Metadata.
        """
        config = self._resolve_tenant_config(db, tenant_id)
        if config.tier == StorageTier.EPHEMERAL:
            raise ValueError("Ephemeral storage does not support persistent background workers.")

        parquet_key = raw_object_key.replace('/raw/', '/analytical/')
        for ext in ['.csv', '.xlsx', '.xls', '.json']:
            if parquet_key.lower().endswith(ext):
                parquet_key = parquet_key[:parquet_key.rfind(ext)] + '.parquet'
                break
        else:
            if not parquet_key.endswith('.parquet'):
                parquet_key += '.parquet'

        raw_s3_path = f"s3://{config.bucket}/{raw_object_key}"
        parquet_s3_path = f"s3://{config.bucket}/{parquet_key}"

        con = self.setup_duckdb_connection(db, tenant_id)
        
        try:
            # 1. Vectorized Conversion via DuckDB Compute Engine
            if raw_object_key.lower().endswith('.csv'):
                read_query = f"read_csv_auto('{raw_s3_path}', normalize_names=True)"
            elif raw_object_key.lower().endswith('.json'):
                read_query = f"read_json_auto('{raw_s3_path}')"
            else:
                read_query = f"read_csv_auto('{raw_s3_path}', normalize_names=True)"

            con.execute(f"""
                COPY (SELECT * FROM {read_query}) 
                TO '{parquet_s3_path}' (FORMAT PARQUET, COMPRESSION 'ZSTD');
            """)

            # 2. Schema Extraction (Zero-Dependency RAG Prep)
            metadata_rows = con.execute(f"DESCRIBE SELECT * FROM '{parquet_s3_path}';").fetchall()
            columns_info = [{"name": row[0], "type": row[1]} for row in metadata_rows]
            
            sample_query = con.execute(f"SELECT * FROM '{parquet_s3_path}' LIMIT 3;")
            col_names = [col[0] for col in sample_query.description]
            sample_rows = [dict(zip(col_names, row)) for row in sample_query.fetchall()]

            return {
                "parquet_path": parquet_key,
                "columns": columns_info,
                "sample": sample_rows
            }

        except Exception as e:
            logger.error(f"Parquet pipeline failed for {raw_object_key}: {e}")
            raise Exception(f"Failed to process dataset pipeline: {str(e)}")
        finally:
            con.close()


# Export singleton instance for dependency injection
storage_manager = AdaptiveStorageManager()