/**
 * ARCLI.TECH - Frontend Domain Models
 * Core types for the multi-tenant Hybrid Analytical & Document RAG interface.
 */

export interface Attachment {
  id: string;
  file: File;
  status: "pending" | "uploading" | "error" | "done";
  previewUrl?: string;
  name?: string;
  size?: number;
  type?: string;
}

/**
 * The blueprint generated by the AI Query Planner.
 * Maps strictly to the Python `QueryPlan` model.
 */
export interface QueryPlan {
  execution_intent: "ANALYTICAL" | "DOCUMENT_RAG" | "HYBRID";
  intent_summary: string;
  analytical_strategy: string;
  primary_dataset_ids: string[];
  primary_document_ids: string[];
  requested_governed_metrics?: string[];
  confidence_score: number;
  is_achievable?: boolean;
  missing_data_reason?: string;
}

/**
 * Statistical insights generated by the Polars compute engine.
 */
export interface InsightPayload {
  summary: string;
  anomalies?: any[];
  correlations?: any[];
  [key: string]: any;
}

/**
 * Root cause analysis for detected data anomalies.
 */
export interface DiagnosticPayload {
  root_cause_analysis: string;
  recommended_actions: string[];
  confidence_level: "HIGH" | "MEDIUM" | "LOW";
}

/**
 * Core domain model for a Chat Message.
 * Upgraded for Phase 8: Hybrid Streaming Engine (DuckDB + Qdrant).
 */
export interface Message {
  id: string;
  role: "user" | "assistant" | "system";
  content: string; // The natural language narrative text
  
  // --- Hybrid Engine reasoning payloads ---
  status?: string;            // Real-time status: "Thinking...", "Executing SQL..."
  error?: string;             // Detailed error strings for UI display
  plan?: QueryPlan;           // The AI's tactical strategy
  insights?: InsightPayload;  // Statistical Polars output
  diagnostics?: DiagnosticPayload; // Root cause anomaly output
  
  // --- Execution & Data payloads ---
  data?: any[];               // Raw DuckDB result rows
  chartSpec?: any;            // Vega-Lite visualization JSON
  sql?: string;               // Generated SQL for transparency/debugging
  executionTimeMs?: number;   // Performance telemetry
  
  attachments?: Attachment[];
  createdAt?: string | Date;
  timestamp?: Date;           // Optional helper for local UI ordering
  metadata?: Record<string, any>;
}

/**
 * Represents an ongoing conversation thread with a specific Data Agent.
 */
export interface ChatThread {
  id: string;
  tenantId: string;
  agentId: string; 
  title: string;
  messages: Message[];
  updatedAt: string | Date;
  createdAt: string | Date;
}

// ------------------------------------------------------------------
// API CONTRACTS (Strict mapping to FastAPI / Orchestration Route)
// ------------------------------------------------------------------

export interface ChatRequestPayload {
  agent_id: string;
  prompt: string;
  history: { role: string; content: string }[];
  active_dataset_ids?: string[];
  active_document_ids?: string[];
  stream?: boolean;
}

/**
 * Fallback response payload for non-streaming requests.
 */
export interface ChatResponsePayload {
  status: string;
  response_text: string;
  execution_time_ms: number;
  data?: any[];
  chart_spec?: any;
  generated_sql?: string;
  plan?: QueryPlan;
  insights?: InsightPayload;
  diagnostics?: DiagnosticPayload;
}