// types/supabase.ts
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[];

type GenericTable = {
  Row: Record<string, Json>;
  Insert: Record<string, Json>;
  Update: Record<string, Json>;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      tenants: {
        Row: {
          tenant_id: string;
          name: string | null;
          display_name: string | null;
          status: string;
          plan: string | null;
          plan_tier: string;
          subscription_status: string;
          trial_ends_at: string | null;
          billing_status: string | null;
          dodo_customer_id: string | null;
          dodo_subscription_id: string | null;
          current_period_end: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          tenant_id: string;
          name?: string | null;
          display_name?: string | null;
          status?: string;
          plan?: string | null;
          plan_tier?: string;
          subscription_status?: string;
          trial_ends_at?: string | null;
          billing_status?: string | null;
          dodo_customer_id?: string | null;
          dodo_subscription_id?: string | null;
          current_period_end?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          tenant_id?: string;
          name?: string | null;
          display_name?: string | null;
          status?: string;
          plan?: string | null;
          plan_tier?: string;
          subscription_status?: string;
          trial_ends_at?: string | null;
          billing_status?: string | null;
          dodo_customer_id?: string | null;
          dodo_subscription_id?: string | null;
          current_period_end?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      tenant_settings: {
        Row: {
          tenant_id: string;
          company_name: string | null;
          reply_to_email: string | null;
          sender_email: string | null;
          website_url: string | null;
          stripe_account_id: string | null;
          email_provider_status: boolean | null;
          api_key: string | null;
          key_last_updated: string | null;
          crm_webhook_url: string | null;
          updated_at: string | null;
        };
        Insert: {
          tenant_id: string;
          company_name?: string | null;
          reply_to_email?: string | null;
          sender_email?: string | null;
          website_url?: string | null;
          stripe_account_id?: string | null;
          email_provider_status?: boolean | null;
          api_key?: string | null;
          key_last_updated?: string | null;
          crm_webhook_url?: string | null;
          updated_at?: string | null;
        };
        Update: {
          tenant_id?: string;
          company_name?: string | null;
          reply_to_email?: string | null;
          sender_email?: string | null;
          website_url?: string | null;
          stripe_account_id?: string | null;
          email_provider_status?: boolean | null;
          api_key?: string | null;
          key_last_updated?: string | null;
          crm_webhook_url?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      source_posts: {
        Row: {
          id: string;
          // Global public-source corpus rows intentionally have no tenant.
          tenant_id: string | null;
          source: string;
          external_id: string | null;
          source_post_id: string | null;
          title: string | null;
          text: string | null;
          body: string | null;
          author: string | null;
          author_handle: string | null;
          community: string | null;
          url: string | null;
          published_at: string | null;
          posted_at: string | null;
          language: string | null;
          embedding_status: string;
          metadata: Json;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          source: string;
          external_id?: string | null;
          source_post_id?: string | null;
          title?: string | null;
          text?: string | null;
          body?: string | null;
          author?: string | null;
          author_handle?: string | null;
          community?: string | null;
          url?: string | null;
          published_at?: string | null;
          posted_at?: string | null;
          language?: string | null;
          embedding_status?: string;
          metadata?: Json;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          source?: string;
          external_id?: string | null;
          source_post_id?: string | null;
          title?: string | null;
          text?: string | null;
          body?: string | null;
          author?: string | null;
          author_handle?: string | null;
          community?: string | null;
          url?: string | null;
          published_at?: string | null;
          posted_at?: string | null;
          language?: string | null;
          embedding_status?: string;
          metadata?: Json;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      lead_matches: {
        Row: {
          id: string;
          tenant_id: string;
          service_profile_id: string | null;
          source_post_id: string | null;
          match_status: string;
          verifier_score: number;
          similarity_score: number | null;
          embedding_score: number | null;
          match_score: number | null;
          pain_detected: string | null;
          match_reason: string | null;
          suggested_reply: string | null;
          verification: Json;
          verifier_result: Json;
          source_post: Json;
          source_post_data: Json;
          source_post_json: Json;
          post: Json;
          metadata: Json;
          matched_at: string | null;
          verified_at: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          service_profile_id?: string | null;
          source_post_id?: string | null;
          match_status?: string;
          verifier_score?: number;
          similarity_score?: number | null;
          embedding_score?: number | null;
          match_score?: number | null;
          pain_detected?: string | null;
          match_reason?: string | null;
          suggested_reply?: string | null;
          verification?: Json;
          verifier_result?: Json;
          source_post?: Json;
          source_post_data?: Json;
          source_post_json?: Json;
          post?: Json;
          metadata?: Json;
          matched_at?: string | null;
          verified_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          service_profile_id?: string | null;
          source_post_id?: string | null;
          match_status?: string;
          verifier_score?: number;
          similarity_score?: number | null;
          embedding_score?: number | null;
          match_score?: number | null;
          pain_detected?: string | null;
          match_reason?: string | null;
          suggested_reply?: string | null;
          verification?: Json;
          verifier_result?: Json;
          source_post?: Json;
          source_post_data?: Json;
          source_post_json?: Json;
          post?: Json;
          metadata?: Json;
          matched_at?: string | null;
          verified_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      discovery_candidates: {
        Row: {
          id: string;
          tenant_id: string;
          service_profile_id: string;
          first_discovery_run_id: string;
          last_discovery_run_id: string;
          candidate_kind: string;
          entity_provider: string;
          entity_external_id: string;
          entity_url: string | null;
          source: string;
          source_external_id: string;
          source_post_id: string | null;
          dedupe_key: string;
          candidate_status: string;
          raw_score: number | null;
          plausibility_score: number | null;
          similarity_score: number | null;
          verifier_score: number | null;
          priority_score: number;
          score_components: Json;
          source_snapshot: Json;
          evidence: Json;
          decision_by: string | null;
          decision_reason: string | null;
          decision_at: string | null;
          qualified_at: string | null;
          rejected_at: string | null;
          first_seen_at: string | null;
          last_seen_at: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          service_profile_id: string;
          first_discovery_run_id: string;
          last_discovery_run_id: string;
          candidate_kind?: string;
          entity_provider: string;
          entity_external_id: string;
          entity_url?: string | null;
          source: string;
          source_external_id: string;
          source_post_id?: string | null;
          dedupe_key: string;
          candidate_status?: string;
          raw_score?: number | null;
          plausibility_score?: number | null;
          similarity_score?: number | null;
          verifier_score?: number | null;
          priority_score?: number;
          score_components?: Json;
          source_snapshot?: Json;
          evidence?: Json;
          decision_by?: string | null;
          decision_reason?: string | null;
          decision_at?: string | null;
          qualified_at?: string | null;
          rejected_at?: string | null;
          first_seen_at?: string | null;
          last_seen_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          service_profile_id?: string;
          first_discovery_run_id?: string;
          last_discovery_run_id?: string;
          candidate_kind?: string;
          entity_provider?: string;
          entity_external_id?: string;
          entity_url?: string | null;
          source?: string;
          source_external_id?: string;
          source_post_id?: string | null;
          dedupe_key?: string;
          candidate_status?: string;
          raw_score?: number | null;
          plausibility_score?: number | null;
          similarity_score?: number | null;
          verifier_score?: number | null;
          priority_score?: number;
          score_components?: Json;
          source_snapshot?: Json;
          evidence?: Json;
          decision_by?: string | null;
          decision_reason?: string | null;
          decision_at?: string | null;
          qualified_at?: string | null;
          rejected_at?: string | null;
          first_seen_at?: string | null;
          last_seen_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      watchlists: {
        Row: {
          id: string;
          tenant_id: string;
          service_profile_id: string;
          name: string;
          target_buyer: string;
          problem_to_solve: string;
          include_terms: Json;
          exclude_terms: Json;
          source_preferences: Json;
          suggested_places: Json;
          matching_brief: Json;
          embedding: Json;
          embedding_text: string | null;
          embedding_model: string | null;
          embedding_status: string;
          scan_status: string;
          last_scan_at: string | null;
          last_scan_error: string | null;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          service_profile_id: string;
          name: string;
          target_buyer: string;
          problem_to_solve: string;
          include_terms?: Json;
          exclude_terms?: Json;
          source_preferences?: Json;
          suggested_places?: Json;
          matching_brief?: Json;
          embedding?: Json;
          embedding_text?: string | null;
          embedding_model?: string | null;
          embedding_status?: string;
          scan_status?: string;
          last_scan_at?: string | null;
          last_scan_error?: string | null;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          service_profile_id?: string;
          name?: string;
          target_buyer?: string;
          problem_to_solve?: string;
          include_terms?: Json;
          exclude_terms?: Json;
          source_preferences?: Json;
          suggested_places?: Json;
          matching_brief?: Json;
          embedding?: Json;
          embedding_text?: string | null;
          embedding_model?: string | null;
          embedding_status?: string;
          scan_status?: string;
          last_scan_at?: string | null;
          last_scan_error?: string | null;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      watchlist_matches: {
        Row: {
          id: string;
          tenant_id: string;
          watchlist_id: string;
          service_profile_id: string;
          source_post_id: string | null;
          match_status: string;
          verifier_score: number;
          similarity_score: number | null;
          pain_detected: string | null;
          match_reason: string | null;
          suggested_reply: string | null;
          verification: Json;
          source_post: Json;
          metadata: Json;
          matched_at: string | null;
          verified_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          watchlist_id: string;
          service_profile_id: string;
          source_post_id?: string | null;
          match_status?: string;
          verifier_score?: number;
          similarity_score?: number | null;
          pain_detected?: string | null;
          match_reason?: string | null;
          suggested_reply?: string | null;
          verification?: Json;
          source_post?: Json;
          metadata?: Json;
          matched_at?: string | null;
          verified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          watchlist_id?: string;
          service_profile_id?: string;
          source_post_id?: string | null;
          match_status?: string;
          verifier_score?: number;
          similarity_score?: number | null;
          pain_detected?: string | null;
          match_reason?: string | null;
          suggested_reply?: string | null;
          verification?: Json;
          source_post?: Json;
          metadata?: Json;
          matched_at?: string | null;
          verified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      discovery_runs: {
        Row: {
          id: string;
          tenant_id: string;
          service_profile_id: string;
          run_kind: string;
          query_plan: Json;
          status: string;
          summary: Json;
          started_at: string;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          service_profile_id: string;
          run_kind?: string;
          query_plan?: Json;
          status?: string;
          summary?: Json;
          started_at?: string;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          service_profile_id?: string;
          run_kind?: string;
          query_plan?: Json;
          status?: string;
          summary?: Json;
          started_at?: string;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      discovery_evidence: {
        Row: {
          id: string;
          tenant_id: string;
          discovery_run_id: string;
          service_profile_id: string;
          source: string;
          source_post_id: string | null;
          source_url: string | null;
          query_type: string;
          query_phrase: string;
          title: string | null;
          source_text: string;
          evidence_excerpt: string | null;
          evidence_status: string;
          observed_at: string | null;
          evidence_key: string;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          discovery_run_id: string;
          service_profile_id: string;
          source: string;
          source_post_id?: string | null;
          source_url?: string | null;
          query_type: string;
          query_phrase: string;
          title?: string | null;
          source_text: string;
          evidence_excerpt?: string | null;
          evidence_status?: string;
          observed_at?: string | null;
          evidence_key: string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          discovery_run_id?: string;
          service_profile_id?: string;
          source?: string;
          source_post_id?: string | null;
          source_url?: string | null;
          query_type?: string;
          query_phrase?: string;
          title?: string | null;
          source_text?: string;
          evidence_excerpt?: string | null;
          evidence_status?: string;
          observed_at?: string | null;
          evidence_key?: string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      discovery_run_events: {
        Row: {
          id: number;
          tenant_id: string;
          run_id: string;
          source: string;
          query_type: string;
          query_hash: string;
          event_key: string;
          phase: string;
          outcome: string;
          details: Json;
          occurred_at: string;
        };
        Insert: {
          id?: number;
          tenant_id: string;
          run_id: string;
          source: string;
          query_type: string;
          query_hash: string;
          event_key: string;
          phase: string;
          outcome: string;
          details?: Json;
          occurred_at?: string;
        };
        Update: {
          id?: number;
          tenant_id?: string;
          run_id?: string;
          source?: string;
          query_type?: string;
          query_hash?: string;
          event_key?: string;
          phase?: string;
          outcome?: string;
          details?: Json;
          occurred_at?: string;
        };
        Relationships: [];
      };
      lead_feedback: {
        Row: {
          id: string;
          tenant_id: string;
          lead_match_id: string;
          user_id: string;
          feedback_type: string;
          reason_code: string | null;
          details: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          lead_match_id: string;
          user_id: string;
          feedback_type: string;
          reason_code?: string | null;
          details?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          lead_match_id?: string;
          user_id?: string;
          feedback_type?: string;
          reason_code?: string | null;
          details?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tenant_users: {
        Row: {
          tenant_id: string;
          user_id: string;
          role: string;
          created_at: string | null;
        };
        Insert: {
          tenant_id: string;
          user_id: string;
          role?: string;
          created_at?: string | null;
        };
        Update: {
          tenant_id?: string;
          user_id?: string;
          role?: string;
          created_at?: string | null;
        };
        Relationships: [];
      };
      api_keys: {
        Row: {
          id: string;
          tenant_id: string;
          key_id: string;
          key_hash: string;
          key_last4: string;
          created_at: string | null;
          created_by: string | null;
          revoked_at: string | null;
          last_used_at: string | null;
          label: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          key_id: string;
          key_hash: string;
          key_last4: string;
          created_at?: string | null;
          created_by?: string | null;
          revoked_at?: string | null;
          last_used_at?: string | null;
          label?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          key_id?: string;
          key_hash?: string;
          key_last4?: string;
          created_at?: string | null;
          created_by?: string | null;
          revoked_at?: string | null;
          last_used_at?: string | null;
          label?: string | null;
        };
        Relationships: [];
      };
      events: {
        Row: {
          id: string;
          tenant_id: string;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          created_at?: string | null;
        };
        Relationships: [];
      };
      anomaly_states: {
        Row: {
          id: string;
          tenant_id: string | null;
          agent_id: string | null;
          metric: string | null;
          date: string | null;
          filters: Json[] | null;
          diagnostic_summary: string | null;
          status: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          agent_id?: string | null;
          metric?: string | null;
          date?: string | null;
          filters?: Json[] | null;
          diagnostic_summary?: string | null;
          status?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          agent_id?: string | null;
          metric?: string | null;
          date?: string | null;
          filters?: Json[] | null;
          diagnostic_summary?: string | null;
          status?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      manual_interventions: {
        Row: Record<string, any>;
        Insert: Record<string, any>;
        Update: Record<string, any>;
        Relationships: [];
      };
      churn_risk_state: {
        Row: Record<string, any>;
        Insert: Record<string, any>;
        Update: Record<string, any>;
        Relationships: [];
      };
      recovery_emails: {
        Row: Record<string, any>;
        Insert: Record<string, any>;
        Update: Record<string, any>;
        Relationships: [];
      };
    } & Record<string, GenericTable>;
    Views: Record<string, never>;
    Functions: Record<string, { Args: Record<string, Json>; Returns: Json }>;
    Enums: Record<string, string>;
    CompositeTypes: Record<string, unknown>;
  };
};
