// lib/seo/compliance-standards-1.tsx

import { SEOPageData } from './index';

/**
 * SEO Compliance Campaign: Zero-Copy Analytics Architecture
 * Target Audience: Enterprise Architects, Head of IT, Cloud Infrastructure Leads
 * Core Focus: Decentralized BI, Federated Querying, eliminating ETL/Reverse-ETL.
 * Upgraded to SEO v10 Architecture (Intent, Realism, Info Gain, UI Blocks)
 */
export const zeroCopyAnalytics: SEOPageData = {
  type: 'campaign',
  searchIntent: {
    primary: 'Understand the security and architectural benefits of Zero-Copy AI Analytics',
    secondary: ['Eliminate ETL for BI', 'Federated query AI architectures', 'Decentralized BI security'],
    queryPriority: 'Tier 1',
    queryClass: ['Informational', 'Commercial investigation']
  },
  serpRealism: {
    targetPosition: 'Top 3 for "Zero Copy AI Analytics" & "No ETL BI"',
    competitionDifficulty: 'Medium',
    domainAdvantage: 'Leveraging a contrarian architectural stance (decentralized compute) against legacy centralized BI vendors.'
  },
  informationGain: 'Quantifying the reduction of attack surfaces by completely eliminating the need to extract, transform, load, or cache data in third-party vendor clouds for analytics.',
  uiBlocks: [
    {
      visualizationType: 'MetricsChart',
      dataMapping: 'executiveSummary',
      interactionPurpose: 'High-impact scannable validation of architectural claims.',
      intentServed: 'Trust building for Cloud Infrastructure Leads.'
    },
    {
      visualizationType: 'ProcessStepper',
      dataMapping: 'securityGuardrails',
      interactionPurpose: 'Step-by-step visualization of how a query is compiled without moving data.',
      intentServed: 'Architectural clarity for Enterprise Architects.'
    }
  ],
  seo: {
    title: 'Zero Copy AI Analytics | Decentralized BI Platform | Arcli',
    description: 'The most secure way to analyze data is to never move it. Arcli’s zero copy AI analytics platform generates federated queries directly inside your VPC.',
    h1: 'Zero Copy Analytics Architecture',
    keywords: ['Zero copy analytics', 'Federated query AI', 'Decentralized AI BI', 'Zero data movement BI', 'No ETL analytics AI'],
    intent: 'campaign',
    canonicalDomain: 'https://arcli.tech/architecture/zero-copy'
  },
  hero: {
    badge: 'ARCHITECTURAL STANDARD',
    title: 'The Best Way to Secure Data is to Never Move It.',
    subtitle: 'Every time you copy data from your warehouse to a BI vendor’s cloud, you multiply your attack surface. Arcli is a decentralized, Zero-Copy AI orchestrator that sends logic to your data, not your data to our logic.',
    primaryCTA: { text: 'View Architectural Diagram', href: '/docs/architecture' },
    secondaryCTA: { text: 'Start Free Trial', href: '/register' }
  },

  // Maps to ExecutiveSummary in seo-blocks-3.tsx
  executiveSummary: [
    { value: '0', label: 'ETL Pipelines Required' },
    { value: '100%', label: 'Compute in Your VPC' },
    { value: '0MB', label: 'Data Exfiltrated' },
    { value: 'O(1)', label: 'Data Freshness' }
  ],

  // Maps to ContrarianBanner in seo-blocks-3.tsx
  contrarianBanner: {
    statement: "Your cloud data warehouse is incredibly secure. The BI tools you connect to it are the vulnerability.",
    subtext: "Vendors demand that you extract, transform, load, and cache your most sensitive data onto their proprietary servers just to render a bar chart. Arcli fundamentally rejects this model."
  },

  // Maps to SecurityGuardrails in seo-blocks-3.tsx
  securityGuardrails: [
    {
      title: 'Decentralized Compute Execution',
      depthLevel: 'Surface',
      description: 'Arcli acts solely as a compilation engine. We translate natural language into dialect-perfect SQL. We then dispatch that SQL string to your Snowflake or Postgres cluster. Your infrastructure does the heavy lifting.'
    },
    {
      title: 'Stateless Chart Rendering',
      depthLevel: 'Intermediate',
      description: 'When your database returns the results of an AI-generated query, Arcli only holds the lightweight JSON aggregate in memory for the milliseconds required to render the UI visualization. Nothing is written to disk.'
    },
    {
      title: 'Identity Provider (IdP) Passthrough',
      depthLevel: 'Deep',
      description: 'Arcli passes the end-user’s identity directly through to the database connection layer via OAuth or JWT. If a user tries to ask the AI for data they cannot access in the database, the query fails at the warehouse level.'
    }
  ],

  // Maps to StrategicQuery in seo-blocks-3.tsx
  strategicScenario: {
    title: 'Federated Query Generation',
    description: 'Zero-copy means querying data exactly where it lives. Arcli excels at generating complex federated queries (e.g., Snowflake External Tables or Postgres FDW), allowing the AI to join structured warehouse data with raw S3 data seamlessly.',
    dialect: 'Snowflake (External Tables)',
    sql: `-- Generated by Arcli AI Orchestrator
SELECT 
    c.customer_segment,
    COUNT(DISTINCT e.user_id) AS active_users,
    SUM(TRY_CAST(e.value:purchase_amount::STRING AS FLOAT)) AS total_raw_revenue
FROM 
    production.core.customers c
JOIN 
    data_lake.s3_external.raw_clickstream e 
    ON c.customer_id = e.value:user_id::STRING
WHERE 
    e.event_type = 'checkout_success'
    AND e.event_date >= DATEADD(month, -1, CURRENT_DATE())
    AND c.status = 'ACTIVE'
GROUP BY 
    c.customer_segment
ORDER BY 
    total_raw_revenue DESC;`,
    businessOutcome: 'Allows analysts to instantly join curated customer dimensions in the warehouse with raw, unstructured JSON clickstream data in an S3 data lake, without building an ETL pipeline to move the S3 data.'
  },

  faqs: [
    {
      q: 'If Arcli is Zero-Copy, how does the AI know what my data means?',
      a: 'We perform a one-time sync of your database schema (metadata). This includes table names, column names, data types, and foreign key relationships. We vectorize this metadata to ground the LLM, but we never ingest the actual rows of data.',
      persona: 'Data Architect',
      intent: 'Technical Validation'
    },
    {
      q: 'Does Zero-Copy mean queries are slower?',
      a: 'Not necessarily. While we don’t cache data, we leverage the massive parallel processing power of your cloud warehouse (like BigQuery or Snowflake). Because we write highly optimized, dialect-specific SQL, execution times are typically sub-second.',
      persona: 'Performance Engineer',
      intent: 'Objection Handling'
    },
    {
      q: 'Can Arcli connect to on-premises databases without a VPN?',
      a: 'For on-premises databases behind a strict firewall, we provide a lightweight, open-source Arcli Agent. It runs inside your network, establishing a secure outbound-only WebSocket tunnel to receive compiled SQL from the Orchestrator.',
      persona: 'Network Administrator',
      intent: 'Infrastructure Capability'
    }
  ]
};

/**
 * SEO Compliance Campaign: AI Query Auditing & Data Governance
 * Target Audience: Compliance Officers, DPO (Data Protection Officers), InfoSec
 * Core Focus: Audit logs, cryptographic provenance, non-repudiation.
 * Upgraded to SEO v10 Architecture
 */
export const queryAuditingGovernance: SEOPageData = {
  type: 'campaign',
  searchIntent: {
    primary: 'Evaluate compliance, auditing, and governance features for AI analytics platforms',
    secondary: ['AI query auditing', 'Cryptographic query logging', 'Preventing AI data exfiltration'],
    queryPriority: 'Tier 1',
    queryClass: ['Commercial investigation', 'Informational']
  },
  serpRealism: {
    targetPosition: 'Top 3 for "AI Data Governance Analytics"',
    competitionDifficulty: 'High',
    domainAdvantage: 'Positioning Arcli as the only platform treating AI-generated SQL as a strictly auditable, cryptographically signed artifact.'
  },
  informationGain: 'Bridging the gap between the "black-box" nature of most AI tools and the strict non-repudiation requirements of Enterprise compliance frameworks (SOC2, GDPR, HIPAA).',
  uiBlocks: [
    {
      visualizationType: 'DataRelationshipsGraph',
      dataMapping: 'features',
      interactionPurpose: 'Illustrate the flow of an audit log from generation to SIEM webhook ingestion.',
      intentServed: 'Operational workflow visualization for SecOps.'
    },
    {
      visualizationType: 'ComparisonTable',
      dataMapping: 'contrarianBanner',
      interactionPurpose: 'Highlight the difference between obscure Chat-BI logic and transparent, auditable SQL generation.',
      intentServed: 'Persuasion for Risk and Compliance Officers.'
    }
  ],
  seo: {
    title: 'AI Query Auditing & Data Governance Analytics | Arcli',
    description: 'Maintain absolute control over your AI analytics. Arcli provides cryptographic query logging, granular RBAC, and strict data governance for enterprise AI.',
    h1: 'Enterprise AI Data Governance',
    keywords: ['AI query auditing', 'Cryptographic query logging', 'Data governance AI analytics', 'AI compliance logging', 'Secure AI BI audit'],
    intent: 'campaign',
    canonicalDomain: 'https://arcli.tech/compliance/query-auditing'
  },
  hero: {
    badge: 'GOVERNANCE & COMPLIANCE',
    title: 'Know Exactly What the AI Asked Your Database.',
    subtitle: 'Black-box AI is a compliance nightmare. Arcli provides a transparent, immutable audit trail of every natural language request, the exact SQL generated, and the user identity that executed it.',
    primaryCTA: { text: 'Schedule a Security Demo', href: '/book-demo' },
    secondaryCTA: { text: 'View Trust Center', href: '/security' }
  },

  executiveSummary: [
    { value: '100%', label: 'Cryptographic Auditing' },
    { value: 'SIEM', label: 'Native Integration' },
    { value: 'GDPR', label: 'Compliant Architecture' },
    { value: 'Read-Only', label: 'Enforced' }
  ],

  // Maps to features in standard blocks to explain the tech
  features: {
    title: 'The Arcli Governance Framework',
    items: [
      {
        title: 'Cryptographic Provenance',
        depthLevel: 'Intermediate',
        description: 'Every query executed by Arcli is hashed and logged with a tamper-evident timestamp. Auditors can verify that the generated SQL was not altered post-execution.',
        icon: 'Lock'
      },
      {
        title: 'SIEM Webhook Integration',
        depthLevel: 'Deep',
        description: 'Stream Arcli audit logs directly into Datadog, Splunk, or AWS CloudTrail in real-time. Trigger automated alerts if a user requests data outside their normal behavioral baseline.',
        icon: 'Network'
      },
      {
        title: 'Granular Role-Based Access (RBAC)',
        depthLevel: 'Surface',
        description: 'Map your Okta or Azure AD groups directly to Arcli. Restrict which LLM models users can access, which databases they can query, and which metrics they are allowed to calculate.',
        icon: 'Users'
      }
    ]
  },

  contrarianBanner: {
    statement: "If you can't prove exactly how the AI arrived at an answer, you can't use it in the enterprise.",
    subtext: "Many 'Chat with Data' tools obscure the underlying logic, leaving compliance teams blind to potential data exposure. Arcli is fundamentally transparent: the compiled SQL is always visible, logged, and exportable."
  },

  // Using a Strategic Scenario to show how Arcli can audit its own logs (Meta)
  strategicScenario: {
    title: 'Auditing the Audit Logs (PostgreSQL)',
    description: 'Because Arcli logs all its own activity to an accessible schema, Security Operations (SecOps) teams can use Arcli’s AI to analyze Arcli’s own usage logs for anomaly detection.',
    dialect: 'PostgreSQL',
    sql: `-- Generated by Arcli AI Orchestrator
SELECT 
    user_email,
    COUNT(query_id) AS total_queries_executed,
    COUNT(CASE WHEN result_row_count > 1000000 THEN 1 END) AS massive_extractions,
    MAX(executed_at) AS last_active
FROM 
    arcli_system.audit_logs
WHERE 
    executed_at >= CURRENT_DATE - INTERVAL '7 days'
    AND database_target = 'production_pii_vault'
GROUP BY 
    user_email
HAVING 
    COUNT(CASE WHEN result_row_count > 1000000 THEN 1 END) > 5
ORDER BY 
    massive_extractions DESC;`,
    businessOutcome: 'Instantly identifies any internal users who have repeatedly executed AI queries that returned over 1 million rows of PII data within the last 7 days, flagging potential data exfiltration attempts.'
  },

  faqs: [
    {
      q: 'How long does Arcli retain audit logs?',
      a: 'By default, Arcli retains detailed audit logs for 90 days within our managed cloud. However, Enterprise customers can configure automated daily exports to their own S3 buckets for infinite, compliant retention.',
      persona: 'Data Protection Officer',
      intent: 'Data Retention Requirements'
    },
    {
      q: 'Can Arcli mask PII data before it reaches the UI?',
      a: 'Yes. In addition to relying on your database’s inherent Data Masking policies, Arcli provides an application-level regex masking engine that automatically redacts SSNs, credit cards, or email addresses from the visualized results.',
      persona: 'CISO',
      intent: 'Data Security / Redaction'
    },
    {
      q: 'Does Arcli send our database schema to OpenAI?',
      a: 'Arcli supports an agnostic LLM routing layer. For highly sensitive schemas, you can route embedding and generation requests exclusively to private, zero-retention models hosted on Azure OpenAI, AWS Bedrock, or even local Llama 3 instances.',
      persona: 'VP of Engineering',
      intent: 'Vendor Risk Assessment'
    }
  ]
};