// lib/seo/database-integrations-3.tsx

import { SEOPageData } from './index';

/**
 * SEO Integration Page: Oracle Database
 * Target Audience: Enterprise CIOs, CISOs, Data Architects
 * Core Focus: Uncompromising security, PL/SQL dialect optimization, Zero-Data Movement.
 */
export const oracleIntegration: SEOPageData = {
  type: 'integration',
  seo: {
    title: 'Oracle Database AI Analytics Integration | Arcli',
    description: 'Connect AI directly to your Oracle Database with zero data movement. Generate highly optimized PL/SQL queries securely, without semantic layer hallucinations.',
    h1: 'Enterprise AI for Oracle Database',
    keywords: ['Oracle BI integration', 'Oracle AI analytics', 'PL/SQL generator', 'Zero data movement Oracle', 'Secure enterprise AI'],
    intent: 'integration',
    canonicalDomain: 'https://arcli.tech/integrations/oracle'
  },
  hero: {
    badge: 'ENTERPRISE DATABASE INTEGRATION',
    title: 'Unlock Oracle Data without Moving It.',
    subtitle: 'Arcli connects to your Oracle instances using strict Read-Only credentials. We generate the PL/SQL, your infrastructure executes it. Absolute security, zero data replication.',
    primaryCTA: { text: 'Connect Oracle Securely', href: '/register' },
    secondaryCTA: { text: 'View Security Whitepaper', href: '/security' }
  },
  
  // Maps to ExecutiveSummary in seo-blocks-3.tsx
  executiveSummary: [
    { value: '0MB', label: 'Data Replicated' },
    { value: '100%', label: 'PL/SQL Grounding' },
    { value: '< 60s', label: 'Time to Value' },
    { value: 'SOC2', label: 'Type II Certified' }
  ],

  // Maps to ContrarianBanner in seo-blocks-3.tsx
  contrarianBanner: {
    statement: "You don't need another expensive semantic layer or a 6-month BI migration.",
    subtext: "Legacy BI vendors want you to extract, transform, and load your Oracle data into their proprietary clouds. Arcli fundamentally disagrees. Keep your data where it belongs; let our AI learn your schema and write the execution logic natively."
  },

  // Maps to SecurityGuardrails in seo-blocks-3.tsx
  securityGuardrails: [
    {
      title: 'Zero-Data Movement Architecture',
      description: 'Your Oracle tables never leave your VPC. Arcli only ingests schema metadata (column names, types, foreign keys) to contextually ground the AI. Compute stays local.'
    },
    {
      title: 'Enforced Read-Only Execution',
      description: 'Arcli connects exclusively via restricted Read-Only Service Accounts. It is architecturally impossible for our platform to execute INSERT, UPDATE, DELETE, or DROP statements.'
    },
    {
      title: 'End-to-End Query Auditing',
      description: 'Every PL/SQL query generated and executed is cryptographically logged. Security and governance teams maintain full visibility into exactly what the AI asked your database.'
    }
  ],

  // Maps to StrategicQuery in seo-blocks-3.tsx
  strategicScenario: {
    title: 'Complex PL/SQL Partition Querying',
    description: 'Oracle databases excel at massive, partitioned datasets. Arcli understands Oracle-specific indexing and partitioning strategies, generating dialect-perfect PL/SQL that won\'t bottleneck your system.',
    dialect: 'Oracle PL/SQL',
    sql: `-- Generated by Arcli AI Orchestrator
SELECT 
    d.department_name,
    COUNT(e.employee_id) AS total_employees,
    SUM(e.salary) AS total_payroll,
    ROUND(AVG(e.salary), 2) AS average_salary
FROM 
    employees PARTITION (emp_current_year) e
JOIN 
    departments d ON e.department_id = d.department_id
WHERE 
    e.hire_date >= TRUNC(SYSDATE, 'YYYY')
    AND e.status = 'ACTIVE'
GROUP BY 
    d.department_name
HAVING 
    COUNT(e.employee_id) > 10
ORDER BY 
    total_payroll DESC
FETCH FIRST 5 ROWS ONLY;`,
    businessOutcome: 'Instantly identifies the top 5 cost-center departments for the current fiscal year without requiring an analyst to manually navigate complex table partitions.'
  },

  faqs: [
    {
      q: 'Does Arcli support Oracle Cloud Infrastructure (OCI) and On-Premises?',
      a: 'Yes. As long as a secure connection tunnel (like an SSH bastion or VPC peering) can be established, Arcli can analyze the schema. We strongly recommend our On-Prem Agent for highly restricted environments.',
      persona: 'Data Engineer'
    },
    {
      q: 'How do you prevent the AI from generating inefficient table scans?',
      a: 'Arcli ingests index metadata during the initial sync. The query planner is instructed to utilize existing indexes and partitions, ensuring the generated PL/SQL is highly performant.',
      persona: 'Database Administrator'
    },
    {
      q: 'Will Arcli retain my proprietary customer data?',
      a: 'No. Arcli never stores row-level data. We only process the aggregate results returned by your database in memory to render charts, immediately discarding the data afterward.',
      persona: 'CISO'
    }
  ]
};

/**
 * SEO Integration Page: ClickHouse
 * Target Audience: Engineering Leaders, Product Managers, Real-Time Analytics Teams
 * Core Focus: Blistering speed, real-time data, dialect-specific aggregation functions.
 */
export const clickhouseIntegration: SEOPageData = {
  type: 'integration',
  seo: {
    title: 'ClickHouse AI Analytics Integration | Arcli',
    description: 'Interact with your real-time ClickHouse clusters using natural language. Arcli writes optimized ClickHouse SQL to visualize massive datasets in milliseconds.',
    h1: 'Real-Time AI Analytics for ClickHouse',
    keywords: ['ClickHouse AI', 'ClickHouse BI tool', 'Real-time analytics AI', 'ClickHouse SQL generator'],
    intent: 'integration',
    canonicalDomain: 'https://arcli.tech/integrations/clickhouse'
  },
  hero: {
    badge: 'HIGH-PERFORMANCE ANALYTICS',
    title: 'Chat with Billions of Rows in Milliseconds.',
    subtitle: 'Harness the blistering speed of ClickHouse without writing complex SQL. Arcli grounds its AI in your schema to generate dialect-perfect, real-time analytics instantly.',
    primaryCTA: { text: 'Connect ClickHouse', href: '/register' },
    secondaryCTA: { text: 'Read the Docs', href: '/docs/clickhouse' }
  },

  executiveSummary: [
    { value: 'Billion+', label: 'Row Scale' },
    { value: 'Sub-sec', label: 'Query Latency' },
    { value: '100%', label: 'ClickHouse SQL' },
    { value: 'Zero', label: 'Data Cached' }
  ],

  contrarianBanner: {
    statement: "Standard SQL generators fail spectacularly on ClickHouse.",
    subtext: "ClickHouse has unique data types, massive arrays, and specialized aggregation functions (like argMax or quantiles). Generic LLMs hallucinate standard Postgres SQL. Arcli natively understands the ClickHouse dialect."
  },

  securityGuardrails: [
    {
      title: 'Stateless Result Processing',
      description: 'Because ClickHouse handles billions of rows, Arcli relies on the database to perform the heavy lifting. We only retrieve the final, lightweight aggregate payloads to render visualizations.'
    },
    {
      title: 'Query Timeouts & Memory Limits',
      description: 'Arcli automatically appends strict `max_execution_time` and memory constraint settings to every generated query, ensuring AI requests never overload your production clusters.'
    },
    {
      title: 'Strict Schema Grounding',
      description: 'We map ClickHouse specific types (Array, Map, Tuple, LowCardinality) into our vector embedding layer so the AI understands exactly how your high-velocity data is structured.'
    }
  ],

  strategicScenario: {
    title: 'Real-Time Web Analytics Aggregation',
    description: 'Analyzing user sessions across billions of events requires ClickHouse-specific aggregation arrays and windowing functions. Arcli generates these seamlessly.',
    dialect: 'ClickHouse SQL',
    sql: `-- Generated by Arcli AI Orchestrator
SELECT
    toStartOfHour(event_time) AS hour,
    uniqExact(user_id) AS unique_visitors,
    countIf(event_type = 'checkout_complete') AS conversions,
    round(conversions / unique_visitors * 100, 2) AS conversion_rate,
    quantilesTiming(0.5, 0.95)(page_load_ms) AS load_time_p50_p95
FROM 
    production.web_events
WHERE 
    event_time >= now() - INTERVAL 24 HOUR
    AND domain = 'app.acme.com'
GROUP BY 
    hour
ORDER BY 
    hour DESC
FORMAT JSON;`,
    businessOutcome: 'Provides product teams with a real-time visualization of conversion rates vs page load latency (P50/P95) over the last 24 hours, pinpointing performance bottlenecks instantly.'
  },

  faqs: [
    {
      q: 'Does Arcli support ClickHouse Cloud as well as self-hosted?',
      a: 'Yes, Arcli seamlessly connects to both ClickHouse Cloud (via standard HTTPS/native ports) and self-hosted Open Source ClickHouse clusters.',
      persona: 'Engineering Manager'
    },
    {
      q: 'How does Arcli handle ClickHouse arrays and nested types?',
      a: 'Arcli\'s semantic engine is specifically trained on ClickHouse syntax. When a user asks about nested data, the AI correctly utilizes functions like `arrayJoin` or `JSONExtract` instead of standard SQL JOINs.',
      persona: 'Data Engineer'
    },
    {
      q: 'Can I restrict which tables Arcli has access to?',
      a: 'Absolutely. Security is paramout. We recommend creating a specific ClickHouse user for Arcli and granting `SELECT` privileges only to the specific databases, tables, or materialized views you want to expose to the AI.',
      persona: 'CISO'
    }
  ]
};