import React from 'react';
import { TrendingUp, FileText, LayoutTemplate } from 'lucide-react';

export type SEOPageData = {
  type: 'feature' | 'integration' | 'comparison' | 'guide' | 'template';
  title: string;
  description: string;
  h1: string;
  subtitle: string;
  icon: React.ReactElement;
  features: string[];
  steps: { name: string; text: string }[];
  useCases: { title: string; description: string }[];
  faqs: { q: string; a: string }[];
  comparison?: { 
    competitor: string; 
    dataOmenWins: string[]; 
    competitorFlaws: string[]; 
  };
  relatedSlugs: string[];
};

export const howToGuides: Record<string, SEOPageData> = {
  'how-to-analyze-sales-data': {
    type: 'guide',
    title: 'How to Analyze Sales Data with AI | DataOmen',
    description: 'A step-by-step guide on analyzing sales data, pipeline velocity, and rep performance using AI and natural language.',
    h1: 'How to Analyze Sales Data Without Excel',
    subtitle: 'Learn how to automatically extract win rates, pipeline velocity, and forecasting metrics using AI.',
    icon: <TrendingUp className="w-12 h-12 text-green-500 mb-6" />,
    features: ['Pipeline Velocity Formulas', 'Win/Loss Tracking', 'Automated Forecasting'],
    steps: [
      { name: 'Export or Connect', text: 'Connect your CRM directly or upload a CSV export of your Opportunities.' },
      { name: 'Ask for Velocity', text: 'Type: "Calculate our pipeline velocity by sales rep for Q3."' },
      { name: 'Generate Forecast', text: 'Ask the AI to project Q4 revenue based on historical win rates and current open pipeline.' }
    ],
    useCases: [
      { title: 'Sales Operations', description: 'Automate your weekly sales forecasting models.' }
    ],
    faqs: [
      { q: 'What metrics should I track?', a: 'Focus on Win Rate, Average Deal Size, Sales Cycle Length, and Pipeline Velocity.' }
    ],
    relatedSlugs: ['analyze-salesforce-data', 'sales-dashboard-template']
  },

  'how-to-build-dashboard-from-csv': {
    type: 'guide',
    title: 'How to Build a Dashboard from a CSV File | DataOmen',
    description: 'Learn how to instantly turn a static CSV or Excel file into a live, interactive business dashboard using AI.',
    h1: 'Turn Any CSV into a Dashboard in 60 Seconds',
    subtitle: 'Stop messing with pivot tables. Upload your CSV and let AI generate a full reporting suite.',
    icon: <FileText className="w-12 h-12 text-blue-400 mb-6" />,
    features: ['Instant Visualization', 'Auto-Pivot', 'Shareable Links'],
    steps: [
      { name: 'Upload the File', text: 'Drag and drop your CSV into the DataOmen interface.' },
      { name: 'Let AI Inspect', text: 'Our engine reads the headers and determines the optimal chart types.' },
      { name: 'Publish', text: 'Click "Generate Dashboard" and share the secure link with your team.' }
    ],
    useCases: [
      { title: 'Ad-Hoc Reporting', description: 'Quickly visualize survey results, financial exports, or marketing lists.' }
    ],
    faqs: [
      { q: 'Is there a file size limit?', a: 'You can upload CSVs up to 1GB directly in the browser.' }
    ],
    relatedSlugs: ['analyze-csv-with-ai', 'ai-dashboard-builder']
  },

  'how-to-build-sql-dashboard': {
    type: 'guide',
    title: 'How to Build a SQL Dashboard Without Coding | DataOmen',
    description: 'Learn how to connect your SQL database and build an automated, live-updating dashboard using AI instead of writing code.',
    h1: 'How to Build a SQL Dashboard in Minutes',
    subtitle: 'Stop writing thousands of lines of SQL to update charts. Let AI generate the queries and build the layout for you.',
    icon: <LayoutTemplate className="w-12 h-12 text-indigo-400 mb-6" />,
    features: ['Auto-Generated SQL', 'Live Database Syncing', 'Interactive Filtering'],
    steps: [
      { name: 'Connect Database', text: 'Add your Postgres, MySQL, or Snowflake credentials.' },
      { name: 'Ask for Metrics', text: 'Type: "Create a dashboard showing Daily Active Users, MRR, and Churn Rate."' },
      { name: 'Pin to Board', text: 'The AI executes the SQL. Click "Pin" to add the resulting charts to your live board.' }
    ],
    useCases: [
      { title: 'Engineering Metrics', description: 'Quickly spin up dashboards monitoring database health and error logs.' }
    ],
    faqs: [
      { q: 'Can I view the underlying SQL?', a: 'Yes. You can inspect, modify, and export the exact SQL queries generated by the AI.' }
    ],
    relatedSlugs: ['postgresql-ai-analytics', 'natural-language-to-sql']
  }
};