// lib/seo/index.tsx

// --- Static Import Layer ---
// Using the statically generated registry instead of dynamic fs/require
// to guarantee 100% compatibility with Next.js/Turbopack serverless builds.
import * as registryModule from './registry';

// We explicitly target the flat SEO_REGISTRY object generated by registry.ts
const seoRegistry = (registryModule as Record<string, any>).SEO_REGISTRY || (registryModule as Record<string, any>).default || {};

// --- 1. The Polymorphic Type Definition System ---
export interface BaseSEOPageData {
  // Made optional for V2 (Block Architecture)
  type?: 'guide' | 'comparison' | 'integration' | 'feature' | 'template' | 'campaign' | 'default';
  
  // V2 Specific Properties
  blocks?: any[];
  meta?: any;

  // V1 / Normalized Properties
  seo?: {
    title: string;
    description: string;
    h1: string;
    datePublished?: string;
    dateModified?: string;
    // Added to support advanced SEO template architectures
    canonicalDomain?: string; 
    keywords?: string[];
    intent?: 'template' | 'guide' | 'comparison' | string;
    [key: string]: any; // Allows future nested meta extensions
  };
  hero?: any; // Note: Can be strictly typed to a specific Hero interface
  demo?: any;
  personas?: any;
  matrix?: any;
  workflow?: any;
  useCases?: any;
  steps?: any;
  features?: any;
  architecture?: any;
  faqs?: { 
    q: string; 
    a: string; 
    persona?: string; // Added for persona-driven targeted FAQs 
    [key: string]: any; 
  }[];
  relatedSlugs?: string[];
  [key: string]: any; // Polymorphic catch-all for silo-specific root data (e.g., assets, technicalStack)
}

export interface TemplateBlueprint extends BaseSEOPageData {
  type: 'template';
  // Add template-specific structural overrides here if necessary
}

export type SEOPageData = BaseSEOPageData | TemplateBlueprint;

// --- 2. Centralized Registry Manifest Loading ---

let seoPagesCache: Record<string, SEOPageData> | null = null;
let seoCategoryCache: Record<string, Record<string, SEOPageData>> | null = null;

/**
 * Shared Computation Layer: Hydrates the full SEO registry from the static map.
 * Evaluates lazily to optimize Next.js server startup and memory chunking.
 * Statically traceable by Webpack/Turbopack.
 */
function hydrateRegistry() {
  if (seoPagesCache) return;

  seoPagesCache = {};
  seoCategoryCache = {};

  try {
    if (!seoRegistry || Object.keys(seoRegistry).length === 0) {
      console.warn('⚠️ Static SEO Registry not found or empty. Ensure generate-registry.mjs ran successfully.');
      return;
    }
    
    // Process the flat map of slug -> SEOPageData generated by registry.ts
    for (const [slug, pageData] of Object.entries(seoRegistry)) {
      // [FIX] V2 Pages do NOT have a top-level 'type' attribute, they have 'blocks'. 
      // This validates BOTH versions of the data structure and prevents downstream undefined crashes.
      if (!pageData || typeof pageData !== 'object' || (!('type' in pageData) && !('blocks' in pageData))) {
        continue;
      }

      const data = pageData as SEOPageData;
      seoPagesCache[slug] = data;
      
      const category = data.type || 'default';
      if (!seoCategoryCache[category]) {
        seoCategoryCache[category] = {};
      }
      seoCategoryCache[category][slug] = data;
    }
  } catch (error) {
    console.error('Error hydrating SEO Registry:', error);
    seoPagesCache = {};
    seoCategoryCache = {};
  }
}

export type SEOCategory = string;

// --- 3. Engineering Excellence Selectors (O(1) Lookups) ---

/**
 * Retrieves full metadata for a specific slug.
 */
export const getPage = (slug: string): SEOPageData | undefined => {
  hydrateRegistry();
  return seoPagesCache?.[slug];
};

/**
 * Returns all unique slugs for Next.js generateStaticParams().
 */
export const getAllSlugs = (): string[] => {
  hydrateRegistry();
  return Object.keys(seoPagesCache || {});
};

/**
 * Type-Guard: Template Identifier
 */
export function isTemplatePage(page: SEOPageData): page is TemplateBlueprint {
  return page.type === 'template';
}

/**
 * Retrieves all pages belonging to a specific architectural silo.
 */
export const getPagesByCategory = (category: SEOCategory): Record<string, SEOPageData> => {
  hydrateRegistry();
  return seoCategoryCache?.[category] || {};
};

/**
 * Internal Linking Optimizer
 * Returns full page data for a list of slugs, used to build "Related Articles".
 */
export const getRelatedPages = (slugs: string[]): SEOPageData[] => {
  hydrateRegistry();
  return slugs
    .map(slug => seoPagesCache?.[slug])
    .filter((page): page is SEOPageData => !!page);
};

// --- 4. Arcli Constants ---

export const ARCLI_SUPPORT_EMAIL = 'support@arcli.tech';
export const ARCLI_DOMAIN = 'arcli.tech';