// lib/seo/industry-verticals-1.tsx

import { SEOPageData } from './index';

/**
 * SEO Industry Campaign: Healthcare & Life Sciences
 * Target Audience: Chief Medical Information Officers (CMIO), Healthcare CISOs, Data Architects
 * Core Focus: HIPAA Compliance, PHI (Protected Health Information) Security, Zero-Data Movement, FHIR R4.
 */
export const healthcareIndustry: SEOPageData = {
  type: 'campaign',
  seo: {
    title: 'HIPAA Compliant AI Analytics | Zero Data Movement BI | Arcli',
    description: 'Deploy AI on top of your EHR and clinical data without moving PHI. Arcli’s read-only, VPC-native architecture generates secure SQL directly in your warehouse.',
    h1: 'HIPAA-Compliant AI Analytics for Healthcare Data',
    keywords: [
      'HIPAA compliant AI analytics', 
      'Healthcare BI zero data movement', 
      'VPC native AI BI tool',
      'query FHIR data with SQL AI',
      'AI for EHR analytics without ETL',
      'secure patient data analytics platform',
      'Epic Systems AI reporting',
      'Cerner zero copy analytics',
      'healthcare data lake text-to-sql',
      'CMIO healthcare dashboard AI',
      'hospital readmission predictive analytics',
      'medical records AI querying',
      'FHIR R4 JSONB analytics',
      'zero data replication healthcare BI',
      'HIPAA BAA AI analytics',
      'clinical trial cohort discovery AI'
    ],
    intent: 'campaign',
    canonicalDomain: 'https://arcli.tech/industries/healthcare'
  },
  hero: {
    badge: 'HEALTHCARE & LIFE SCIENCES',
    title: 'Query EHR Data with AI. Keep PHI in Your VPC.',
    subtitle: 'Extract insights from your clinical databases instantly. Arcli generates dialect-perfect SQL, but your secure infrastructure executes it. Zero data replication. Zero compliance risk.',
    primaryCTA: { text: 'Schedule a Security Review', href: '/book-demo' },
    secondaryCTA: { text: 'View VPC Architecture', href: '/security' }
  },

  // Cross-page Differentiation Signal: Healthcare Specific Architecture
  complianceStack: {
    standards: ['HIPAA BAA', 'HITECH', 'HITRUST CSF (Inherited)'],
    encryption: ['AES-256 at Rest', 'TLS 1.2+ in Transit', 'Stateless Memory Purge'],
    audit: ['Cryptographic Query Hashing', 'End-to-End Execution Logging', 'Automated Anomaly Flagging']
  },

  executiveSummary: [
    { value: '0MB', label: 'PHI Replicated' },
    { value: '100%', label: 'HIPAA Compliant' },
    { value: 'VPC', label: 'Native Execution' },
    { value: 'End-to-End', label: 'Audit Logging' }
  ],

  contrarianBanner: {
    statement: "Copying patient records into a third-party BI cloud is a massive liability.",
    subtext: "Legacy analytics force you to build complex ETL pipelines, duplicating sensitive PHI across multiple environments. Arcli fundamentally rejects this. Keep your data in your secure infrastructure; let our AI come to you."
  },

  securityGuardrails: [
    {
      title: 'Architectural PHI Protection',
      description: 'Arcli only ingests schema metadata (table structures, column names). Raw Protected Health Information never touches our servers. We generate the query; your warehouse handles the actual patient records.'
    },
    {
      title: 'Strict Read-Only Guarantee',
      description: 'We connect to your Epic, Cerner, or FHIR data lakes using heavily restricted, Read-Only service accounts. It is programmatically impossible for Arcli to mutate, update, or delete clinical data.'
    },
    {
      title: 'Cryptographic Query Auditing',
      description: 'Every interaction is logged via our Metric Governance layer. Compliance teams have full visibility into exactly what SQL was generated, who requested it, and when it executed.'
    }
  ],

  useCases: {
    title: 'High-Impact Clinical Analytics',
    items: [
      {
        title: 'Hospital Readmission Tracking',
        description: 'Instantly generate reports on 30-day readmission rates filtered by ICD-10 codes, attending physicians, or wards without waiting weeks for data engineering.',
        icon: 'Activity'
      },
      {
        title: 'Resource Allocation & Triage',
        description: 'Analyze real-time ER wait times versus staffing levels to optimize nurse and doctor shifts during peak influenza or local emergency events.',
        icon: 'Users'
      },
      {
        title: 'Clinical Trial Cohort Discovery',
        description: 'Quickly query massive genomic or patient history datasets to identify eligible participants for new trials based on highly specific JSONB inclusion criteria.',
        icon: 'Microscope'
      }
    ]
  },

  strategicScenario: {
    title: 'Postgres JSONB FHIR R4 Analysis',
    description: 'Standard BI tools choke on nested FHIR (Fast Healthcare Interoperability Resources) JSON blobs. Arcli natively understands nested JSONB and writes the precise Postgres operators needed.',
    dialect: 'PostgreSQL (JSONB)',
    sql: `-- Generated by Arcli Semantic Router & AI Orchestrator
WITH patient_metrics AS (
    SELECT 
        resource->>'id' AS patient_id,
        resource->>'gender' AS patient_gender,
        (resource->'extension'->0->>'valueDecimal')::numeric AS risk_score,
        jsonb_array_elements(resource->'address')->>'city' AS city
    FROM 
        fhir_patients
    WHERE 
        resource->>'resourceType' = 'Patient'
        AND (resource->'active')::boolean = true
)
SELECT 
    patient_gender,
    COUNT(patient_id) AS total_patients,
    ROUND(AVG(risk_score), 2) AS avg_risk_score
FROM 
    patient_metrics
WHERE 
    city = 'Boston'
GROUP BY 
    patient_gender
HAVING 
    COUNT(patient_id) > 50
ORDER BY 
    avg_risk_score DESC;`,
    businessOutcome: 'Empowers CMIOs to instantly extract patient risk scores deeply nested within FHIR JSON blobs, providing immediate population health insights without requiring complex ETL unnesting.'
  },

  // NEW: UI Hook mapping for DynamicChartFactory / InteractiveDemo
  interactiveDemoMap: {
    component: 'ProgressiveChart',
    defaultQuery: 'Show me the 30-day readmission rate for cardiac patients by ward',
    visualizationType: 'bar-chart'
  },

  faqs: [
    {
      q: 'Will Arcli sign a Business Associate Agreement (BAA)?',
      a: 'Yes. For Enterprise tier customers operating in the United States, we provide standard BAAs to satisfy HIPAA and HITECH regulatory requirements.',
      persona: 'Compliance Officer'
    },
    {
      q: 'Does Arcli store any data temporarily for caching?',
      a: 'Arcli only holds aggregate results in memory temporarily to render visual charts (e.g., "50 patients in Boston"). Row-level patient data is never stored on our disks and is purged instantly after the session.',
      persona: 'Head of Security'
    },
    {
      q: 'Can we self-host Arcli inside our own VPC?',
      a: 'Yes. For the strictest security postures, Arcli offers a Single-Tenant/VPC deployment model where both the Orchestrator and the UI run entirely within your firewalled environment.',
      persona: 'Data Architect'
    }
  ]
};

/**
 * SEO Industry Campaign: FinTech & Banking
 * Target Audience: CTOs, Chief Risk Officers (CRO), FinTech Data Leads
 * Core Focus: Ledger immutability, SOC2 Type II, RLS Passthrough, Zero-ETL.
 */
export const fintechIndustry: SEOPageData = {
  type: 'campaign',
  seo: {
    title: 'Financial Services AI Analytics | Zero-ETL BI Tool | Arcli',
    description: 'Query your core banking ledgers and payment gateways with natural language. Arcli guarantees zero data movement and immutable read-only security for FinTechs.',
    h1: 'Zero-ETL AI Analytics for Core Ledgers',
    keywords: [
      'Financial services AI analytics', 
      'Secure ledger BI tool', 
      'SOC2 compliant AI reporting', 
      'Zero-ETL banking analytics',
      'Zero copy analytics banking',
      'AI ledger analytics without ETL',
      'secure payment gateway BI',
      'SOC2 compliant text-to-SQL',
      'real-time liquidity AI dashboard',
      'Stripe data analytics zero copy',
      'fraud detection SQL generator',
      'core banking reporting automation',
      'payment velocity anomaly detection',
      'RLS aware financial BI',
      'immutable query logging AI',
      'capital ratio calculation SQL',
      'unit economics BI platform',
      'fintech row level security AI',
      'ledger reconciliation AI'
    ],
    intent: 'campaign',
    canonicalDomain: 'https://arcli.tech/industries/fintech'
  },
  hero: {
    badge: 'FINANCIAL SERVICES',
    title: 'Query Your Ledger. Keep It Secure.',
    subtitle: 'For modern FinTechs, moving transaction data is a non-starter. Arcli connects directly to your secure data warehouse, translating English into optimized SQL without ever extracting your customer’s financial data.',
    primaryCTA: { text: 'Start Free Trial', href: '/register' },
    secondaryCTA: { text: 'View SOC2 Report', href: '/security' }
  },

  financialDataModels: {
    supportedLedgers: ['Double-Entry Core Ledgers', 'Payment Gateways (Stripe, Adyen)', 'Trading Execution Logs'],
    coreMetrics: ['Liquidity & Capital Ratios', 'Real-time CAC/LTV', 'Net Revenue Retention (NRR)', 'Fraud Velocity'],
    securityPrerequisites: ['Strict Row-Level Security (RLS) Passthrough', 'VPC Peering', 'No-ETL Architecture Required']
  },

  executiveSummary: [
    { value: 'SOC2', label: 'Type II Certified' },
    { value: '100%', label: 'Stateless Compute' },
    { value: '0', label: 'Ledger Replications' },
    { value: 'RBAC', label: 'Row-Level Security' }
  ],

  contrarianBanner: {
    statement: "Your customer transaction data belongs in your vault, not a vendor's cache.",
    subtext: "If your BI tool requires a nightly sync of your core ledger, your attack surface just doubled. Arcli’s Zero-Data Movement architecture ensures that your financial data remains exactly where you put it—protected by your own warehouse policies."
  },

  securityGuardrails: [
    {
      title: 'Inherited Row-Level Security (RLS)',
      description: 'Arcli natively respects the RLS policies defined in your Snowflake or Postgres databases. The AI can never surface a transaction a user isn\'t explicitly authorized to see at the database level.'
    },
    {
      title: 'Zero-ETL Architecture',
      description: 'Skip the vulnerable middle-man. Because Arcli writes the SQL directly against your live schema, there are no brittle dbt pipelines or stale data lakes holding unencrypted PII.'
    },
    {
      title: 'Immutable Query Logging',
      description: 'Satisfy auditors instantly. Arcli maintains a tamper-proof cryptographic log of every single query the AI generates and executes, tracking the exact timestamp and Azure AD/Okta user identity.'
    }
  ],

  useCases: {
    title: 'Accelerate Financial Intelligence',
    items: [
      {
        title: 'Fraud & Anomaly Detection',
        description: 'Empower risk teams to query raw transaction velocity and geographic anomalies in real-time via the AI scratchpad, detecting micro-structuring before clearing.',
        icon: 'ShieldAlert'
      },
      {
        title: 'Liquidity & Capital Ratios',
        description: 'Treasury teams can ask complex questions about daily capital requirements and instantly receive mathematically sound calculations verified by our Semantic Metric Builder.',
        icon: 'Landmark'
      },
      {
        title: 'Unit Economics Tracking',
        description: 'Blend payment gateway data with your internal database to calculate exact Customer Acquisition Cost (CAC) vs. Lifetime Value (LTV) across product cohorts.',
        icon: 'TrendingUp'
      }
    ]
  },

  strategicScenario: {
    title: 'Snowflake Time-Travel & Windowing',
    description: 'Financial analysis requires precise window functions and array flattening. Arcli’s execution engine generates advanced Snowflake dialect SQL to process millions of ledger rows flawlessly.',
    dialect: 'Snowflake SQL',
    sql: `-- Generated by Arcli NL2SQL Generator
WITH daily_rollup AS (
    SELECT
        DATE_TRUNC('day', transaction_date) AS txn_day,
        merchant_category,
        SUM(amount) AS daily_volume
    FROM 
        core_ledger.production.transactions
    WHERE 
        status = 'SETTLED'
        AND transaction_date >= DATEADD(day, -30, CURRENT_DATE())
    GROUP BY 
        txn_day, merchant_category
)
SELECT
    txn_day,
    merchant_category,
    daily_volume,
    SUM(daily_volume) OVER (
        PARTITION BY merchant_category 
        ORDER BY txn_day
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ) AS rolling_7_day_volume
FROM 
    daily_rollup
ORDER BY 
    txn_day DESC, daily_volume DESC;`,
    businessOutcome: 'Provides the Head of Risk with a real-time, 7-day rolling average of transaction volumes to detect liquidity spikes, executing purely on Snowflake compute.'
  },

  interactiveDemoMap: {
    component: 'OmniscientScratchpad',
    defaultQuery: 'Calculate the 7-day rolling average for settled transactions by merchant category.',
    visualizationType: 'area-chart'
  },

  faqs: [
    {
      q: 'Is Arcli SOC 2 Type II compliant?',
      a: 'Yes. We undergo rigorous independent auditing to maintain our SOC 2 Type II certification, ensuring our security, availability, and confidentiality controls meet strict FinTech standards.',
      persona: 'Chief Risk Officer'
    },
    {
      q: 'How do you handle highly complex financial calculations like IRR or Yield?',
      a: 'Arcli grounds its AI not just in table names, but in semantic definitions via `SemanticMetricBuilder`. You define "Internal Rate of Return" once, and the AI will reliably insert the correct mathematical SQL logic every time.',
      persona: 'Data Engineer'
    },
    {
      q: 'Can Arcli connect to legacy mainframe databases?',
      a: 'Arcli excels with modern cloud warehouses (Snowflake, BigQuery) and RDBMS (Postgres, SQL Server). For legacy mainframes, we recommend querying the replicated operational data store (ODS) via our JDBC-compatible Integrations layer.',
      persona: 'CTO'
    }
  ]
};