// lib/seo/industry-verticals-1.tsx

import { SEOPageData } from './index';

/**
 * SEO Industry Campaign: Healthcare & Life Sciences
 * Target Audience: Chief Medical Information Officers (CMIO), Healthcare CISOs, Data Architects
 * Core Focus: HIPAA Compliance, PHI (Protected Health Information) Security, Zero-Data Movement, FHIR R4.
 */
export const healthcareIndustry: SEOPageData = {
  type: 'campaign',
  seo: {
    title: 'HIPAA Compliant AI Analytics | Zero Data Movement BI | Arcli',
    description: 'Deploy AI on top of your EHR and clinical data without moving PHI. Arcli’s read-only, VPC-native architecture generates secure SQL directly in your warehouse.',
    h1: 'HIPAA-Compliant AI Analytics for Healthcare Data',
    keywords: [
      'HIPAA compliant AI analytics', 
      'Healthcare BI zero data movement', 
      'VPC native AI BI tool',
      'query FHIR data with SQL AI',
      'AI for EHR analytics without ETL',
      'secure patient data analytics platform',
      'Epic Systems AI reporting',
      'Cerner zero copy analytics',
      'healthcare data lake text-to-sql',
      'CMIO healthcare dashboard AI',
      'FHIR R4 JSONB analytics',
      'zero data replication healthcare BI'
    ],
    intent: 'campaign',
    canonicalDomain: 'https://arcli.tech/industries/healthcare'
  },
  hero: {
    badge: 'HEALTHCARE & LIFE SCIENCES',
    title: 'Query EHR Data with AI. Keep PHI in Your VPC.',
    subtitle: 'Extract insights from your clinical databases instantly. Arcli generates dialect-perfect SQL, but your secure infrastructure executes it. Zero data replication. Zero compliance risk.',
    primaryCTA: { text: 'Schedule a Security Review', href: '/book-demo' },
    secondaryCTA: { text: 'View VPC Architecture', href: '/security' }
  },

  // STRICT BLOCK ARCHITECTURE (V13 Rule 4)
  blocks: [
    {
      type: 'ContrarianBanner',
      statement: "Copying patient records into a third-party BI cloud is a massive liability.",
      subtext: "Legacy analytics force you to build complex ETL pipelines, duplicating sensitive PHI across multiple environments. Arcli fundamentally rejects this. Keep your data in your secure infrastructure; let our AI come to you."
    },
    {
      type: 'InformationGain',
      uniqueInsight: "Standard text-to-SQL breaks on nested FHIR JSON blobs. Arcli's semantic execution layer is natively optimized to write deep Postgres JSONB and Snowflake array traversal functions without intermediate unnesting pipelines.",
      structuralAdvantage: "Reduces your compliance scope by 90% because Arcli only models metadata. Raw PHI never leaves your secure firewall."
    },
    {
      type: 'SecurityGuardrails',
      // Strict Array Requirement (V13 Rule 3)
      items: [
        {
          title: 'Architectural PHI Protection',
          description: 'Arcli only ingests schema metadata. Raw Protected Health Information never touches our servers. We generate the query; your warehouse handles the actual patient records.'
        },
        {
          title: 'Strict Read-Only Guarantee',
          description: 'We connect using heavily restricted, Read-Only service accounts. It is programmatically impossible for Arcli to mutate, update, or delete clinical data.'
        },
        {
          title: 'Cryptographic Query Auditing',
          description: 'Every interaction is logged via our Metric Governance layer. Compliance teams have full visibility into exactly what SQL was generated, who requested it, and when.'
        }
      ]
    },
    {
      type: 'ComparisonMatrix',
      // Strict Table Requirement (V13 Rule 3)
      rows: [
        { category: 'PHI Movement', arcliAdvantage: '0MB (Zero Replication)', legacy: 'High (ETL to BI Cloud)' },
        { category: 'Audit Logs', arcliAdvantage: 'End-to-end Cryptographic Hashing', legacy: 'Proprietary Blackbox' },
        { category: 'FHIR JSON Handling', arcliAdvantage: 'Native Dialect Compilation', legacy: 'Requires Unnesting Scripts' }
      ]
    },
    {
      type: 'UIBlock',
      payload: {
        type: 'AnalyticsDashboard',
        // Strict Data Mapping (V13 Rule 1 & 2)
        dataMapping: {
          title: 'Postgres JSONB FHIR R4 Analysis',
          description: 'Standard BI tools choke on nested FHIR JSON blobs. Arcli natively understands nested JSONB and writes the precise Postgres operators needed.',
          dialect: 'PostgreSQL (JSONB)',
          code: `-- Generated by Arcli Semantic Router & AI Orchestrator
WITH patient_metrics AS (
    SELECT 
        resource->>'id' AS patient_id,
        (resource->'extension'->0->>'valueDecimal')::numeric AS risk_score,
        jsonb_array_elements(resource->'address')->>'city' AS city
    FROM fhir_patients
    WHERE resource->>'resourceType' = 'Patient'
)
SELECT city, ROUND(AVG(risk_score), 2) AS avg_risk_score
FROM patient_metrics
GROUP BY city ORDER BY avg_risk_score DESC;`,
          businessOutcome: 'Empowers CMIOs to instantly extract patient risk scores deeply nested within FHIR JSON blobs without complex ETL.'
        }
      }
    },
    {
      type: 'UIBlock',
      payload: {
        type: 'ProgressiveChart',
        // Strict Nested Payload Requirement (V13 Rule 2)
        dataMapping: {
          title: 'Hospital Readmission Rate by Ward',
          visualizationType: 'bar-chart',
          codeSnippet: {
            filename: 'readmissions.sql',
            language: 'sql',
            code: 'SELECT ward, COUNT(readmission_id) FROM clinical_events WHERE readmission_date < 30 GROUP BY ward;'
          },
          governedOutputs: [
            { label: '30-Day Rate', value: '11.4%', status: 'warning' },
            { label: 'Avg Length of Stay', value: '4.2 Days', status: 'optimal' }
          ]
        }
      }
    }
  ],

  faqs: [
    {
      q: 'Will Arcli sign a Business Associate Agreement (BAA)?',
      a: 'Yes. For Enterprise tier customers operating in the United States, we provide standard BAAs to satisfy HIPAA and HITECH regulatory requirements.',
      persona: 'Compliance Officer'
    },
    {
      q: 'Can we self-host Arcli inside our own VPC?',
      a: 'Yes. For the strictest security postures, Arcli offers a Single-Tenant/VPC deployment model where both the Orchestrator and the UI run entirely within your firewalled environment.',
      persona: 'Data Architect'
    }
  ]
};

/**
 * SEO Industry Campaign: FinTech & Banking
 * Target Audience: CTOs, Chief Risk Officers (CRO), FinTech Data Leads
 * Core Focus: Ledger immutability, SOC2 Type II, RLS Passthrough, Zero-ETL.
 */
export const fintechIndustry: SEOPageData = {
  type: 'campaign',
  seo: {
    title: 'Financial Services AI Analytics | Zero-ETL BI Tool | Arcli',
    description: 'Query your core banking ledgers and payment gateways with natural language. Arcli guarantees zero data movement and immutable read-only security for FinTechs.',
    h1: 'Zero-ETL AI Analytics for Core Ledgers',
    keywords: [
      'Financial services AI analytics', 
      'Secure ledger BI tool', 
      'SOC2 compliant AI reporting', 
      'Zero-ETL banking analytics',
      'fintech row level security AI',
      'ledger reconciliation AI'
    ],
    intent: 'campaign',
    canonicalDomain: 'https://arcli.tech/industries/fintech'
  },
  hero: {
    badge: 'FINANCIAL SERVICES',
    title: 'Query Your Ledger. Keep It Secure.',
    subtitle: 'For modern FinTechs, moving transaction data is a non-starter. Arcli connects directly to your secure data warehouse, translating English into optimized SQL without ever extracting your customer’s financial data.',
    primaryCTA: { text: 'Start Free Trial', href: '/register' },
    secondaryCTA: { text: 'View SOC2 Report', href: '/security' }
  },

  blocks: [
    {
      type: 'ContrarianBanner',
      statement: "Your customer transaction data belongs in your vault, not a vendor's cache.",
      subtext: "If your BI tool requires a nightly sync of your core ledger, your attack surface just doubled. Arcli’s Zero-Data Movement architecture ensures that your financial data remains exactly where you put it—protected by your warehouse policies."
    },
    {
      type: 'InformationGain',
      uniqueInsight: "Arcli natively respects Row-Level Security (RLS) policies defined directly in Snowflake or Postgres. Our execution orchestrator uses Passthrough Authentication to ensure the AI can never query rows the end-user isn't explicitly permitted to see.",
      structuralAdvantage: "Decouples the compute/UI from the data storage layer completely. You retain 100% data sovereignty."
    },
    {
      type: 'ComparisonMatrix',
      // Strict Table Requirement (V13 Rule 3)
      rows: [
        { category: 'Data Exposure', arcliAdvantage: 'Zero (RLS Passthrough Native)', legacy: 'High (ETL Pipeline Duplication)' },
        { category: 'Compute Architecture', arcliAdvantage: 'Stateless Query Delegation', legacy: 'Stateful Proprietary Caching' },
        { category: 'Auditability', arcliAdvantage: 'Immutable Query Ledgers', legacy: 'Opaque Vendor Operations' }
      ]
    },
    {
      type: 'SecurityGuardrails',
      // Strict Array Requirement (V13 Rule 3)
      items: [
        {
          title: 'Inherited Row-Level Security (RLS)',
          description: 'Arcli natively respects the RLS policies defined in your Snowflake or Postgres databases. The AI can never surface a transaction a user isn\'t explicitly authorized to see.'
        },
        {
          title: 'Zero-ETL Architecture',
          description: 'Skip the vulnerable middle-man. Because Arcli writes the SQL directly against your live schema, there are no brittle dbt pipelines or stale data lakes.'
        },
        {
          title: 'Immutable Query Logging',
          description: 'Satisfy auditors instantly. Arcli maintains a tamper-proof cryptographic log of every single query the AI generates and executes.'
        }
      ]
    },
    {
      type: 'UIBlock',
      payload: {
        type: 'AnalyticsDashboard',
        // Strict Data Mapping (V13 Rule 1 & 2)
        dataMapping: {
          title: 'Snowflake Time-Travel & Windowing',
          description: 'Financial analysis requires precise window functions. Arcli’s engine generates advanced Snowflake dialect SQL to process millions of ledger rows flawlessly.',
          dialect: 'Snowflake SQL',
          code: `-- Generated by Arcli NL2SQL Generator
WITH daily_rollup AS (
    SELECT
        DATE_TRUNC('day', transaction_date) AS txn_day,
        merchant_category, SUM(amount) AS daily_volume
    FROM core_ledger.production.transactions
    WHERE status = 'SETTLED'
    GROUP BY txn_day, merchant_category
)
SELECT txn_day, merchant_category, daily_volume,
    SUM(daily_volume) OVER (
        PARTITION BY merchant_category ORDER BY txn_day ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ) AS rolling_7_day_volume
FROM daily_rollup ORDER BY txn_day DESC;`,
          businessOutcome: 'Provides the Head of Risk with a real-time, 7-day rolling average of transaction volumes to detect liquidity spikes natively on Snowflake compute.'
        }
      }
    }
  ],

  faqs: [
    {
      q: 'Is Arcli SOC 2 Type II compliant?',
      a: 'Yes. We undergo rigorous independent auditing to maintain our SOC 2 Type II certification, ensuring our security, availability, and confidentiality controls meet strict FinTech standards.',
      persona: 'Chief Risk Officer'
    },
    {
      q: 'How do you handle highly complex financial calculations like IRR or Yield?',
      a: 'Arcli grounds its AI not just in table names, but in semantic definitions via `SemanticMetricBuilder`. You define "Internal Rate of Return" once, and the AI will reliably insert the correct mathematical SQL logic every time.',
      persona: 'Data Engineer'
    }
  ]
};