// lib/seo/saas-integrations-1.tsx

import { SEOPageData } from './index';

/**
 * V13 ENFORCED: SaaS Integration Campaigns Part 1 (Salesforce & Shopify)
 * Completely refactored to eliminate local interfaces and enforce the strictly typed UI Block Protocol.
 */
export const saasIntegrationsPart1: Record<string, SEOPageData> = {
  'analyze-salesforce-data': {
    type: 'integration',
    seo: {
      title: 'Analyze Salesforce Data with AI | Zero-ETL CRM Analytics | Arcli',
      description: 'Connect Salesforce to Arcli. Bypass rigid native reports and use generative AI to track pipeline velocity, cross-object joins, and rep performance instantly.',
      h1: 'How to Analyze Salesforce Data (Without SOQL)',
      keywords: [
        'Analyze Salesforce Data', 
        'Zero-ETL CRM Analytics', 
        'Salesforce Pipeline Velocity', 
        'Salesforce Custom Objects AI',
        'Bypass SOQL'
      ],
      intent: 'integration',
      canonicalDomain: 'https://arcli.tech/integrations/salesforce'
    },
    hero: {
      badge: 'CRM Intelligence',
      title: 'How to Analyze Salesforce Data (Without SOQL)',
      subtitle: 'Stop wrestling with rigid Salesforce Report builders and custom object limitations. Ask complex questions about your pipeline in plain English to unlock instant architectural visibility.',
      icon: 'Cloud',
      primaryCTA: { text: 'Connect Salesforce Free', href: '/register' },
      secondaryCTA: { text: 'View Security Architecture', href: '/security' }
    },

    // STRICT BLOCK ARCHITECTURE (V13 Rule 4)
    blocks: [
      {
        type: 'ContrarianBanner',
        statement: 'Native Salesforce report builders force you to create custom report types just to join more than three objects.',
        subtext: 'Tracking historical snapshot data (e.g., "What was the pipeline value on Day 1 of the quarter?") is notoriously difficult natively. Arcli bypasses this entirely by extracting data into a columnar format and querying it with standard SQL.'
      },
      {
        type: 'InformationGain',
        uniqueInsight: 'Arcli\'s Semantic Router dynamically indexes your specific CRM schema, achieving native recognition of polymorphic fields, lookup relationships, and automated custom field (`__c`) detection.',
        structuralAdvantage: 'Embeds your unique Salesforce terminology (like specific custom deal stages) directly into the AI context window, preventing hallucinated metric definitions without requiring a rigid dbt layer.'
      },
      {
        type: 'UIBlock',
        payload: {
          type: 'ArchitectureDiagram',
          // Strict Data Mapping & Nested Array Requirement (V13 Rule 1 & 2)
          dataMapping: {
            title: 'The Zero-ETL Salesforce Pipeline',
            steps: [
              {
                title: '1. The Zero-ETL Sync',
                description: 'Authorize Arcli using enterprise-grade Salesforce OAuth 2.0. We strictly enforce read-only access and immediately normalize the payload.'
              },
              {
                title: '2. Automated Metadata Ingestion',
                description: 'Our Semantic Router automatically scans and indexes your complex CRM schema, understanding relationships between Standard and nested Custom Objects.'
              },
              {
                title: '3. Conversational Compute',
                description: 'By bypassing traditional SOQL limits and compiling queries directly against the in-memory columnar replica, operations execute in milliseconds.'
              }
            ]
          }
        }
      },
      {
        type: 'ComparisonMatrix',
        // Strict Table Requirement (V13 Rule 3)
        rows: [
          { category: 'Data Blending', arcliAdvantage: 'Unlimited automated semantic SQL joins', legacy: 'Restricted to predefined Custom Report Types' },
          { category: 'Historical Trending', arcliAdvantage: 'Native snapshot & time-travel querying', legacy: 'Requires expensive CRM Analytics add-ons' },
          { category: 'Time to Insight', arcliAdvantage: 'Seconds (Self-Serve AI)', legacy: 'Days (RevOps Ticket Backlog)' }
        ]
      },
      {
        type: 'UIBlock',
        payload: {
          type: 'AnalyticsDashboard',
          // Strict Data Mapping (V13 Rule 1 & 2)
          dataMapping: {
            title: 'Pipeline Velocity by Account Vertical',
            description: 'Measure the exact number of days it takes to close a deal, cross-referenced with account custom fields to identify bottlenecks.',
            dialect: 'PostgreSQL (DuckDB)',
            code: `-- Generated by Arcli Query Planner
WITH stage_duration AS (
  SELECT opportunity_id, AVG(DATE_PART('day', exit_time - enter_time)) AS days_in_legal 
  FROM sfdc_opportunity_history 
  WHERE stage_name = 'Legal Review' GROUP BY 1
)
SELECT 
  a.industry__c AS account_industry, 
  o.lead_source,
  sd.days_in_legal,
  AVG(DATE_PART('day', o.close_date::timestamp - o.created_date::timestamp)) AS avg_cycle_days 
FROM salesforce_opportunities o 
JOIN salesforce_accounts a ON o.account_id = a.id 
JOIN stage_duration sd ON o.id = sd.opportunity_id
WHERE o.is_won = TRUE AND o.type = 'Enterprise'
GROUP BY 1, 2 ORDER BY avg_cycle_days DESC;`,
            businessOutcome: 'Reveals that Enterprise deals sourced via Outbound face a 22-day bottleneck in Legal, enabling more accurate quarterly sales forecasting.'
          }
        }
      }
    ],

    faqs: [
      {
        q: 'Is our pipeline data used for public AI training?',
        a: 'No. Arcli adheres to a strict Zero-Mutation and Local-First Processing model. Your data is isolated per tenant and encrypted at rest. We NEVER use customer schema or row-level data to train foundational LLMs.',
        persona: 'CISO'
      },
      {
        q: 'What happens when we add new custom fields or alter our sales stages?',
        a: 'Arcli\'s Semantic Router detects schema drift dynamically. The next time you sync, the new metadata (`new_field__c`) is automatically embedded into the LLM\'s context window without manual mapping.',
        persona: 'RevOps'
      }
    ]
  },

  'analyze-shopify-data': {
    type: 'integration',
    seo: {
      title: 'Analyze Shopify E-Commerce Data with AI | Arcli Analytics',
      description: 'Turn massive Shopify store data into actionable insights. Evaluate how Arcli automatically unpacks nested JSON to calculate true margins, LTV, and inventory forecasting.',
      h1: 'How to Analyze Shopify Data (LTV, CAC, Net Profit)',
      keywords: [
        'Analyze Shopify Data', 
        'Shopify Net Margin Analytics', 
        'Shopify JSON Unnesting', 
        'E-commerce Cohort LTV',
        'Predictive Inventory Forecasting'
      ],
      intent: 'integration',
      canonicalDomain: 'https://arcli.tech/integrations/shopify'
    },
    hero: {
      badge: 'E-Commerce Intelligence',
      title: 'How to Analyze Shopify Data (LTV, CAC, Net Profit)',
      subtitle: 'Move beyond basic gross revenue dashboards. Let our engine unpack nested JSON payloads to calculate exact SKU profitability, cohort LTV, and inventory velocity.',
      icon: 'ShoppingCart',
      primaryCTA: { text: 'Connect Shopify Free', href: '/register' },
      secondaryCTA: { text: 'See E-Commerce Demo', href: '#interactive-demo' }
    },

    blocks: [
      {
        type: 'ContrarianBanner',
        statement: 'Native Shopify dashboards over-index on Gross Revenue, ignoring variable COGS and escalating return rates.',
        subtext: 'Calculating Lifetime Value (LTV) across specific customer cohorts usually requires messy Excel exports and VLOOKUPs. Arcli blends Shopify data with ad-spend directly, calculating blended CAC and Net Margin dynamically.'
      },
      {
        type: 'InformationGain',
        uniqueInsight: 'Arcli natively extracts and aggregates deeply nested JSON arrays (`line_items`, `tax_lines`, `discount_applications`) commonly found in modern E-commerce APIs.',
        structuralAdvantage: 'The execution engine is specifically trained on E-commerce relational models, accurately attributing proportional discounts and refunds down to the individual SKU level to calculate True Net Profit.'
      },
      {
        type: 'UIBlock',
        payload: {
          type: 'ArchitectureDiagram',
          dataMapping: {
            title: 'Shopify Data Extraction Pipeline',
            steps: [
              {
                title: '1. API Synchronization',
                description: 'Connect your Shopify store via our secure integration portal using strictly scoped read-only access.'
              },
              {
                title: '2. Automated Payload Normalization',
                description: 'Arcli automatically cleans and flattens complex JSON arrays (refunds, line items) into optimized columnar structures.'
              },
              {
                title: '3. Conversational Extraction',
                description: 'Data is instantly available for querying via plain English prompts, executing in sub-seconds.'
              }
            ]
          }
        }
      },
      {
        type: 'ComparisonMatrix',
        rows: [
          { category: 'Profitability Metrics', arcliAdvantage: 'Calculates True Net Profit & COGS instantly', legacy: 'Focuses primarily on Gross Revenue' },
          { category: 'Inventory Forecasting', arcliAdvantage: 'Real-time Predictive Velocity Analytics', legacy: 'Requires manual CSV exports' },
          { category: 'JSON Handling', arcliAdvantage: 'Native Array Unnesting', legacy: 'Requires complex dbt modeling' }
        ]
      },
      {
        type: 'UIBlock',
        payload: {
          type: 'AnalyticsDashboard',
          dataMapping: {
            title: 'Predictive Inventory Depletion',
            description: 'Combine historical sales velocity with current stock levels to forecast exact run-out dates per SKU.',
            dialect: 'PostgreSQL (Analytical)',
            code: `-- Generated by Arcli Query Planner
WITH trailing_velocity AS (
  SELECT sku, SUM(quantity) / 14.0 AS daily_sales_velocity 
  FROM shopify_order_line_items 
  WHERE created_at >= CURRENT_DATE - INTERVAL '14 days' 
  GROUP BY sku
) 
SELECT 
  i.sku, 
  i.inventory_quantity AS current_stock, 
  (i.inventory_quantity / NULLIF(tv.daily_sales_velocity, 0)) AS days_left 
FROM shopify_inventory_levels i 
JOIN trailing_velocity tv ON i.sku = tv.sku 
WHERE (i.inventory_quantity / NULLIF(tv.daily_sales_velocity, 0)) < 30
ORDER BY days_left ASC;`,
            businessOutcome: 'Prevents catastrophic stockouts during high-demand BFCM periods by enabling proactive reordering based on mathematical reality.'
          }
        }
      }
    ],

    faqs: [
      {
        q: 'How do you handle deeply nested JSON arrays for line items?',
        a: 'Our ingestion engine automatically flattens and normalizes `line_items`, `tax_lines`, and `refunds` into distinct, optimized columnar structures (Parquet), allowing for rapid vectorized querying via tools like UNNEST().',
        persona: 'Data Engineer'
      },
      {
        q: 'Can this show me true net profit after returns and discounts?',
        a: 'Yes. By mapping your COGS and unpacking the complex Shopify JSON payloads regarding refunds and discount allocations, Arcli provides exact net profitability, not just vanity gross sales.',
        persona: 'CEO'
      }
    ]
  }
};