// lib/seo/saas-integrations-2.tsx

import { SEOPageData } from './index';

/**
 * V13 ENFORCED: SaaS Integration Campaigns Part 2 (GA4 & HubSpot)
 * Completely refactored to eliminate local interfaces and enforce the strictly typed UI Block Protocol.
 */
export const saasIntegrationsPart2: Record<string, SEOPageData> = {
  'google-analytics-ai-dashboard': {
    type: 'integration',
    seo: {
      title: 'Google Analytics 4 AI Dashboard | Arcli Analytics',
      description: 'Learn how to analyze GA4 data without the UI. Connect BigQuery to Arcli and use generative AI to UNNEST events and track true attribution instantly.',
      h1: 'How to Analyze Google Analytics 4 (GA4) Data Without the UI',
      keywords: [
        'Analyze GA4 Data',
        'GA4 BigQuery Unnest',
        'Bypass GA4 Sampling',
        'Unsampled GA4 Analytics',
        'AI Google Analytics Dashboard'
      ],
      intent: 'integration',
      canonicalDomain: 'https://arcli.tech/integrations/google-analytics'
    },
    hero: {
      badge: 'Marketing Intelligence',
      title: 'Analyze Google Analytics 4 (GA4) Without the UI',
      subtitle: 'Query raw BigQuery events, custom funnels, and attribution using conversational AI instead of confusing GA4 reports. Get 100% accurate, unsampled traffic metrics in seconds.',
      icon: 'Search',
      primaryCTA: { text: 'Connect BigQuery Free', href: '/register' },
      secondaryCTA: { text: 'See Live Demo', href: '#interactive-demo' }
    },

    // STRICT BLOCK ARCHITECTURE (V13 Rule 4)
    blocks: [
      {
        type: 'ContrarianBanner',
        statement: 'The native GA4 UI hides your real data behind thresholding and aggressive sampling algorithms.',
        subtext: 'If you want mathematically accurate data, you must use the BigQuery export. But analyzing that raw data requires writing massive SQL queries to UNNEST complex event_params STRUCT arrays. Arcli bypasses this entirely by routing natural language intents directly to BigQuery.'
      },
      {
        type: 'InformationGain',
        uniqueInsight: 'Arcli natively understands the GA4 BigQuery schema design. It automatically authors the highly complex SQL required to UNNEST parameters while strictly enforcing `_TABLE_SUFFIX` partition filters to prevent costly full-table scans.',
        structuralAdvantage: 'Provides a mathematical guarantee of 100% unsampled data, allowing marketers to blend raw GA4 acquisition traffic directly with internal Stripe/CRM revenue for true ROAS.'
      },
      {
        type: 'UIBlock',
        payload: {
          type: 'ArchitectureDiagram',
          // Strict Data Mapping & Nested Array Requirement (V13 Rule 1 & 2)
          dataMapping: {
            title: 'The Zero-Copy GA4 Pipeline',
            steps: [
              {
                title: '1. BigQuery Synchronization',
                description: 'Authorize Arcli using secure Google Cloud Service Accounts to connect to your raw GA4 daily export.'
              },
              {
                title: '2. Intelligent Schema Parsing',
                description: 'Our Semantic Router automatically indexes GA4\'s daily partition tables and nested STRUCT parameters.'
              },
              {
                title: '3. Conversational Push-Down Compute',
                description: 'Arcli compiles plain English into optimized Google Standard SQL, executing in milliseconds on your compute.'
              }
            ]
          }
        }
      },
      {
        type: 'ComparisonMatrix',
        // Strict Table Requirement (V13 Rule 3)
        rows: [
          { category: 'Data Accuracy', arcliAdvantage: '100% Unsampled Raw Export', legacy: 'Heavily Sampled & Thresholded UI' },
          { category: 'Cross-Platform ROI', arcliAdvantage: 'Native (Join GA4 with Stripe/CRM)', legacy: 'Impossible (Walled Garden)' },
          { category: 'Query Cost', arcliAdvantage: 'Partition-Aware (Low Cost)', legacy: 'High (Prone to full-table scans)' }
        ]
      },
      {
        type: 'UIBlock',
        payload: {
          type: 'AnalyticsDashboard',
          // Strict Data Mapping (V13 Rule 1 & 2)
          dataMapping: {
            title: 'Cross-Platform ROAS Blending',
            description: 'Merge GA4 acquisition costs with internal CRM data to find true customer value, completely bypassing the GA4 interface.',
            dialect: 'Google BigQuery',
            code: `-- Generated by Arcli Semantic Router
SELECT 
  traffic_source.campaign, 
  COUNT(DISTINCT user_id) as total_users, 
  SUM(user_ltv.revenue) as true_ltv 
FROM \`analytics_123456789.events_*\`
WHERE _TABLE_SUFFIX BETWEEN '20230701' AND '20230930' 
  AND event_name = 'purchase'
GROUP BY 1 
ORDER BY true_ltv DESC;`,
            businessOutcome: 'Provides the executive team with a mathematically precise Return on Ad Spend (ROAS) metric without relying on Google\'s internal, sampled attribution algorithms.'
          }
        }
      }
    ],

    faqs: [
      {
        q: 'How does Arcli handle BigQuery costs and prevent full-table scans?',
        a: 'Our Contextual RAG routing ensures that every AI-generated query strictly enforces `_TABLE_SUFFIX` partition filters based on the date range requested. We prevent the AI from generating queries that scan your entire historical dataset.',
        persona: 'Data Engineer'
      },
      {
        q: 'Do I need to write the UNNEST SQL myself?',
        a: 'No. Arcli automatically detects nested `event_params` and `user_properties` arrays and writes the required `UNNEST()` functions directly into the executed query.',
        persona: 'Marketing Director'
      }
    ]
  },

  'analyze-hubspot-data': {
    type: 'integration',
    seo: {
      title: 'How to Analyze HubSpot Data (Deals, Contacts, Revenue) | Arcli',
      description: 'Learn how to analyze HubSpot data beyond the native UI. Connect to Arcli to calculate true pipeline velocity, multi-touch attribution, and custom properties via AI.',
      h1: 'How to Analyze HubSpot Data (Deals, Contacts, Revenue)',
      keywords: [
        'Analyze HubSpot Data',
        'HubSpot Pipeline Velocity',
        'Cross-Object HubSpot Reporting',
        'HubSpot Custom Objects AI',
        'RevOps AI Analytics'
      ],
      intent: 'integration',
      canonicalDomain: 'https://arcli.tech/integrations/hubspot'
    },
    hero: {
      badge: 'RevOps Intelligence',
      title: 'Analyze HubSpot Beyond the Native UI',
      subtitle: 'Stop exporting HubSpot lists to Excel. Connect your raw CRM data to Arcli and ask complex revenue, velocity, and pipeline questions in plain English.',
      icon: 'Megaphone',
      primaryCTA: { text: 'Connect HubSpot Free', href: '/register' },
      secondaryCTA: { text: 'Watch How It Works', href: '#interactive-demo' }
    },

    blocks: [
      {
        type: 'ContrarianBanner',
        statement: 'HubSpot\'s native reporting strictly limits users to 3-object joins (e.g., Contacts + Deals + Companies).',
        subtext: 'If you want to build complex multi-touch attribution models or deeply nested custom object reports, the native UI fails. Arcli extracts and vectorizes the data into a columnar engine, allowing infinite object joins and dynamic pipeline velocity math.'
      },
      {
        type: 'InformationGain',
        uniqueInsight: 'Arcli handles the hardest part of HubSpot data engineering: mapping complex association tables. The AI automatically understands how Deals link to Contacts via intersection tables, generating flawless cross-object SQL.',
        structuralAdvantage: 'Bypasses the need to build and maintain expensive dbt models just to report on HubSpot data. Custom properties are embedded into the semantic router instantly.'
      },
      {
        type: 'UIBlock',
        payload: {
          type: 'ArchitectureDiagram',
          dataMapping: {
            title: 'HubSpot Extraction Lifecycle',
            steps: [
              {
                title: '1. API Synchronization',
                description: 'Authorize Arcli using HubSpot OAuth 2.0 protocols for secure, strictly read-only access.'
              },
              {
                title: '2. Automated Property Normalization',
                description: 'Our Semantic Router automatically indexes every custom field and association table.'
              },
              {
                title: '3. Conversational Sub-Second Compute',
                description: 'Complex cross-object queries execute in milliseconds on our internal columnar engine.'
              }
            ]
          }
        }
      },
      {
        type: 'ComparisonMatrix',
        rows: [
          { category: 'Cross-Object Reporting', arcliAdvantage: 'Unlimited Object Joins', legacy: 'Strictly Limited to 3 Objects' },
          { category: 'Pipeline Velocity', arcliAdvantage: 'Native SQL Window Functions', legacy: 'Requires complex custom workflows' },
          { category: 'Custom Properties', arcliAdvantage: 'Auto-Indexed Instantly', legacy: 'Requires manual mapping' }
        ]
      },
      {
        type: 'UIBlock',
        payload: {
          type: 'AnalyticsDashboard',
          dataMapping: {
            title: 'Net Revenue Retention (NRR) via PLG Data Blending',
            description: 'Predict churn by joining HubSpot deal renewals with external product usage telemetry natively.',
            dialect: 'PostgreSQL (DuckDB)',
            code: `-- Generated by Arcli Query Planner
SELECT 
  d.dealstage, 
  AVG(DATE_PART('day', d.closedate::timestamp - d.createdate::timestamp)) as avg_velocity_days 
FROM hubspot_deals d
WHERE d.deal_type = 'Enterprise' 
  AND d.createdate >= CURRENT_DATE - INTERVAL '6 months'
GROUP BY 1 
ORDER BY avg_velocity_days DESC;`,
            businessOutcome: 'Reveals exact bottlenecks in the pipeline. Enterprise deals stuck in Legal Review for >5 days have a 60% lower win rate.'
          }
        }
      }
    ],

    faqs: [
      {
        q: 'Can Arcli handle our hundreds of custom HubSpot properties?',
        a: 'Yes. Upon connection, Arcli maps your entire metadata structure. Custom properties and unique Deal Stages are embedded into our semantic router instantly without manual tagging.',
        persona: 'RevOps'
      },
      {
        q: 'Will querying this data slow down our CRM?',
        a: 'No. Arcli extracts the data into an isolated columnar structure (Zero-ETL cache) for analytical processing, meaning your complex queries will never impact your operational HubSpot API limits.',
        persona: 'Data Engineer'
      }
    ]
  }
};