// lib/seo/sales-pipeline-velocity.tsx

import { SEOPageData } from './index';

export const salesPipelineVelocityData: SEOPageData = {
  type: 'integration',
  seo: {
    title: "AI Analytics for Salesforce & HubSpot | Pipeline Velocity | Arcli",
    description: "Stop wrestling with rigid Salesforce reports. Arcli's AI agents automatically join HubSpot lead data with Salesforce opportunities to calculate true pipeline velocity in real-time.",
    h1: "Calculate True Pipeline Velocity with AI",
    keywords: [
      "Salesforce AI analytics", 
      "HubSpot text to SQL", 
      "pipeline velocity calculation", 
      "RevOps AI data agent", 
      "sales performance BI", 
      "cross-platform CRM analytics",
      "Zero-ETL Salesforce reporting"
    ],
    intent: 'integration',
    canonicalDomain: 'https://arcli.tech/use-cases/sales-pipeline-velocity'
  },
  
  hero: {
    badge: "REVOPS & SALES INTELLIGENCE",
    title: "Conversational BI for Modern RevOps.",
    subtitle: "Salesforce reports are too rigid. Spreadsheets are too slow. Arcli deploys AI data agents that natively join Salesforce and HubSpot data, allowing RevOps to ask complex pipeline questions in plain English and get mathematically governed answers instantly."
  },

  blocks: [
    {
      type: 'ContrarianBanner',
      statement: "The RevOps backlog is dead. Let your Sales VPs interrogate the pipeline directly.",
      subtext: "RevOps teams spend 40% of their week building ad-hoc Salesforce dashboards for Sales Leaders. Arcli eliminates this bottleneck. By establishing a semantic layer over your CRM data, leaders get instant, mathematically accurate answers without filing a JIRA ticket."
    },
    {
      type: 'InformationGain',
      uniqueInsight: "Traditional BI forces you to extract SFDC and HubSpot data into a costly external data warehouse before joining it. Arcli uses embedded DuckDB to execute cross-platform joins in-memory, delivering instant velocity metrics without the zero-value ETL overhead.",
      structuralAdvantage: "A unified AI Semantic Router that natively understands recursive B2B Account hierarchies and automates cross-platform identity resolution."
    },
    {
      type: 'ROIHighlight',
      metrics: [
        { value: '40%', label: 'RevOps Time Saved' },
        { value: '0', label: 'ETL Pipelines Required' },
        { value: 'Instant', label: 'Cross-Platform Joins' },
        { value: '100%', label: 'Metric Governance' }
      ]
    },
    {
      type: 'ArchitectureDiagram',
      data: {
        title: "From Cluttered CRM to Governed AI Analytics",
        steps: [
          {
            title: "Incremental Bulk Ingestion",
            description: "The salesforce_connector utilizes the SFDC Bulk API v2 to incrementally sync standard objects (Accounts, Opportunities) and custom objects into a columnar Parquet format without hitting API rate limits."
          },
          {
            title: "Cross-Platform Entity Resolution",
            description: "Arcli automatically resolves the messy reality of B2B sales: merging HubSpot Contact IDs with Salesforce Lead IDs and mapping them to parent Account hierarchies."
          },
          {
            title: "Semantic RevOps Layer",
            description: "Define what 'Qualified Pipeline' actually means to your business in Arcli's governance layer. The AI agent strictly adheres to this definition, preventing hallucinated calculations."
          },
          {
            title: "Automated Slack Watchdogs",
            description: "Deploy an agent to monitor the semantic layer. If next quarter's pipeline generation drops below the historical 30-day moving average, it instantly alerts the VP of Sales in Slack."
          }
        ]
      }
    },
    {
      type: 'ComparisonMatrix',
      rows: [
        {
          category: "Cross-Platform JOINs",
          arcliAdvantage: "Native (Embedded DuckDB Engine)",
          legacy: "Requires Data Warehouse & dbt pipelines"
        },
        {
          category: "Custom Mathematical Metrics",
          arcliAdvantage: "Natural Language (Semantic Layer)",
          legacy: "Complex Summary Formulas or DAX expertise"
        },
        {
          category: "Historical Snapshotting",
          arcliAdvantage: "Automated instantly at ingestion",
          legacy: "Requires custom 'Reporting Snapshots' setup"
        },
        {
          category: "Executive Accessibility",
          arcliAdvantage: "Ask natively in Slack / Chat interface",
          legacy: "Dashboard hunting & filter fatigue"
        }
      ]
    },
    {
      type: 'AnalyticsDashboard',
      data: {
        title: "The Engine Room: Cross-Platform Pipeline Velocity",
        description: "To calculate true Pipeline Velocity, Arcli bridges the gap between Marketing (HubSpot) and Sales (Salesforce) dynamically.",
        dialect: "DuckDB SQL (Embedded Execution)",
        code: `-- Generated by Arcli AI Semantic Router
WITH hubspot_attribution AS (
    SELECT 
        hs_contact_id,
        email,
        recent_conversion_event_name AS campaign_source
    FROM tenant_workspace.hubspot.contacts
    WHERE createdate >= CURRENT_DATE - INTERVAL 180 DAY
),
salesforce_opps AS (
    SELECT 
        o.id AS opportunity_id,
        c.email AS primary_contact_email,
        o.amount,
        o.is_won,
        DATE_DIFF('day', o.created_date, o.close_date) AS days_to_close
    FROM tenant_workspace.salesforce.opportunities o
    LEFT JOIN tenant_workspace.salesforce.opportunity_contact_roles ocr ON o.id = ocr.opportunity_id
    LEFT JOIN tenant_workspace.salesforce.contacts c ON ocr.contact_id = c.id
    WHERE o.is_closed = TRUE AND o.created_date >= CURRENT_DATE - INTERVAL 180 DAY
),
unified_pipeline AS (
    SELECT 
        s.opportunity_id, s.amount, s.is_won, s.days_to_close,
        COALESCE(h.campaign_source, 'Outbound / Unattributed') AS lead_source
    FROM salesforce_opps s
    LEFT JOIN hubspot_attribution h ON LOWER(s.primary_contact_email) = LOWER(h.email)
)
SELECT 
    lead_source,
    COUNT(opportunity_id) AS total_opportunities,
    ROUND(SUM(CASE WHEN is_won THEN 1 ELSE 0 END) * 100.0 / COUNT(opportunity_id), 2) AS win_rate_pct,
    ROUND(AVG(CASE WHEN is_won THEN amount ELSE NULL END), 0) AS avg_deal_size_usd,
    ROUND(AVG(CASE WHEN is_won THEN days_to_close ELSE NULL END), 1) AS avg_sales_cycle_days,
    -- Pipeline Velocity ($/Day)
    CASE 
        WHEN AVG(CASE WHEN is_won THEN days_to_close ELSE NULL END) = 0 THEN 0
        ELSE ROUND((COUNT(opportunity_id) * (SUM(CASE WHEN is_won THEN 1 ELSE 0 END)::FLOAT / COUNT(opportunity_id)) * AVG(CASE WHEN is_won THEN amount ELSE NULL END)) / AVG(CASE WHEN is_won THEN days_to_close ELSE NULL END), 0)
    END AS pipeline_velocity_per_day
FROM unified_pipeline
GROUP BY 1 HAVING COUNT(opportunity_id) > 5
ORDER BY pipeline_velocity_per_day DESC;`,
        businessOutcome: "Allows Go-To-Market leaders to instantly pivot marketing spend toward the campaigns that generate the fastest revenue, bypassing the need for complex Data Warehouse ETL pipelines."
      }
    },
    {
      type: 'SecurityGuardrails',
      items: [
        {
          title: "Strictly Read-Only Execution",
          description: "Arcli extracts and analyzes your CRM data to provide insights without any risk of accidentally overwriting or mutating production Salesforce records."
        },
        {
          title: "API Quota Protection",
          description: "Our connector intelligently utilizes the Salesforce Bulk API v2 for initial loads and relies on the incremental streaming API for updates, ensuring minimal impact on your daily quotas."
        }
      ]
    },
    {
      type: 'CTAGroup',
      primaryCTA: {
        text: "Connect Your CRM",
        href: "/register?intent=revops"
      },
      secondaryCTA: {
        text: "View Velocity Architecture",
        href: "#strategic-query"
      }
    }
  ],

  faqs: [
    {
      q: "Does Arcli support Salesforce Custom Objects?",
      a: "Yes. During the connection flow, Arcli dynamically profiles your Salesforce schema, automatically mapping any standard or custom objects (and custom fields with `__c`) into your queryable semantic layer.",
      persona: "RevOps Manager"
    },
    {
      q: "How does Arcli handle complex Account hierarchies?",
      a: "Our Semantic Router understands recursive parent-child relationships natively. If you ask for 'Global Revenue for Microsoft', the agent will automatically traverse the `ParentId` tree to sum opportunities across all regional subsidiary accounts.",
      persona: "VP of Sales"
    }
  ]
};