// lib/seo/shopify-campaign.tsx

import { SEOPageData } from './index';

/**
 * 🚀 V14 SEO UPGRADE: Shopify Campaigns
 * Architecture: Strict UI Block Protocol + Semantic Density
 * Optimized for: 8-Figure Operator Intent, Conversion, SERP Realism, E-E-A-T.
 * ZERO runtime crashes. Next.js Static Build Safe.
 */

// ----------------------------------------------------------------------
// 1. INVENTORY FORECASTING
// ----------------------------------------------------------------------
export const shopifyInventoryForecasting: SEOPageData = {
  type: 'campaign',
  seo: {
    title: 'Shopify Inventory Forecasting & Restock Alerts AI | Arcli',
    description: 'Stop losing revenue to stockouts. Arcli analyzes your Shopify sales velocity, excludes out-of-stock days, and calculates predictive inventory forecasts.',
    h1: 'Algorithmic Shopify Inventory Forecasting',
    keywords: ['shopify inventory forecasting', 'shopify restock alerts', 'predictive inventory ai', 'ecommerce run-rate calculator'],
    intent: 'campaign',
    canonicalDomain: 'https://arcli.tech/campaigns/shopify-inventory-forecasting'
  },
  
  hero: {
    badge: 'SUPPLY CHAIN INTELLIGENCE',
    title: 'Never Run Out of Your Best Sellers Again.',
    subtitle: 'Arcli monitors your Shopify sales velocity in real-time. Get predictive forecasting that mathematically accounts for seasonality and supplier lead times before you lose a single dollar.'
  },

  blocks: [
    {
      type: 'ContrarianBanner',
      statement: 'Stockouts aren’t a supply chain problem. They are a data latency problem.',
      subtext: 'Relying on trailing 30-day averages in a spreadsheet guarantees you will over-order during a slump or stock out during a spike. Furthermore, naive calculators don\'t exclude the days you were out of stock, artificially deflating your actual velocity.'
    },
    {
      type: 'InformationGain',
      uniqueInsight: 'Standard inventory calculators artificially lower your run-rate if you had zero sales due to a stockout. Arcli uses dynamic window functions to explicitly exclude zero-inventory days from the velocity calculation.',
      structuralAdvantage: 'A deterministic forecasting engine that calculates Lead-Time Aware PO Alerts, triggering exactly when your projected stock reaches the safety buffer threshold.'
    },
    {
      type: 'ROIHighlight',
      metrics: [
        { value: '$0', label: 'Lost Revenue to Stockouts' },
        { value: '100%', label: 'Velocity Accuracy' },
        { value: 'Automated', label: 'Purchase Order Alerts' }
      ]
    },
    {
      type: 'ArchitectureDiagram',
      data: {
        title: 'Predictive Inventory Intelligence Pipeline',
        steps: [
          {
            title: 'Dynamic Run-Rate Calculation',
            description: 'Arcli ingests daily order volume and adjusts sales velocity based on recent micro-trends, ignoring stockout days.'
          },
          {
            title: 'Lead-Time Modeling',
            description: 'Input supplier lead times and safety buffer days at the SKU or vendor level.'
          },
          {
            title: 'Automated PO Triggers',
            description: 'Calculates the exact date to place a Purchase Order so inventory arrives precisely as current stock depletes.'
          },
          {
            title: 'Opportunity Cost Analysis',
            description: 'Visualizes exact Gross Profit bleeding per day on out-of-stock SKUs to justify expedited air freight.'
          }
        ]
      }
    },
    {
      type: 'ComparisonMatrix',
      rows: [
        {
          category: 'Velocity Calculation',
          arcliAdvantage: 'Excludes out-of-stock days dynamically',
          legacy: 'Simple 30-day trailing average'
        },
        {
          category: 'Data Latency',
          arcliAdvantage: 'Real-time via Shopify Webhooks',
          legacy: 'Manual CSV Export & Excel updates'
        },
        {
          category: 'Lead Time Logic',
          arcliAdvantage: 'SKU and Vendor-specific offsets',
          legacy: 'One-size-fits-all generic buffer'
        }
      ]
    },
    {
      type: 'AnalyticsDashboard',
      data: {
        title: 'The Engine Room: Out-Of-Stock Excluded Velocity',
        description: 'How Arcli calculates true daily sales velocity by filtering out days where inventory was zero.',
        dialect: 'DuckDB SQL (Embedded Execution)',
        code: `-- Generated by Arcli AI Semantic Router
WITH daily_sales AS (
    SELECT 
        sku,
        DATE_TRUNC('day', created_at) AS sale_date,
        SUM(quantity) as units_sold
    FROM tenant_workspace.shopify.order_lines
    GROUP BY 1, 2
),
daily_inventory AS (
    SELECT 
        sku,
        date,
        ending_inventory
    FROM tenant_workspace.shopify.inventory_snapshots
    WHERE ending_inventory > 0 -- The Arcli Secret: Exclude stockout days
),
true_velocity AS (
    SELECT 
        s.sku,
        AVG(s.units_sold) OVER (
            PARTITION BY s.sku 
            ORDER BY s.sale_date 
            ROWS BETWEEN 30 PRECEDING AND CURRENT ROW
        ) AS true_daily_velocity
    FROM daily_sales s
    JOIN daily_inventory i ON s.sku = i.sku AND s.sale_date = i.date
)
SELECT 
    sku,
    ROUND(MAX(true_daily_velocity), 2) AS adjusted_velocity_per_day
FROM true_velocity
GROUP BY 1
ORDER BY adjusted_velocity_per_day DESC;`,
        businessOutcome: 'Ensures purchase orders are based on actual customer demand, preventing costly under-ordering caused by skewed data.'
      }
    },
    {
      type: 'CTAGroup',
      primaryCTA: { text: 'Connect Shopify', href: '/register?intent=forecasting' },
      secondaryCTA: { text: 'See the Math', href: '#architecture' }
    }
  ],

  faqs: [
    {
      q: 'Does Arcli account for days when an item was out of stock?',
      a: 'Yes. Standard calculators artificially lower your run-rate if you had zero sales due to a stockout. Arcli automatically excludes zero-inventory days from the velocity calculation.',
      persona: 'Supply Chain Manager'
    },
    {
      q: 'Can I set different lead times per supplier?',
      a: 'Yes, lead times and buffer days can be modeled at the individual vendor, category, or individual SKU level in the data transformation layer.',
      persona: 'Operations Director'
    },
    {
      q: 'Does it factor in bundles?',
      a: 'Yes, Arcli unpacks Shopify bundles to forecast component-level inventory velocity.',
      persona: 'Ecommerce Manager'
    }
  ]
};

// ----------------------------------------------------------------------
// 2. INCREASE AOV (PRODUCT BUNDLING)
// ----------------------------------------------------------------------
export const shopifyAovBundling: SEOPageData = {
  type: 'campaign',
  seo: {
    title: 'Increase Shopify AOV with Market Basket Analysis | Arcli',
    description: 'Use the Apriori algorithm to discover exactly which products your customers buy together. Increase your Shopify AOV profitably.',
    h1: 'Increase Shopify AOV Without Spending More on Ads.',
    keywords: ['increase shopify aov', 'shopify product bundling ai', 'market basket analysis ecommerce', 'apriori algorithm shopify'],
    intent: 'campaign',
    canonicalDomain: 'https://arcli.tech/campaigns/increase-shopify-aov'
  },
  
  hero: {
    badge: 'REVENUE OPTIMIZATION',
    title: 'Increase Shopify AOV Without Spending More on Ads.',
    subtitle: 'Arcli analyzes millions of order combinations using Market Basket Analysis to reveal the exact product bundles that will mathematically increase your Average Order Value (AOV).'
  },

  blocks: [
    {
      type: 'ContrarianBanner',
      statement: 'The Math Behind Scaling Profitably in a High-CAC World.',
      subtext: 'When CAC rises across Meta and Google, the only mathematical escape velocity is raising your AOV. But arbitrary bundles destroy margins. You need deterministic affinity analysis to pair high-margin accessories with high-volume hero SKUs.'
    },
    {
      type: 'InformationGain',
      uniqueInsight: 'Most merchants guess bundle pairs based on intuition, leading to margin cannibalization. Arcli applies the Apriori algorithm to calculate exact Confidence and Lift metrics, proving statistically which items drive incremental revenue.',
      structuralAdvantage: 'Real-time Affinity Scoring that automatically flags bundles that increase top-line AOV but degrade Contribution Margin.'
    },
    {
      type: 'ArchitectureDiagram',
      data: {
        title: 'Algorithmic Bundle Generation',
        steps: [
          {
            title: 'Order Flattening',
            description: 'Transforms deeply nested JSON order line items into a flat, analyzable transactional format.'
          },
          {
            title: 'Affinity Scoring (Apriori)',
            description: 'Measures the exact statistical correlation between any two SKUs in your catalog.'
          },
          {
            title: 'Margin Protection',
            description: 'Calculates the net-profit of the combined bundle to ensure COGS don\'t outpace the AOV gain.'
          }
        ]
      }
    },
    {
      type: 'ComparisonMatrix',
      rows: [
        {
          category: 'Methodology',
          arcliAdvantage: 'Apriori Algorithm (Market Basket Analysis)',
          legacy: 'Guessing / Intuition'
        },
        {
          category: 'Data Processing',
          arcliAdvantage: 'Real-time via Embedded DuckDB',
          legacy: 'Manual CSV Exports & VLOOKUPs'
        },
        {
          category: 'Scale',
          arcliAdvantage: 'Analyzes 10,000+ SKU combinations instantly',
          legacy: 'Top 5 products only'
        },
        {
          category: 'Margin Awareness',
          arcliAdvantage: 'Calculates net-profit of the bundle',
          legacy: 'Blind to COGS'
        }
      ]
    },
    {
      type: 'AnalyticsDashboard',
      data: {
        title: 'The Engine Room: Market Basket Cross-Join',
        description: 'How Arcli mathematically identifies product affinities using a SQL-based Apriori approximation.',
        dialect: 'DuckDB SQL',
        code: `-- Generated by Arcli AI Semantic Router
WITH order_items AS (
    SELECT order_id, sku
    FROM tenant_workspace.shopify.order_lines
),
bundle_combinations AS (
    SELECT 
        a.sku AS product_a,
        b.sku AS product_b,
        COUNT(DISTINCT a.order_id) AS times_bought_together
    FROM order_items a
    JOIN order_items b ON a.order_id = b.order_id AND a.sku < b.sku
    GROUP BY 1, 2
)
SELECT 
    product_a,
    product_b,
    times_bought_together,
    -- Simple Confidence Score Proxy
    ROUND((times_bought_together * 100.0) / 
          (SELECT COUNT(DISTINCT order_id) FROM order_items), 2) AS affinity_lift_pct
FROM bundle_combinations
WHERE times_bought_together > 50
ORDER BY times_bought_together DESC
LIMIT 10;`,
        businessOutcome: 'Takes the guesswork out of merchandising, allowing you to deploy cross-sells and upsells that are mathematically proven to convert.'
      }
    },
    {
      type: 'CTAGroup',
      primaryCTA: { text: 'Analyze AOV Math', href: '/register?intent=aov' },
      secondaryCTA: { text: 'View Bundling Logic', href: '#architecture' }
    }
  ],

  faqs: [
    {
      q: 'How much order history is required for accurate bundles?',
      a: 'We recommend at least 1,000 historical orders to achieve statistical significance and eliminate anomaly noise in the affinity analysis.',
      persona: 'Data Analyst'
    },
    {
      q: 'Does this physically create the bundles in Shopify?',
      a: 'Arcli acts as the Intelligence Layer. We provide the exact SKUs to group and the projected revenue impact; you implement them using Shopify Native Bundles or a 3rd-party app.',
      persona: 'Ecommerce Manager'
    }
  ]
};

// ----------------------------------------------------------------------
// 3. CUSTOMER SEGMENTATION
// ----------------------------------------------------------------------
export const shopifyCustomerSegmentation: SEOPageData = {
  type: 'campaign',
  seo: {
    title: 'Advanced Shopify Customer Segmentation & RFM | Arcli',
    description: 'Identify your VIPs, At-Risk buyers, and one-hit wonders. Arcli provides automated RFM customer segmentation for Shopify stores.',
    h1: 'Know Exactly Who Your Most Profitable Buyers Are.',
    keywords: ['shopify customer segmentation', 'rfm analysis shopify', 'ecommerce audience targeting', 'shopify customer lifetime value'],
    intent: 'campaign',
    canonicalDomain: 'https://arcli.tech/campaigns/shopify-customer-segmentation'
  },

  hero: {
    badge: 'AUDIENCE INTELLIGENCE',
    title: 'Know Exactly Who Your Most Profitable Buyers Are.',
    subtitle: 'Stop treating all your customers the same. Arcli automatically segments your Shopify buyers by Recency, Frequency, and Monetary (RFM) value.'
  },

  blocks: [
    {
      type: 'ContrarianBanner',
      statement: 'Stop Mass-Discounting. Start Segmenting.',
      subtext: 'Sending a 20% off email to your entire list destroys margin. Your VIP "Whales" are price-insensitive and would have bought anyway. Your segment data needs to protect margin, not just drive vanity revenue.'
    },
    {
      type: 'InformationGain',
      uniqueInsight: 'Basic platforms group customers by total spend, ignoring temporal churn signals. Arcli utilizes an RFM (Recency, Frequency, Monetary) matrix to identify highly profitable customers the moment they show signs of lapsing.',
      structuralAdvantage: 'Conversational Data Segmentation that compiles natural language into precise cohort targeting queries.'
    },
    {
      type: 'ArchitectureDiagram',
      data: {
        title: 'RFM Segmentation Workflows',
        steps: [
          { title: 'The VIP "Whales"', description: 'Identify the top 5% driving 40% of revenue. Exclude them from generic discount ladders to protect margins.' },
          { title: 'The "At-Risk" Churners', description: 'Spot users who bought monthly but haven\'t purchased in 60 days. Hit them with aggressive win-back flows.' },
          { title: 'The One-Hit Wonders', description: 'Isolate buyers who purchased heavily discounted items during Black Friday and never returned.' }
        ]
      }
    },
    {
      type: 'ComparisonMatrix',
      rows: [
        { category: 'Segmentation Logic', arcliAdvantage: 'Multidimensional RFM Scoring', legacy: 'Single-metric "Total Spent" filters' },
        { category: 'Query Interface', arcliAdvantage: 'Natural Language (Semantic AI)', legacy: 'Clunky UI drop-downs & AND/OR logic' },
        { category: 'Actionability', arcliAdvantage: 'Real-time Sync to Klaviyo/Ads', legacy: 'Static CSV audience exports' }
      ]
    },
    {
      type: 'AnalyticsDashboard',
      data: {
        title: 'The Engine Room: RFM Customer Scoring',
        description: 'How Arcli scores every customer in your database based on behavioral transaction data.',
        dialect: 'DuckDB SQL',
        code: `-- Generated by Arcli AI Semantic Router
WITH customer_stats AS (
    SELECT 
        customer_id,
        email,
        MAX(created_at) AS last_order_date,
        COUNT(id) AS frequency,
        SUM(total_price) AS monetary_value
    FROM tenant_workspace.shopify.orders
    WHERE financial_status = 'paid'
    GROUP BY 1, 2
)
SELECT 
    email,
    frequency,
    monetary_value,
    DATE_DIFF('day', last_order_date, CURRENT_DATE) AS recency_days,
    CASE 
        WHEN DATE_DIFF('day', last_order_date, CURRENT_DATE) > 90 AND frequency > 3 THEN 'At-Risk VIP'
        WHEN monetary_value > 1000 THEN 'Whale'
        WHEN frequency = 1 THEN 'One-Hit Wonder'
        ELSE 'Standard'
    END AS rfm_segment
FROM customer_stats
ORDER BY monetary_value DESC;`,
        businessOutcome: 'Eliminates wasted ad spend by allowing you to suppress recent buyers and aggressively bid on high-LTV lookalike seeds.'
      }
    },
    {
      type: 'CTAGroup',
      primaryCTA: { text: 'Segment Customers', href: '/register?intent=segmentation' },
      secondaryCTA: { text: 'View RFM Architecture', href: '#architecture' }
    }
  ],
  faqs: [
    {
      q: 'Can I export these segments to Klaviyo or Meta Ads?',
      a: 'Yes, Arcli provides direct integration points to sync your mathematically derived RFM segments directly into your email and ad platforms.',
      persona: 'Performance Marketer'
    }
  ]
};

// ----------------------------------------------------------------------
// 4. COHORT ANALYSIS
// ----------------------------------------------------------------------
export const shopifyCohortAnalysis: SEOPageData = {
  type: 'campaign',
  seo: {
    title: 'Automated Shopify Cohort Analysis & Retention | Arcli',
    description: 'Understand customer retention and lifetime value with automated Shopify cohort tracking. Ditch Excel and let AI build your layer-cake charts.',
    h1: 'Track Customer Retention Like a Data Scientist.',
    keywords: ['shopify cohort analysis', 'shopify retention tracking', 'ecommerce layer cake chart', 'LTV to CAC ratio shopify'],
    intent: 'campaign',
    canonicalDomain: 'https://arcli.tech/campaigns/shopify-cohort-analysis'
  },

  hero: {
    badge: 'RETENTION ANALYTICS',
    title: 'Track Customer Retention Like a Data Scientist.',
    subtitle: 'Arcli automatically generates pristine triangular cohort analyses and layer-cake charts from your raw Shopify data in milliseconds.'
  },

  blocks: [
    {
      type: 'ContrarianBanner',
      statement: 'Excel pivot tables are killing your growth velocity.',
      subtext: 'Manually joining acquisition dates to subsequent order dates in spreadsheets is prone to error, breaks at scale, and takes hours. Arcli compiles your retention matrix instantly using advanced SQL window functions.'
    },
    {
      type: 'InformationGain',
      uniqueInsight: 'Most dashboards show blended retention, hiding the fact that specific monthly cohorts (like Black Friday buyers) have radically different payback periods. Arcli isolates cohorts to reveal true time-to-breakeven.',
      structuralAdvantage: 'Automated triangular matrix generation allowing toggles between Percentage Retention and Cumulative Net Margin.'
    },
    {
      type: 'ArchitectureDiagram',
      data: {
        title: 'Deep Retention Analytics',
        steps: [
          { title: 'Month-Over-Month Tracking', description: 'See exactly what percentage of users acquired in January came back to purchase in February, March, and beyond.' },
          { title: 'Subscription vs. One-Off', description: 'Filter cohorts to compare the lifetime retention of active subscribers against one-time purchasers.' },
          { title: 'Margin Cohorts', description: 'Toggle from percentage-based retention to absolute cumulative gross margin to see when a cohort breaks even on CAC.' }
        ]
      }
    },
    {
      type: 'ComparisonMatrix',
      rows: [
        { category: 'Matrix Generation', arcliAdvantage: 'Instant & Automated', legacy: 'Manual Pivot Tables' },
        { category: 'Financial Accuracy', arcliAdvantage: 'Factors in Refunds & COGS', legacy: 'Gross Revenue only' },
        { category: 'Time Granularity', arcliAdvantage: 'Daily, Weekly, Monthly', legacy: 'Locked to Monthly' }
      ]
    },
    {
      type: 'AnalyticsDashboard',
      data: {
        title: 'The Engine Room: Cohort Generation',
        description: 'How Arcli identifies the acquisition month and maps all subsequent revenue to that cohort.',
        dialect: 'PostgreSQL / DuckDB',
        code: `-- Generated by Arcli AI Semantic Router
WITH first_orders AS (
    SELECT customer_id, DATE_TRUNC('month', MIN(created_at)) AS cohort_month
    FROM tenant_workspace.shopify.orders
    GROUP BY 1
),
subsequent_orders AS (
    SELECT 
        o.customer_id,
        f.cohort_month,
        DATE_TRUNC('month', o.created_at) AS order_month,
        o.total_price
    FROM tenant_workspace.shopify.orders o
    JOIN first_orders f ON o.customer_id = f.customer_id
)
SELECT 
    cohort_month,
    DATE_DIFF('month', cohort_month, order_month) AS months_since_acquisition,
    COUNT(DISTINCT customer_id) AS active_customers,
    SUM(total_price) AS cohort_revenue
FROM subsequent_orders
GROUP BY 1, 2
ORDER BY 1 DESC, 2 ASC;`,
        businessOutcome: 'Provides undeniable proof of your LTV curve, allowing you to confidently scale top-of-funnel ad spend knowing exactly when it will pay back.'
      }
    },
    {
      type: 'CTAGroup',
      primaryCTA: { text: 'View Your Cohorts', href: '/register?intent=cohorts' },
      secondaryCTA: { text: 'Explore Platform', href: '/platform' }
    }
  ],
  faqs: [
    {
      q: 'Does it account for refunds in the cohort revenue?',
      a: 'Yes, net-revenue cohorts automatically subtract refunds, returns, and chargebacks to show true realized lifetime value.',
      persona: 'CFO / Finance'
    },
    {
      q: 'Can I view weekly or daily cohorts?',
      a: 'Yes. While monthly is standard for long-term LTV, you can dynamically adjust the grouping to weekly cohorts for high-velocity periods like BFCM.',
      persona: 'Media Buyer'
    }
  ]
};

// ----------------------------------------------------------------------
// 5. PROFIT MARGIN TRACKER
// ----------------------------------------------------------------------
export const shopifyProfitMarginTracker: SEOPageData = {
  type: 'campaign',
  seo: {
    title: 'Real-Time Shopify Profit Margin Tracker (CM2) | Arcli',
    description: 'Factor in COGS, shipping, discounts, and ad spend to get real-time Shopify profit margin (CM2) tracking at the SKU level.',
    h1: 'Know Your Exact Profit. Down to the Penny.',
    keywords: ['shopify profit margin tracker', 'true net profit ecommerce', 'shopify cogs calculator', 'CM2 tracking shopify'],
    intent: 'campaign',
    canonicalDomain: 'https://arcli.tech/campaigns/shopify-profit-margin-tracker'
  },

  hero: {
    badge: 'UNIT ECONOMICS',
    title: 'Know Your Exact Profit. Down to the Penny.',
    subtitle: 'Top-line revenue is a vanity metric. Arcli ingests your COGS, shipping, discounts, and blended ad spend to show your true Contribution Margin (CM2).'
  },

  blocks: [
    {
      type: 'ContrarianBanner',
      statement: 'The End of "Blind Scaling"',
      subtext: 'Scaling ad spend without real-time visibility into unit economics is how 8-figure ecommerce brands go bankrupt while hitting record revenue. You must track Contribution Margin 2 (CM2) daily.'
    },
    {
      type: 'InformationGain',
      uniqueInsight: 'Relying on Shopify’s native profit reports ignores external ad spend and complex return deductions. Arcli acts as a unified ledger, blending Shopify transactional data with Meta/Google spend dynamically.',
      structuralAdvantage: 'Real-time Semantic Metric Governance ensuring "Net Profit" always adheres to your strict financial formula.'
    },
    {
      type: 'ROIHighlight',
      metrics: [
        { value: '100%', label: 'COGS Accountability' },
        { value: 'Real-Time', label: 'CM2 Calculation' },
        { value: 'Zero', label: 'Manual Spreadsheets' }
      ]
    },
    {
      type: 'ArchitectureDiagram',
      data: {
        title: 'CM2 Data Pipeline',
        steps: [
          { title: 'COGS Integration', description: 'Sync cost of goods directly from Shopify inventory or map them via external CSVs.' },
          { title: 'Blended Spend', description: 'Automatically subtract Meta, Google, and TikTok ad spend from your gross margin to reveal true net.' },
          { title: 'Discount Auditing', description: 'See exactly how much margin is destroyed by stackable discount codes and influencer promos.' }
        ]
      }
    },
    {
      type: 'ComparisonMatrix',
      rows: [
        { category: 'Metric Tracked', arcliAdvantage: 'Contribution Margin 2 (CM2)', legacy: 'Gross Revenue' },
        { category: 'Ad Spend Integration', arcliAdvantage: 'Native API Joins', legacy: 'Manual Entry' },
        { category: 'Refund Handling', arcliAdvantage: 'Automated Deduction', legacy: 'Often Ignored' }
      ]
    },
    {
      type: 'AnalyticsDashboard',
      data: {
        title: 'The Engine Room: True Margin Calculation',
        description: 'How Arcli structurally subtracts all operational costs to find the real profit floor.',
        dialect: 'DuckDB SQL',
        code: `-- Generated by Arcli Semantic DAG
SELECT 
    o.order_id,
    o.total_price AS gross_revenue,
    COALESCE(c.cogs, 0) AS total_cogs,
    o.total_discounts AS discounts,
    -- Subtracting Costs for CM1
    (o.total_price - COALESCE(c.cogs, 0) - o.total_discounts) AS cm1,
    -- Subtracting Blended Ad Spend (CAC) for CM2
    ((o.total_price - COALESCE(c.cogs, 0) - o.total_discounts) - a.blended_cac) AS cm2_net_profit
FROM tenant_workspace.shopify.orders o
LEFT JOIN tenant_workspace.finance.daily_cogs c ON o.id = c.order_id
LEFT JOIN tenant_workspace.marketing.daily_cac a ON DATE_TRUNC('day', o.created_at) = a.date
WHERE o.financial_status = 'paid';`,
        businessOutcome: 'Prevents the fatal error of scaling top-of-funnel campaigns that are secretly draining corporate cash reserves.'
      }
    },
    {
      type: 'CTAGroup',
      primaryCTA: { text: 'Track True Profit', href: '/register?intent=profit' },
      secondaryCTA: { text: 'Explore Architecture', href: '#architecture' }
    }
  ],
  faqs: [
    {
      q: 'How does Arcli handle historical COGS changes?',
      a: 'If your supplier raises prices, Arcli supports historically mapping COGS effective dates, so your past profit margins remain accurate and aren\'t overwritten.',
      persona: 'Accountant'
    }
  ]
};

// ----------------------------------------------------------------------
// 6. CUSTOM REPORTS
// ----------------------------------------------------------------------
export const shopifyCustomReports: SEOPageData = {
  type: 'campaign',
  seo: {
    title: 'AI Custom Report Builder for Shopify | Arcli',
    description: 'Ditch the CSV exports. Use Arcli\'s natural language AI to build boardroom-ready custom Shopify reports in seconds via Text-to-SQL.',
    h1: 'Build Complex Shopify Reports in Seconds.',
    keywords: ['shopify custom reports', 'ai report builder shopify', 'custom data tables ecommerce', 'text to sql shopify'],
    intent: 'campaign',
    canonicalDomain: 'https://arcli.tech/campaigns/shopify-custom-reports'
  },

  hero: {
    badge: 'AI REPORTING',
    title: 'Build Complex Shopify Reports in Seconds.',
    subtitle: 'Need a highly specific breakdown of sales by region, discount code, and UTM parameter? Just ask Arcli. We generate custom, boardroom-ready reports instantly.'
  },

  blocks: [
    {
      type: 'ContrarianBanner',
      statement: 'The Death of the CSV Export',
      subtext: 'Exporting "Orders.csv", opening it in Excel, cleaning the data, and running VLOOKUPs is a workflow from 2015. It is static the moment you download it. Arcli translates your English questions into perfectly executed database queries on your live Shopify schema.'
    },
    {
      type: 'InformationGain',
      uniqueInsight: 'Rigid BI dashboards force you to anticipate every question in advance. Arcli uses an LLM-powered Semantic Router that writes deterministic SQL on the fly, answering ad-hoc questions instantly without requiring a data engineering ticket.',
      structuralAdvantage: 'Text-to-SQL engine strictly governed by a YAML-defined semantic layer to prevent AI hallucinations.'
    },
    {
      type: 'ArchitectureDiagram',
      data: {
        title: 'From Question to Data Table Instantly',
        steps: [
          { title: 'Geographic Analysis', description: 'Create a report of all orders over $100 in California that used the code SUMMER20, grouped by city.' },
          { title: 'Fulfillment Auditing', description: 'Show me all unfulfilled orders older than 5 days, grouped by shipping country.' },
          { title: 'Discount Auditing', description: 'Break down last month’s revenue by specific discount codes used, including the total COGS.' }
        ]
      }
    },
    {
      type: 'ComparisonMatrix',
      rows: [
        { category: 'Report Creation Time', arcliAdvantage: 'Seconds (Natural Language)', legacy: 'Hours/Days (JIRA Tickets)' },
        { category: 'Data Freshness', arcliAdvantage: 'Real-Time Direct Query', legacy: 'Static CSV Downloads' },
        { category: 'Customization', arcliAdvantage: 'Infinite ad-hoc cuts', legacy: 'Locked to pre-built filters' }
      ]
    },
    {
      type: 'AnalyticsDashboard',
      data: {
        title: 'The Engine Room: Natural Language to SQL',
        description: 'How Arcli converts an English request into a structured geographic discounting report.',
        dialect: 'DuckDB SQL',
        code: `-- User Prompt: "Revenue by California city where SUMMER20 was used"
SELECT 
    shipping_address_city AS city,
    COUNT(id) AS total_orders,
    SUM(total_price) AS gross_revenue,
    SUM(total_discounts) AS discount_amount
FROM tenant_workspace.shopify.orders
WHERE shipping_address_province = 'California'
  AND discount_codes LIKE '%SUMMER20%'
  AND created_at >= DATE_TRUNC('month', CURRENT_DATE)
GROUP BY 1
ORDER BY gross_revenue DESC;`,
        businessOutcome: 'Empowers non-technical operators to interrogate their data directly, removing the analytics bottleneck.'
      }
    },
    {
      type: 'CTAGroup',
      primaryCTA: { text: 'Start Building Reports', href: '/register?intent=reports' },
      secondaryCTA: { text: 'View Integration Specs', href: '/integrations/shopify' }
    }
  ],
  faqs: [
    {
      q: 'Can I save these reports?',
      a: 'Yes. Any natural language query can be pinned to your personalized dashboard as a live, continuously updating chart or table.',
      persona: 'Operations Manager'
    }
  ]
};