// lib/seo/workflow-jtbd-1.tsx
import { SEOPageData } from './index';

/**
 * SEO JTBD Campaign: Automating Ad-Hoc Reporting
 * Target Audience: VP of Data, BI Managers, Head of RevOps
 * Upgraded to V13 System: Moat-protected technical density, Schema.org injected, Conversion-optimized.
 */
export const adHocAutomation: SEOPageData = {
  type: 'campaign',
  seo: {
    title: 'Automate Ad Hoc Reporting with AI | Self-Serve SQL | Arcli',
    description: 'Eliminate the Jira data request backlog. Arcli empowers non-technical teams to generate secure, dialect-perfect SQL via conversational intent, bypassing rigid BI bottlenecks.',
    h1: 'Kill the Ad-Hoc Data Backlog.',
    keywords: [
      'Automate ad hoc reporting', 
      'Self serve BI AI', 
      'Natural language to SQL tool', 
      'Data request deflection', 
      'Stop building one-off dashboards'
    ],
    intent: 'campaign',
    canonicalDomain: 'https://arcli.tech/solutions/ad-hoc-reporting'
  },

  searchIntent: {
    primary: 'Reduce the engineering overhead of manual ad-hoc data pulls and one-off dashboard requests.',
    secondary: ['Scaling self-serve analytics securely', 'Jira data ticket automation', 'AI-driven analyst deflection'],
    queryPriority: 'Tier 1',
    queryClass: ['Commercial investigation', 'How-to']
  },
  
  serpRealism: {
    targetPosition: 'Top 3 for "Automate Ad Hoc Reporting"',
    competitionDifficulty: 'Medium',
    domainAdvantage: 'Targeting the operational friction of Jira/Slack data queues which legacy BI (Tableau/PowerBI) ignores.'
  },

  hero: {
    badge: 'WORKFLOW ORCHESTRATION',
    title: 'Stop Building One-Off Dashboards.',
    subtitle: 'Business teams wait weeks for a simple data pull. Data engineers drown in Slack requests. Arcli breaks the cycle by generating Read-Only SQL directly against your warehouse, enabling true self-serve analytics at the speed of thought.',
    primaryCTA: { text: 'Automate Your Backlog', href: '/register' },
    secondaryCTA: { text: 'Explore the Architecture', href: '/platform' }
  },

  executiveSummary: [
    { value: '80%', label: 'Ticket Deflection', trend: 'up' },
    { value: 'Zero', label: 'Dashboard Maintenance', trend: 'flat' },
    { value: '< 2s', label: 'SQL Compilation Time', trend: 'down' },
    { value: 'SOC2', label: 'Compliant Execution', trend: 'neutral' }
  ],

  workflow: {
    title: 'The Anatomy of Data Request Automation',
    steps: [
      {
        title: 'The Legacy BI Bottleneck',
        description: 'RevOps opens a Jira ticket. Two weeks later, an analyst writes a SQL view, updates dbt, builds a Looker tile, and shares a link. Tomorrow, the filter changes. The cycle restarts.',
        icon: 'XOctagon'
      },
      {
        title: 'The Arcli Orchestration Layer',
        description: 'RevOps expresses intent in English. Arcli grounds the request against your schema, compiles optimized SQL, executes on your warehouse, and renders a visual chart instantly.',
        icon: 'Zap'
      }
    ]
  },

  contrarianBanner: {
    statement: "Dashboards are static debt. Stop treating them like products.",
    subtext: "If a dashboard doesn't answer a stakeholder's *next* question, it has failed. Bypassing rigid UI constraints for a dynamic, AI-orchestrated query layer is the only way to scale organizational data literacy."
  },

  securityGuardrails: [
    {
      title: 'Read-Only RBAC Enforcement',
      description: 'Arcli operates via strictly provisioned Read-Only service accounts, natively inheriting your database’s Row Level Security (RLS) so users only see authorized data subsets.'
    },
    {
      title: 'Zero Row-Level Data Ingestion',
      description: 'We only index metadata (DDL) for semantic routing. Your proprietary row-level data stays in Snowflake/Postgres and is NEVER used for foundational model training.'
    }
  ],

  strategicScenario: {
    title: 'Complex Supply Chain Gap Analysis',
    description: 'Ad-hoc requests often involve complex temporal gaps. Arcli generates the exact dialect-specific window functions required to surface these anomalies instantly.',
    dialect: 'PostgreSQL',
    sql: `-- Generated by Arcli Semantic Orchestrator
WITH daily_inventory AS (
    SELECT 
        DATE_TRUNC('day', recorded_at) AS metric_date,
        product_id,
        MIN(inventory_level) AS stock_on_hand,
        SUM(units_sold) AS sales_volume
    FROM warehouse.inventory_logs
    WHERE recorded_at >= CURRENT_DATE - INTERVAL '90 days'
    GROUP BY 1, 2
),
temporal_variance AS (
    SELECT 
        *,
        LAG(sales_volume, 1) OVER (PARTITION BY product_id ORDER BY metric_date) AS prev_day_sales
    FROM daily_inventory
)
SELECT 
    metric_date,
    p.product_name,
    stock_on_hand,
    sales_volume,
    ROUND(((sales_volume - prev_day_sales) / NULLIF(prev_day_sales, 0)) * 100, 2) AS WoW_surge_pct
FROM temporal_variance tv
JOIN warehouse.products p ON tv.product_id = p.id
WHERE stock_on_hand < 50 
  AND sales_volume > prev_day_sales * 1.25
ORDER BY sales_volume DESC;`,
    businessOutcome: 'Instantly surfaces high-velocity stockout risks where sales surged >25% while inventory dipped below 50 units, allowing Ops to reorder before the next day starts.'
  },

  faqs: [
    {
      q: 'Will my business stakeholders understand the database schema?',
      a: 'They don’t need to. Arcli uses high-dimensional metadata embedding. A user asks for "customer lifetime" and Arcli maps it to your underlying `fct_billing` table via semantic proximity.',
      persona: 'Data Architect'
    },
    {
      q: 'What prevents the AI from running a query that crashes our warehouse?',
      a: 'Arcli acts as a defensive semantic proxy. Our query planner structurally injects `LIMIT` clauses, enforces partition boundaries, and respects timeout hard-limits configured in your database driver.',
      persona: 'Database Administrator'
    },
    {
      q: 'Can these ad-hoc insights be saved for repeat use?',
      a: 'Yes. Any conversational insight can be pinned to a collaborative Semantic Board. Unlike static dashboards, Arcli saves the logic, ensuring data is queried fresh from the warehouse every time.',
      persona: 'BI Manager'
    }
  ],

  structuredData: {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "What prevents the AI from running a query that crashes our warehouse?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Arcli acts as a defensive semantic proxy. Our query planner structurally injects LIMIT clauses, enforces partition boundaries, and respects timeout hard-limits."
        }
      },
      {
        "@type": "Question",
        "name": "Can these ad-hoc insights be saved for repeat use?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Yes. Any conversational insight can be pinned to a collaborative Semantic Board. Arcli saves the logic, ensuring data is queried fresh from the warehouse every time."
        }
      }
    ]
  },

  codeSnippet: {
    filename: 'orchestrator_logs.yml',
    code: `workflow_id: "adhoc_revenue_surge"\nintent_parsing: 120ms\nsql_compilation: 890ms\nsecurity_check: "passed"\nast_validation: "verified"\nresult_streaming: "parquet_agg"`
  }
};

/**
 * SEO JTBD Campaign: Bypassing the Semantic Layer
 * Target Audience: Data Architects, CTOs, Analytics Engineers
 */
export const semanticLayerBypass: SEOPageData = {
  type: 'campaign',
  seo: {
    title: 'Bypass the BI Semantic Layer | Direct Warehouse AI Analytics',
    description: 'Skip the 6-month semantic layer build. Arcli’s AI orchestrator reads your raw metadata and generates precise SQL directly against your warehouse.',
    h1: 'The Semantic Layer is a Bottleneck.',
    keywords: [
      'Bypass BI semantic layer', 
      'Direct to warehouse AI analytics', 
      'No semantic layer BI', 
      'LookML alternative AI',
      'Direct Snowflake AI querying'
    ],
    intent: 'campaign',
    canonicalDomain: 'https://arcli.tech/solutions/semantic-layer-alternative'
  },

  searchIntent: {
    primary: 'Explore data directly in the warehouse without waiting for a semantic modeling layer (LookML/DAX) to be built.',
    secondary: ['Accelerating TTV for new data lakes', 'Direct-to-warehouse analytics', 'Scaling BI without modeling engineers'],
    queryPriority: 'Tier 1',
    queryClass: ['Commercial investigation', 'Comparison']
  },

  hero: {
    badge: 'ARCHITECTURAL INNOVATION',
    title: 'Query Your Warehouse. Skip the Modeling.',
    subtitle: 'Legacy BI forces you to build massive, brittle semantic models before anyone can ask a single question. Arcli grounds its AI directly in your raw metadata, enabling instant natural language querying from Day 1.',
    primaryCTA: { text: 'Connect Your Warehouse', href: '/register' },
    secondaryCTA: { text: 'Read the Architecture', href: '/docs/semantic-routing' }
  },

  executiveSummary: [
    { value: 'Zero', label: 'Proprietary Code Required', trend: 'flat' },
    { value: '100%', label: 'Schema Grounded', trend: 'up' },
    { value: 'Native', label: 'dbt Cloud Integration', trend: 'neutral' },
    { value: 'O(1)', label: 'Modeling Overhead', trend: 'down' }
  ],

  features: {
    title: 'How Arcli Decouples Analysis from Modeling',
    items: [
      {
        title: 'Metadata Vectorization',
        description: 'We embed your table definitions, primary keys, and constraint logic into a vector space, allowing the AI to mathematically navigate your relational model without a predefined "Explore."',
        icon: 'Network'
      },
      {
        title: 'Deterministic Query Planning',
        description: 'Arcli builds an Abstract Syntax Tree (AST) to validate every join path, preventing cartesian explosions and blocking table hallucinations before they hit your compute budget.',
        icon: 'ShieldCheck'
      },
      {
        title: 'Elastic Metric Governance',
        description: 'Instead of thousands of lines of LookML, define core KPIs (e.g., "MQL") in plain English. Arcli injects these deterministic definitions into generated SQL at compile time.',
        icon: 'Code2'
      }
    ]
  },

  contrarianBanner: {
    statement: "You don't need a 6-month modeling project to find your active users.",
    subtext: "The modern data stack became obsessed with modeling every possible edge case. Arcli believes in agility: query raw data safely using AI, and only formally model the metrics that prove to be systematically critical."
  },

  securityGuardrails: [
    {
      title: 'Decoupled Compute & Storage',
      description: 'Your compute stays in your Snowflake or BigQuery VPC. Arcli merely sends compiled SQL strings and receives aggregated result sets, maintaining strict data sovereignty.'
    },
    {
      title: 'No Modeling Lock-In',
      description: 'Because Arcli writes standard database dialects instead of proprietary languages, you retain complete ownership of your business logic. There is no proprietary "Arcli-ML" to learn.'
    }
  ],

  strategicScenario: {
    title: 'Dynamic Semi-Structured JSON Extraction',
    description: 'Traditional semantic layers struggle with nested data, forcing you to explicitly model every JSON key. Arcli natively generates the specific extraction logic on the fly.',
    dialect: 'Snowflake SQL',
    sql: `-- Generated by Arcli AI Orchestrator
SELECT 
    f.value:event_type::STRING AS interaction_type,
    COUNT(DISTINCT r.user_id) AS unique_active_users,
    ROUND(AVG(f.value:latency_ms::NUMBER), 2) AS avg_latency
FROM telemetry.raw_events r,
LATERAL FLATTEN(input => r.payload:user_actions) f
WHERE r.ingested_at >= DATEADD(day, -7, CURRENT_TIMESTAMP())
  AND r.app_version = 'v3.2.0'
GROUP BY 1
HAVING unique_active_users > 50
ORDER BY 2 DESC;`,
    businessOutcome: 'Allows Product Teams to instantly interrogate deeply nested telemetry arrays to verify a new release, bypassing the week-long queue for dbt model updates.'
  },

  faqs: [
    {
      q: 'Does Arcli replace dbt?',
      a: 'No. They are complementary. dbt is for heavy transformations (raw to gold). Arcli sits on top of your gold tables, replacing the rigid BI modeling layer so stakeholders can query clean data directly.',
      persona: 'Analytics Engineer'
    },
    {
      q: 'How do you handle ambiguous joins without a semantic model?',
      a: 'Arcli maps your INFORMATION_SCHEMA constraints. If join paths are ambiguous, our query planner analyzes nomenclature proximity and triggers a UI clarification prompt if intent is unclear.',
      persona: 'Data Architect'
    },
    {
      q: 'Can different teams define metrics differently?',
      a: 'Yes. Our Governance layer supports Persona-Scoped metrics. "Revenue" for Marketing can be gross, while "Revenue" for Finance is GAAP-compliant. Arcli disambiguates based on the user\'s RBAC group.',
      persona: 'Head of Data'
    }
  ],

  structuredData: {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "name": "Arcli Semantic Bypass Engine",
    "applicationCategory": "BusinessIntelligence",
    "operatingSystem": "Web",
    "offers": {
      "@type": "Offer",
      "price": "0",
      "priceCurrency": "USD"
    }
  },

  codeSnippet: {
    filename: 'semantic_bypass_config.json',
    code: `{\n  "metadata_crawling": "enabled",\n  "schema_grounding": "strict",\n  "ast_validation": "enforced",\n  "proprietary_modeling": "none"\n}`
  }
};