// lib/seo/workflow-jtbd-1.tsx

import { SEOPageData } from './index';

/**
 * SEO JTBD Campaign: Automating Ad-Hoc Reporting
 * Target Audience: VP of Data, BI Managers, Operations Leaders
 * Core Focus: Killing the Jira data request backlog, self-serve enablement, complex SQL generation.
 */
export const adHocAutomation: SEOPageData = {
  type: 'campaign',
  seo: {
    title: 'Automate Ad Hoc Reporting with AI | Self-Serve BI | Arcli',
    description: 'Stop building one-off dashboards. Arcli empowers stakeholders to generate secure, dialect-perfect SQL via natural language, eliminating your ad-hoc data queue.',
    h1: 'Kill the Ad-Hoc Data Backlog.',
    keywords: ['Automate ad hoc reporting', 'Self serve BI AI', 'Natural language to SQL tool', 'AI ad hoc analysis', 'Stop building dashboards'],
    intent: 'campaign',
    canonicalDomain: 'https://arcli.tech/solutions/ad-hoc-reporting'
  },
  hero: {
    badge: 'WORKFLOW AUTOMATION',
    title: 'Stop Building One-Off Dashboards.',
    subtitle: 'Business teams wait weeks for a simple data pull. Data teams are drowning in Slack requests. Arcli breaks the cycle by generating Read-Only SQL directly against your warehouse, enabling true self-serve analytics.',
    primaryCTA: { text: 'Automate Your Backlog', href: '/register' },
    secondaryCTA: { text: 'See How It Works', href: '/platform' }
  },

  // Maps to ExecutiveSummary in seo-blocks-3.tsx
  executiveSummary: [
    { value: '40%', label: 'Data Engineering Time Saved' },
    { value: '0', label: 'New Dashboards Created' },
    { value: '< 3s', label: 'Average Query Time' },
    { value: '100%', label: 'VPC Native Execution' }
  ],

  // Maps to Workflow in seo-blocks-1.tsx
  workflow: {
    title: 'The Anatomy of a Data Request',
    steps: [
      {
        title: 'The Legacy BI Bottleneck',
        description: 'RevOps opens a Jira ticket. Two weeks later, a Data Engineer writes the SQL, updates the dbt model, builds a Looker dashboard, and shares a link. The next day, RevOps asks for a new filter. The cycle repeats.',
        icon: 'XOctagon'
      },
      {
        title: 'The Arcli Automation Engine',
        description: 'RevOps asks a question in plain English. Arcli grounds the intent against your schema, generates dialect-perfect SQL, queries the database directly, and renders a dynamic chart instantly. No Jira required.',
        icon: 'Zap'
      }
    ]
  },

  contrarianBanner: {
    statement: "Dashboards are dead documents. Stop treating them like products.",
    subtext: "If a dashboard doesn't perfectly answer a stakeholder's question, it becomes technical debt. Bypassing rigid dashboards for a dynamic, AI-orchestrated query layer is the only way to scale data access."
  },

  // Continuing the Security Mandate
  securityGuardrails: [
    {
      title: 'Stakeholder Read-Only Enforcement',
      description: 'Self-serve does not mean free reign. Arcli operates via strict Read-Only service accounts, inheriting your database’s Row Level Security (RLS) so users only see the data they are authorized to query.'
    },
    {
      title: 'Zero Data Replication',
      description: 'Your data stays in Snowflake or Postgres. Arcli only orchestrates the query logic and temporarily renders the aggregate JSON response. We never cache your sensitive ad-hoc query results.'
    }
  ],

  // Maps to StrategicQuery in seo-blocks-3.tsx
  strategicScenario: {
    title: 'Complex Time-Series Gap Analysis',
    description: 'Ad-hoc requests often involve complex time-series gaps (e.g., "Show me days where inventory dropped below threshold but sales remained high"). Arcli generates the exact PostgreSQL window functions required to find these anomalies without moving data to Pandas.',
    dialect: 'PostgreSQL',
    sql: `-- Generated by Arcli AI Orchestrator
WITH daily_metrics AS (
    SELECT 
        DATE_TRUNC('day', recorded_at) AS metric_date,
        product_id,
        MIN(inventory_level) AS min_inventory,
        SUM(units_sold) AS total_sold
    FROM 
        warehouse.daily_inventory_log
    WHERE 
        recorded_at >= CURRENT_DATE - INTERVAL '90 days'
    GROUP BY 
        1, 2
),
lagged_metrics AS (
    SELECT 
        metric_date,
        product_id,
        min_inventory,
        total_sold,
        LAG(total_sold, 1) OVER (PARTITION BY product_id ORDER BY metric_date) AS prev_day_sales
    FROM 
        daily_metrics
)
SELECT 
    metric_date,
    p.product_name,
    min_inventory,
    total_sold,
    ROUND(((total_sold - prev_day_sales)::numeric / NULLIF(prev_day_sales, 0)) * 100, 2) AS WoW_sales_growth
FROM 
    lagged_metrics lm
JOIN 
    warehouse.products p ON lm.product_id = p.id
WHERE 
    min_inventory < 50 
    AND total_sold > prev_day_sales * 1.2
ORDER BY 
    metric_date DESC;`,
    businessOutcome: 'Instantly surfaces "stockout-risk" events where daily sales spiked by over 20% while inventory dipped below 50 units, empowering operations to adjust reorder points without waiting for an analyst.'
  },

  faqs: [
    {
      q: 'Will business users be able to understand the raw database schema?',
      a: 'They don’t have to. Arcli uses a semantic embedding layer. A user can ask for "revenue" and Arcli maps it to `fct_transactions.amount_usd_settled`. You can also define core business metrics to strictly guide the AI.',
      persona: 'Data Architect'
    },
    {
      q: 'What happens if the AI generates a query that scans a massive, unpartitioned table?',
      a: 'Arcli acts as a defensive proxy. The query planner automatically injects `LIMIT` clauses, enforces partition filters (e.g., `_PARTITIONTIME`), and respects the timeout settings configured by your database administrator.',
      persona: 'Database Administrator'
    },
    {
      q: 'Can users save and share their ad-hoc findings?',
      a: 'Yes. Once Arcli generates an insight, the user can pin it to a shared collaborative workspace. The underlying logic is saved, but the data is queried fresh upon every page load to guarantee zero stale data.',
      persona: 'BI Manager'
    }
  ]
};

/**
 * SEO JTBD Campaign: Bypassing the Semantic Layer
 * Target Audience: Data Architects, Analytics Engineers, CTOs
 * Core Focus: Faster time-to-value, schema-grounded LLMs, raw data querying.
 */
export const semanticLayerBypass: SEOPageData = {
  type: 'campaign',
  seo: {
    title: 'Bypass the BI Semantic Layer | Schema-Grounded AI Analytics',
    description: 'Skip the 6-month semantic layer build. Arcli’s AI orchestrator reads your raw metadata and generates precise SQL directly against your data warehouse.',
    h1: 'The Semantic Layer is a Bottleneck.',
    keywords: ['Bypass BI semantic layer', 'Direct to warehouse AI analytics', 'Schema grounded AI reporting', 'No semantic layer BI', 'LookML alternative AI'],
    intent: 'campaign',
    canonicalDomain: 'https://arcli.tech/solutions/semantic-layer-alternative'
  },
  hero: {
    badge: 'ARCHITECTURAL INNOVATION',
    title: 'Query Your Warehouse. Skip the Modeling.',
    subtitle: 'Legacy BI forces you to build massive, brittle semantic models before anyone can ask a simple question. Arcli grounds its AI directly in your database schema, enabling instant natural language querying from Day 1.',
    primaryCTA: { text: 'Connect Your Database', href: '/register' },
    secondaryCTA: { text: 'Read the Architecture Docs', href: '/docs/schema-grounding' }
  },

  executiveSummary: [
    { value: 'Zero', label: 'Proprietary Code to Write' },
    { value: '100%', label: 'Schema Grounded' },
    { value: 'Native', label: 'dbt Integration' },
    { value: 'O(1)', label: 'Metric Governance' }
  ],

  // Maps to features in standard blocks to explain the tech
  features: {
    title: 'How Arcli Replaces the Middleman',
    items: [
      {
        title: 'Metadata Vectorization',
        description: 'We ingest your table schemas, column types, and foreign keys, embedding them into a high-dimensional vector space so the AI mathematically understands your relational model.',
        icon: 'Network'
      },
      {
        title: 'Defensive Query Planning',
        description: 'Arcli does not just write raw SQL. It builds an Abstract Syntax Tree (AST) to validate join paths, preventing cartesian explosions and hallucinated tables.',
        icon: 'ShieldCheck'
      },
      {
        title: 'Code-Free Metric Governance',
        description: 'Instead of writing LookML, define your core metrics (e.g., "Active User") in plain English or raw SQL snippets via our API. Arcli forcefully injects these definitions at compile time.',
        icon: 'Code2'
      }
    ]
  },

  contrarianBanner: {
    statement: "You shouldn't need a 6-month data modeling project to find out how many active users logged in yesterday.",
    subtext: "The modern data stack became obsessed with modeling every edge case. Arcli believes in agility: query the raw data safely using AI, and only model the data that proves to be systematically critical."
  },

  securityGuardrails: [
    {
      title: 'Decoupled Compute & Storage',
      description: 'By bypassing a proprietary semantic layer cloud, your compute stays exactly where it belongs: in your Snowflake or BigQuery VPC. We just send the compiled SQL strings.'
    },
    {
      title: 'No Vendor Lock-In',
      description: 'Because Arcli writes standard database dialects instead of proprietary modeling languages (like DAX or LookML), you retain complete ownership of your analytical logic.'
    }
  ],

  strategicScenario: {
    title: 'Dynamic Snowflake JSON Flattening',
    description: 'Traditional semantic layers fail at nested, unstructured data. You have to explicitly model every JSON key. Arcli natively generates Snowflake `FLATTEN` logic on the fly based on natural language intent.',
    dialect: 'Snowflake SQL',
    sql: `-- Generated by Arcli AI Orchestrator
SELECT 
    f.value:event_type::STRING AS interaction_type,
    COUNT(DISTINCT r.user_id) AS unique_users,
    AVG(f.value:duration_ms::NUMBER) AS avg_interaction_time_ms
FROM 
    raw_telemetry.app_events r,
    LATERAL FLATTEN(input => r.payload:user_interactions) f
WHERE 
    r.ingested_at >= DATEADD(day, -7, CURRENT_TIMESTAMP())
    AND r.app_version = 'v2.1.0'
GROUP BY 
    interaction_type
HAVING 
    COUNT(DISTINCT r.user_id) > 100
ORDER BY 
    unique_users DESC;`,
    businessOutcome: 'Allows Product Managers to instantly unpack deeply nested telemetry JSON arrays to analyze feature adoption on a new app release, completely bypassing the Data Engineering dbt backlog.'
  },

  faqs: [
    {
      q: 'Does Arcli replace dbt?',
      a: 'No. Arcli and dbt are highly complementary. dbt is excellent for heavy data transformations (bronze to gold). Arcli sits on top of your gold tables, replacing the rigid BI layer so users can query the clean data dynamically.',
      persona: 'Analytics Engineer'
    },
    {
      q: 'How does Arcli know how to join tables without a semantic model?',
      a: 'Arcli maps explicit Foreign Key constraints. Where constraints don’t exist, our AI query planner infers join paths by analyzing column nomenclature (e.g., `user_id` to `id`) and runs lightweight validation checks before execution.',
      persona: 'Data Architect'
    },
    {
      q: 'What if multiple departments define "Revenue" differently?',
      a: 'Arcli solves this via Persona-Scoped Metric Governance. You can define "Marketing Revenue" and "GAAP Revenue" in the admin console. When a user asks a question, Arcli disambiguates the term based on their RBAC group or asks a clarifying question.',
      persona: 'Head of Data'
    }
  ]
};