-- Prospect-intelligence telemetry and customer-feedback contract.
--
-- Apply after scripts/RLS_updates.sql (which creates tenants,
-- service_profiles, and lead_matches).  The worker supplies the discovery run
-- UUID, so the Python helper remains fail-open if this migration is not yet
-- applied.  Browser clients receive tenant-scoped read access only, except for
-- immutable lead-feedback inserts.

BEGIN;

CREATE TABLE IF NOT EXISTS public.discovery_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id TEXT NOT NULL REFERENCES public.tenants(tenant_id) ON DELETE CASCADE,
    service_profile_id UUID NOT NULL,
    query_plan JSONB NOT NULL DEFAULT '{"version":1,"queries":[]}'::JSONB,
    status TEXT NOT NULL DEFAULT 'running',
    summary JSONB NOT NULL DEFAULT '{}'::JSONB,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT discovery_runs_status_check
        CHECK (status IN ('running', 'completed', 'partial', 'failed', 'cancelled', 'skipped'))
);

CREATE TABLE IF NOT EXISTS public.discovery_run_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id TEXT NOT NULL REFERENCES public.tenants(tenant_id) ON DELETE CASCADE,
    run_id UUID NOT NULL,
    source TEXT NOT NULL,
    query_type TEXT NOT NULL,
    query_hash TEXT NOT NULL,
    event_key TEXT NOT NULL,
    phase TEXT NOT NULL,
    outcome TEXT NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT discovery_run_events_query_hash_check
        CHECK (query_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT discovery_run_events_event_key_check
        CHECK (event_key ~ '^[0-9a-f]{64}$')
);

CREATE TABLE IF NOT EXISTS public.lead_feedback (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id TEXT NOT NULL REFERENCES public.tenants(tenant_id) ON DELETE CASCADE,
    lead_match_id UUID NOT NULL,
    user_id TEXT NOT NULL,
    feedback_type TEXT NOT NULL,
    reason_code TEXT,
    details JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT lead_feedback_type_check
        CHECK (feedback_type IN ('good_fit', 'wrong_buyer', 'useful_pain_not_now', 'not_relevant', 'spam'))
);

-- The ALTER keeps a re-applied contract compatible with an early rollout.
-- There should be no feedback rows before this new contract; fail explicitly
-- instead of silently assigning an existing customer's feedback to a user.
ALTER TABLE public.lead_feedback
    ADD COLUMN IF NOT EXISTS user_id TEXT;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.lead_feedback WHERE user_id IS NULL) THEN
        RAISE EXCEPTION 'lead_feedback.user_id must be backfilled before applying this contract';
    END IF;
END;
$$;
ALTER TABLE public.lead_feedback
    ALTER COLUMN user_id SET NOT NULL;

-- Composite keys make cross-tenant references impossible even for trusted
-- service/database roles.  IDs are globally unique today, but tenant-scoped
-- foreign keys protect the contract against future migrations and mistakes.
-- Do not drop these keys on re-apply: the composite FKs below depend on them.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'uq_service_profiles_tenant_id_id'
           AND conrelid = 'public.service_profiles'::regclass
    ) THEN
        ALTER TABLE public.service_profiles
            ADD CONSTRAINT uq_service_profiles_tenant_id_id UNIQUE (tenant_id, id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'uq_lead_matches_tenant_id_id'
           AND conrelid = 'public.lead_matches'::regclass
    ) THEN
        ALTER TABLE public.lead_matches
            ADD CONSTRAINT uq_lead_matches_tenant_id_id UNIQUE (tenant_id, id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'uq_discovery_runs_tenant_id_id'
           AND conrelid = 'public.discovery_runs'::regclass
    ) THEN
        ALTER TABLE public.discovery_runs
            ADD CONSTRAINT uq_discovery_runs_tenant_id_id UNIQUE (tenant_id, id);
    END IF;
END;
$$;

ALTER TABLE public.discovery_runs
    DROP CONSTRAINT IF EXISTS fk_discovery_runs_tenant_service_profile;
ALTER TABLE public.discovery_runs
    ADD CONSTRAINT fk_discovery_runs_tenant_service_profile
    FOREIGN KEY (tenant_id, service_profile_id)
    REFERENCES public.service_profiles (tenant_id, id)
    ON DELETE RESTRICT;

ALTER TABLE public.discovery_run_events
    DROP CONSTRAINT IF EXISTS fk_discovery_run_events_tenant_run;
ALTER TABLE public.discovery_run_events
    ADD CONSTRAINT fk_discovery_run_events_tenant_run
    FOREIGN KEY (tenant_id, run_id)
    REFERENCES public.discovery_runs (tenant_id, id)
    ON DELETE CASCADE;

ALTER TABLE public.lead_feedback
    DROP CONSTRAINT IF EXISTS fk_lead_feedback_tenant_lead_match;
ALTER TABLE public.lead_feedback
    ADD CONSTRAINT fk_lead_feedback_tenant_lead_match
    FOREIGN KEY (tenant_id, lead_match_id)
    REFERENCES public.lead_matches (tenant_id, id)
    ON DELETE CASCADE;

ALTER TABLE public.discovery_runs
    DROP CONSTRAINT IF EXISTS discovery_runs_status_check;
ALTER TABLE public.discovery_runs
    ADD CONSTRAINT discovery_runs_status_check
    CHECK (status IN ('running', 'completed', 'partial', 'failed', 'cancelled', 'skipped'));

ALTER TABLE public.discovery_run_events
    DROP CONSTRAINT IF EXISTS discovery_run_events_query_hash_check;
ALTER TABLE public.discovery_run_events
    ADD CONSTRAINT discovery_run_events_query_hash_check
    CHECK (query_hash ~ '^[0-9a-f]{64}$');

ALTER TABLE public.discovery_run_events
    DROP CONSTRAINT IF EXISTS discovery_run_events_event_key_check;
ALTER TABLE public.discovery_run_events
    ADD CONSTRAINT discovery_run_events_event_key_check
    CHECK (event_key ~ '^[0-9a-f]{64}$');

ALTER TABLE public.lead_feedback
    DROP CONSTRAINT IF EXISTS lead_feedback_type_check;
UPDATE public.lead_feedback
   SET feedback_type = CASE feedback_type
       WHEN 'good_lead' THEN 'good_fit'
       WHEN 'bad_lead' THEN 'not_relevant'
       WHEN 'wrong_audience' THEN 'wrong_buyer'
       WHEN 'useful_not_now' THEN 'useful_pain_not_now'
       ELSE feedback_type
   END
 WHERE feedback_type IN (
       'good_lead',
       'bad_lead',
       'wrong_audience',
       'useful_not_now'
 );
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM public.lead_feedback
         WHERE feedback_type NOT IN (
             'good_fit',
             'wrong_buyer',
             'useful_pain_not_now',
             'not_relevant',
             'spam'
         )
    ) THEN
        RAISE EXCEPTION
            'lead_feedback contains an unsupported feedback_type; map it before applying the prospect-intelligence contract';
    END IF;

    -- Do not silently delete historical reviewer input to make a new
    -- idempotency constraint fit. Surface this to the operator instead.
    IF EXISTS (
        SELECT 1
          FROM public.lead_feedback
         GROUP BY tenant_id, lead_match_id, user_id, feedback_type
        HAVING COUNT(*) > 1
    ) THEN
        RAISE EXCEPTION
            'lead_feedback contains duplicate user feedback; resolve duplicates before applying the prospect-intelligence contract';
    END IF;
END;
$$;
ALTER TABLE public.lead_feedback
    ADD CONSTRAINT lead_feedback_type_check
    CHECK (feedback_type IN ('good_fit', 'wrong_buyer', 'useful_pain_not_now', 'not_relevant', 'spam'));

CREATE INDEX IF NOT EXISTS idx_discovery_runs_tenant_started_at
    ON public.discovery_runs(tenant_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_discovery_runs_tenant_profile_started_at
    ON public.discovery_runs(tenant_id, service_profile_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_discovery_run_events_tenant_run_occurred_at
    ON public.discovery_run_events(tenant_id, run_id, occurred_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_discovery_run_events_tenant_run_event_key
    ON public.discovery_run_events(tenant_id, run_id, event_key);
CREATE INDEX IF NOT EXISTS idx_lead_feedback_tenant_lead_match_created_at
    ON public.lead_feedback(tenant_id, lead_match_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lead_feedback_tenant_user_created_at
    ON public.lead_feedback(tenant_id, user_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_lead_feedback_tenant_lead_user_type
    ON public.lead_feedback(tenant_id, lead_match_id, user_id, feedback_type);

CREATE OR REPLACE FUNCTION public.set_prospect_intelligence_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

-- These guards duplicate the composite foreign keys deliberately: they return
-- a clear error for direct SQL writes and prevent tenant reassignment on later
-- updates.  The function search path is fixed to avoid search-path hijacking.
CREATE OR REPLACE FUNCTION public.guard_discovery_run_tenant_scope()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF TG_OP = 'UPDATE'
       AND (NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
            OR NEW.service_profile_id IS DISTINCT FROM OLD.service_profile_id) THEN
        RAISE EXCEPTION 'discovery run tenant and service profile are immutable'
            USING ERRCODE = '23514';
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM public.service_profiles AS profile
         WHERE profile.id = NEW.service_profile_id
           AND profile.tenant_id = NEW.tenant_id
    ) THEN
        RAISE EXCEPTION 'service profile does not belong to discovery run tenant'
            USING ERRCODE = '23503';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.guard_discovery_run_event_tenant_scope()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF TG_OP = 'UPDATE'
       AND (NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
            OR NEW.run_id IS DISTINCT FROM OLD.run_id) THEN
        RAISE EXCEPTION 'discovery event tenant and run are immutable'
            USING ERRCODE = '23514';
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM public.discovery_runs AS run
         WHERE run.id = NEW.run_id
           AND run.tenant_id = NEW.tenant_id
    ) THEN
        RAISE EXCEPTION 'discovery event run does not belong to tenant'
            USING ERRCODE = '23503';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.guard_lead_feedback_tenant_scope()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF TG_OP = 'UPDATE'
       AND (NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
            OR NEW.lead_match_id IS DISTINCT FROM OLD.lead_match_id
            OR NEW.user_id IS DISTINCT FROM OLD.user_id) THEN
        RAISE EXCEPTION 'lead feedback tenant, lead match, and user are immutable'
            USING ERRCODE = '23514';
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM public.lead_matches AS lead_match
         WHERE lead_match.id = NEW.lead_match_id
           AND lead_match.tenant_id = NEW.tenant_id
    ) THEN
        RAISE EXCEPTION 'lead match does not belong to feedback tenant'
            USING ERRCODE = '23503';
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM public.tenant_users AS tenant_user
         WHERE tenant_user.tenant_id::TEXT = NEW.tenant_id::TEXT
           AND tenant_user.user_id::TEXT = NEW.user_id::TEXT
    ) THEN
        RAISE EXCEPTION 'feedback user does not belong to tenant'
            USING ERRCODE = '23503';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS discovery_runs_scope_guard ON public.discovery_runs;
CREATE TRIGGER discovery_runs_scope_guard
    BEFORE INSERT OR UPDATE ON public.discovery_runs
    FOR EACH ROW EXECUTE FUNCTION public.guard_discovery_run_tenant_scope();

DROP TRIGGER IF EXISTS discovery_runs_updated_at ON public.discovery_runs;
CREATE TRIGGER discovery_runs_updated_at
    BEFORE UPDATE ON public.discovery_runs
    FOR EACH ROW EXECUTE FUNCTION public.set_prospect_intelligence_updated_at();

DROP TRIGGER IF EXISTS discovery_run_events_scope_guard ON public.discovery_run_events;
CREATE TRIGGER discovery_run_events_scope_guard
    BEFORE INSERT OR UPDATE ON public.discovery_run_events
    FOR EACH ROW EXECUTE FUNCTION public.guard_discovery_run_event_tenant_scope();

DROP TRIGGER IF EXISTS lead_feedback_scope_guard ON public.lead_feedback;
CREATE TRIGGER lead_feedback_scope_guard
    BEFORE INSERT OR UPDATE ON public.lead_feedback
    FOR EACH ROW EXECUTE FUNCTION public.guard_lead_feedback_tenant_scope();

DROP TRIGGER IF EXISTS lead_feedback_updated_at ON public.lead_feedback;
CREATE TRIGGER lead_feedback_updated_at
    BEFORE UPDATE ON public.lead_feedback
    FOR EACH ROW EXECUTE FUNCTION public.set_prospect_intelligence_updated_at();

-- Direct database/service roles write discovery telemetry.  Authenticated
-- browser users can only read rows in their workspace and add feedback for a
-- lead match in that workspace; they cannot create, edit, or remove runs.
ALTER TABLE public.discovery_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discovery_run_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_feedback ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON TABLE public.discovery_runs TO authenticated;
GRANT SELECT ON TABLE public.discovery_run_events TO authenticated;
GRANT SELECT, INSERT ON TABLE public.lead_feedback TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.discovery_runs FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.discovery_run_events FROM authenticated;
REVOKE UPDATE, DELETE ON TABLE public.lead_feedback FROM authenticated;

DROP POLICY IF EXISTS discovery_runs_select_tenant ON public.discovery_runs;
CREATE POLICY discovery_runs_select_tenant ON public.discovery_runs
    FOR SELECT TO authenticated
    USING (
        EXISTS (
            SELECT 1
              FROM public.tenant_users AS tenant_user
             WHERE tenant_user.tenant_id::TEXT = discovery_runs.tenant_id::TEXT
               AND tenant_user.user_id::TEXT = auth.uid()::TEXT
        )
    );

DROP POLICY IF EXISTS discovery_run_events_select_tenant ON public.discovery_run_events;
CREATE POLICY discovery_run_events_select_tenant ON public.discovery_run_events
    FOR SELECT TO authenticated
    USING (
        EXISTS (
            SELECT 1
              FROM public.tenant_users AS tenant_user
             WHERE tenant_user.tenant_id::TEXT = discovery_run_events.tenant_id::TEXT
               AND tenant_user.user_id::TEXT = auth.uid()::TEXT
        )
    );

DROP POLICY IF EXISTS lead_feedback_select_tenant ON public.lead_feedback;
CREATE POLICY lead_feedback_select_tenant ON public.lead_feedback
    FOR SELECT TO authenticated
    USING (
        EXISTS (
            SELECT 1
              FROM public.tenant_users AS tenant_user
             WHERE tenant_user.tenant_id::TEXT = lead_feedback.tenant_id::TEXT
               AND tenant_user.user_id::TEXT = auth.uid()::TEXT
        )
    );

DROP POLICY IF EXISTS lead_feedback_insert_tenant ON public.lead_feedback;
CREATE POLICY lead_feedback_insert_tenant ON public.lead_feedback
    FOR INSERT TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1
              FROM public.tenant_users AS tenant_user
             WHERE tenant_user.tenant_id::TEXT = lead_feedback.tenant_id::TEXT
               AND tenant_user.user_id::TEXT = auth.uid()::TEXT
        )
        AND lead_feedback.user_id::TEXT = auth.uid()::TEXT
        AND EXISTS (
            SELECT 1
              FROM public.lead_matches AS lead_match
             WHERE lead_match.id = lead_feedback.lead_match_id
               AND lead_match.tenant_id::TEXT = lead_feedback.tenant_id::TEXT
        )
    );

REVOKE ALL ON FUNCTION public.guard_discovery_run_tenant_scope() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.guard_discovery_run_event_tenant_scope() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.guard_lead_feedback_tenant_scope() FROM PUBLIC;

NOTIFY pgrst, 'reload schema';

COMMIT;
