# api/auth.py

import os
import logging
import jwt  # Requires: pip install PyJWT
from typing import Dict, Any, Optional
from dataclasses import dataclass
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel, EmailStr, Field
from supabase import create_client, Client
from dotenv import load_dotenv

# Configure logging for observability
logger = logging.getLogger(__name__)
load_dotenv()

# Initialize API Router for modular registration
auth_router = APIRouter(prefix="/api/v1/auth", tags=["Auth"])

# FastAPI security scheme
security = HTTPBearer()

# Singleton placeholder for the Supabase client
_supabase_client: Optional[Client] = None


# ─── Pydantic Schemas ──────────────────────────────────────────────

class RegisterRequest(BaseModel):
    """
    Strict payload validation for the registration flow.
    Ensures the smart defaults generated by the frontend are correctly typed and sanitized.
    """
    email: EmailStr
    password: str = Field(..., min_length=8, description="Must be at least 8 characters.")
    full_name: str = Field(..., description="Fallback or actual user name")
    company_name: str = Field(..., description="Fallback or actual tenant company name")


@dataclass
class TenantContext:
    """
    Object-Oriented Security: Encapsulates the verified user and tenant data.
    Ensures downstream services rely on strict properties, preventing dictionary-key typos 
    and accidental data leakage across tenants.
    """
    user_id: str
    tenant_id: str
    email: Optional[str] = None
    app_metadata: Optional[Dict[str, Any]] = None


# ─── Core Services & Dependencies ──────────────────────────────────

def get_supabase_client() -> Client:
    """Lazy initialization of the Supabase client to prevent startup crashes."""
    global _supabase_client
    if _supabase_client is None:
        url = os.getenv("SUPABASE_URL")
        # Ensure we use the SERVICE_ROLE_KEY for admin actions like user creation bypassing email confirmation
        key = os.getenv("SUPABASE_SERVICE_ROLE_KEY") or os.getenv("SUPABASE_ANON_KEY")
        
        if not url or not key:
            raise RuntimeError("Supabase URL or Key is missing from environment.")
            
        _supabase_client = create_client(url, key)
    return _supabase_client


def get_current_user(credentials: HTTPAuthorizationCredentials = Depends(security)) -> Dict[str, Any]:
    """
    SaaS Performance Upgrade: Attempts stateless JWT verification first.
    Local decoding reduces auth latency to <1ms, preventing API rate limits.
    """
    token = credentials.credentials
    jwt_secret = os.getenv("SUPABASE_JWT_SECRET")

    # FAST PATH: Stateless Local Verification
    if jwt_secret:
        try:
            # Supabase uses HS256 for signing standard JWTs
            decoded_payload = jwt.decode(
                token,
                jwt_secret,
                algorithms=["HS256"],
                options={"verify_aud": False} # Supabase audience varies by project config
            )
            return decoded_payload
        except jwt.ExpiredSignatureError:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Token has expired")
        except jwt.InvalidTokenError as e:
            logger.warning(f"Stateless JWT verification failed: {e}")
            # Fallthrough to network check if local decoding fails
            
    # SLOW PATH: Network Verification (Fallback)
    try:
        client = get_supabase_client()
        user_response = client.auth.get_user(token)
        
        if not user_response or not user_response.user:
            raise ValueError("Invalid user token")
            
        # Safely convert Supabase user object to dict
        return user_response.user.model_dump() if hasattr(user_response.user, 'model_dump') else dict(user_response.user)
        
    except Exception as e:
        logger.warning(f"Network Authentication failed: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authentication credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )


def verify_tenant(user_payload: Dict[str, Any] = Depends(get_current_user)) -> TenantContext:
    """
    Security by Design: Validates and locks the context to a specific tenant.
    Inject this dependency into your routes to enforce strict multi-tenant boundaries.
    """
    # Handle both stateless (JWT payload 'sub') and network (Supabase dump 'id') formats
    user_id = user_payload.get("sub") or user_payload.get("id")
    email = user_payload.get("email")
    app_metadata = user_payload.get("app_metadata", {})
    user_metadata = user_payload.get("user_metadata", {})
    
    # Priority 1: B2B Organization/Tenant ID from app_metadata
    # Priority 2: User metadata fallback
    # Priority 3: B2C Solo User ID
    tenant_id = app_metadata.get("tenant_id") or user_metadata.get("tenant_id") or user_id
    
    if not tenant_id or not user_id:
        logger.error("Tenant isolation failed. Missing ID for payload.")
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="User does not belong to a valid tenant setup.",
        )
        
    return TenantContext(
        user_id=str(user_id),
        tenant_id=str(tenant_id),
        email=email,
        app_metadata=app_metadata
    )


def get_current_tenant_id(tenant_context: TenantContext = Depends(verify_tenant)) -> str:
    """
    Convenience Dependency: Instantly extracts the tenant_id for rapid API route filtering.
    """
    return tenant_context.tenant_id


# ─── Endpoints ─────────────────────────────────────────────────────

@auth_router.post("/register", status_code=status.HTTP_201_CREATED)
async def register_user(payload: RegisterRequest):
    """
    Multi-tenant Registration Endpoint.
    1. Creates the user in Supabase Auth bypassing email checks (for immediate frontend login).
    2. Embeds the generated company name and full name into the user's metadata.
    """
    try:
        client = get_supabase_client()
        
        # Security by Design: We use the admin API to create the user and auto-confirm them.
        # This allows the frontend's immediate `signInWithPassword` call to succeed.
        response = client.auth.admin.create_user({
            "email": payload.email,
            "password": payload.password,
            "email_confirm": True,
            "user_metadata": {
                "full_name": payload.full_name,
                "company_name": payload.company_name,
                "tenant_id": payload.email  # Temporary baseline tenant_id mapped to email/company
            }
        })
        
        # Here you would typically trigger your Database layer to create the physical 
        # multi-tenant schema/rows, e.g., `db.create_tenant(...)`
        
        return {
            "status": "success", 
            "message": "User and tenant successfully provisioned.",
            "user_id": response.user.id
        }
        
    except Exception as e:
        logger.error(f"Registration Failed for {payload.email}: {str(e)}")
        # Handle cases where the user might already exist
        if "already registered" in str(e).lower():
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="User already exists.")
            
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Could not create user account.")