# api/auth.py

import os
import json
import logging
import jwt  # Requires: pip install PyJWT
from typing import Dict, Any, Optional
from dataclasses import dataclass
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel, EmailStr, Field
from supabase import create_client, Client
from dotenv import load_dotenv

# ------------------------------------------------------------------------------
# 1. Configuration & Security Initialization
# ------------------------------------------------------------------------------
logger = logging.getLogger("DataOmenAuth")
load_dotenv()

# Security by Design: Enforce M2M Key for Cloudflare & Celery to DigitalOcean comms
INTERNAL_SERVICE_KEY = os.getenv("INTERNAL_SERVICE_KEY")
if not INTERNAL_SERVICE_KEY:
    # Structured logging matching the exact format for cloud monitoring
    logger.error(json.dumps({
        "timestamp": "startup",
        "level": "error",
        "tenant_id": "anonymous",
        "event": "critical_startup_failure",
        "error": "Missing INTERNAL_SERVICE_KEY",
        "details": "Machine-to-Machine (M2M) microservice routing will fail without this."
    }))
    # Fail-fast in production to trigger container restart alerts
    if os.getenv("ENVIRONMENT") == "production":
        raise RuntimeError("INTERNAL_SERVICE_KEY is strictly required in production.")

# Initialize API Router for modular registration
auth_router = APIRouter(prefix="/api/v1/auth", tags=["Auth"])

# FastAPI security scheme
security = HTTPBearer()

# Singleton placeholder for the Supabase client
_supabase_client: Optional[Client] = None

# ------------------------------------------------------------------------------
# 2. Strict Pydantic Data Models
# ------------------------------------------------------------------------------
class RegisterRequest(BaseModel):
    """
    Strict payload validation for the registration flow.
    Ensures the smart defaults generated by the frontend are correctly typed and sanitized.
    """
    email: EmailStr
    password: str = Field(..., min_length=8, description="Must be at least 8 characters.")
    full_name: str = Field(..., description="Fallback or actual user name")
    company_name: str = Field(..., description="Fallback or actual tenant company name")

@dataclass
class TenantContext:
    """
    Object-Oriented Security: Encapsulates the verified user and tenant data.
    Ensures downstream services rely on strict properties, preventing dictionary-key typos 
    and accidental data leakage across tenants.
    """
    user_id: str
    tenant_id: str
    email: str
    role: str = "authenticated"
    app_metadata: Optional[Dict[str, Any]] = None

# ------------------------------------------------------------------------------
# 3. Core Services & Performance Dependencies
# ------------------------------------------------------------------------------
def get_supabase_client() -> Client:
    """Lazy initialization of the Supabase client to prevent startup crashes."""
    global _supabase_client
    if _supabase_client is None:
        url = os.getenv("SUPABASE_URL")
        # Ensure we use the SERVICE_ROLE_KEY for admin actions like user creation
        key = os.getenv("SUPABASE_SERVICE_ROLE_KEY") or os.getenv("SUPABASE_ANON_KEY")
        
        if not url or not key:
            raise RuntimeError("Supabase URL or Key is missing from environment.")
            
        _supabase_client = create_client(url, key)
    return _supabase_client

def get_current_user(credentials: HTTPAuthorizationCredentials = Depends(security)) -> Dict[str, Any]:
    """
    SaaS Performance Upgrade: M2M Bypass -> Stateless JWT -> Network Verification
    """
    token = credentials.credentials

    # FAST PATH 0: Machine-to-Machine (M2M) Authentication
    # Permits Cloudflare Workers and Celery Tasks to act as the internal system
    if INTERNAL_SERVICE_KEY and token == INTERNAL_SERVICE_KEY:
        return {
            "sub": "system-worker-0000",
            "email": "system@arcli.tech",
            "role": "service_role",
            "app_metadata": {"tenant_id": "arcli.tech"}
        }

    jwt_secret = os.getenv("SUPABASE_JWT_SECRET")

    # FAST PATH 1: Stateless Local Verification
    # Local decoding reduces auth latency to <1ms, preventing API rate limits.
    if jwt_secret:
        try:
            # Supabase uses HS256 for signing standard JWTs
            decoded_payload = jwt.decode(
                token,
                jwt_secret,
                algorithms=["HS256"],
                options={"verify_aud": False} # Supabase audience varies by project config
            )
            return decoded_payload
        except jwt.ExpiredSignatureError:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Token has expired")
        except jwt.InvalidTokenError as e:
            logger.warning(f"Stateless JWT verification failed: {e}")
            # Fallthrough to network check if local decoding fails
            
    # SLOW PATH: Network Verification (Fallback)
    try:
        client = get_supabase_client()
        user_response = client.auth.get_user(token)
        
        if not user_response or not user_response.user:
            raise ValueError("Invalid user token")
            
        # Safely convert Supabase user object to dict
        return user_response.user.model_dump() if hasattr(user_response.user, 'model_dump') else dict(user_response.user)
        
    except Exception as e:
        logger.warning(f"Network Authentication failed: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authentication credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )

def verify_tenant(user_payload: Dict[str, Any] = Depends(get_current_user)) -> TenantContext:
    """
    Security by Design: Validates and locks the context to a specific tenant.
    Inject this dependency into your routes to enforce strict multi-tenant boundaries.
    """
    user_id = user_payload.get("sub") or user_payload.get("id")
    email = user_payload.get("email", "")
    app_metadata = user_payload.get("app_metadata", {})
    user_metadata = user_payload.get("user_metadata", {})
    
    if not user_id or not email:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Malformed identity profile.")

    # 0. M2M System Bypass
    if user_id == "system-worker-0000":
        return TenantContext(
            user_id=str(user_id),
            tenant_id=app_metadata.get("tenant_id", "arcli.tech"),
            email=email,
            role="admin",
            app_metadata=app_metadata
        )

    # 1. Zero-Config Organization Routing (Domain Extraction)
    tenant_domain = email.split("@")[1].lower() if "@" in email else "unknown"
    
    # 2. Global Admin Detection
    is_admin = tenant_domain == "arcli.tech"

    # 3. Explicit Override (If a user is manually assigned a tenant_id in Supabase metadata)
    explicit_tenant = app_metadata.get("tenant_id") or user_metadata.get("tenant_id")
    
    # Priority: Explicit Metadata > Extracted Domain > User ID (B2C Solo)
    final_tenant_id = explicit_tenant or tenant_domain or user_id
    
    return TenantContext(
        user_id=str(user_id),
        tenant_id=str(final_tenant_id),
        email=email,
        role="admin" if is_admin else "authenticated",
        app_metadata=app_metadata
    )

def get_current_tenant_id(tenant_context: TenantContext = Depends(verify_tenant)) -> str:
    """
    Convenience Dependency: Instantly extracts the tenant_id for rapid API route filtering.
    """
    return tenant_context.tenant_id

# ------------------------------------------------------------------------------
# 4. Endpoints
# ------------------------------------------------------------------------------
@auth_router.post("/register", status_code=status.HTTP_201_CREATED)
async def register_user(payload: RegisterRequest):
    """
    Multi-tenant Registration Endpoint.
    1. Creates the user in Supabase Auth bypassing email checks (for immediate frontend login).
    2. Maps the user to their organizational domain tenant.
    """
    try:
        client = get_supabase_client()
        
        # Extract domain from email for the initial tenant assignment
        extracted_domain = payload.email.split("@")[1].lower() if "@" in payload.email else payload.email

        # Security by Design: We use the admin API to create the user and auto-confirm them.
        response = client.auth.admin.create_user({
            "email": payload.email,
            "password": payload.password,
            "email_confirm": True,
            "user_metadata": {
                "full_name": payload.full_name,
                "company_name": payload.company_name,
                "tenant_id": extracted_domain  # Zero-config tenant assignment
            }
        })
        
        # Next Step: Trigger your Database Service here to create the physical 
        # multi-tenant schema/rows, e.g., `db.create_tenant(extracted_domain)`
        
        return {
            "status": "success", 
            "message": "User and tenant successfully provisioned.",
            "user_id": response.user.id,
            "tenant_id": extracted_domain
        }
        
    except Exception as e:
        logger.error(f"Registration Failed for {payload.email}: {str(e)}")
        if "already registered" in str(e).lower():
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="User already exists.")
            
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Could not create user account.")