# api/auth.py

import os
import json
import logging
import re
import time
import hmac
import jwt  # Requires: pip install PyJWT
from typing import Dict, Any, Optional
from dataclasses import dataclass
from fastapi import APIRouter, Depends, HTTPException, Security, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from fastapi.security.api_key import APIKeyHeader
from pydantic import BaseModel, EmailStr, Field
from supabase import create_client, Client
from dotenv import load_dotenv

# ------------------------------------------------------------------------------
# 1. Configuration & Security Initialization
# ------------------------------------------------------------------------------
logger = logging.getLogger("DataOmenAuth")
load_dotenv()

# Security by Design: Enforce M2M Key for Cloudflare & Celery to DigitalOcean comms
INTERNAL_SERVICE_KEY = os.getenv("INTERNAL_SERVICE_KEY")
if not INTERNAL_SERVICE_KEY:
    # Structured logging matching the exact format for cloud monitoring
    logger.error(json.dumps({
        "timestamp": "startup",
        "level": "error",
        "tenant_id": "anonymous",
        "event": "critical_startup_failure",
        "error": "Missing INTERNAL_SERVICE_KEY",
        "details": "Machine-to-Machine (M2M) microservice routing will fail without this."
    }))
    # Fail-fast in production to trigger container restart alerts
    if os.getenv("ENVIRONMENT") == "production":
        raise RuntimeError("INTERNAL_SERVICE_KEY is strictly required in production.")

# Initialize API Router for modular registration
router = APIRouter(prefix="/api/v1/auth", tags=["Auth"])

# FastAPI security scheme
security = HTTPBearer()
internal_auth_header = APIKeyHeader(name="Authorization", auto_error=True)

# Singleton placeholder for the Supabase client
_supabase_client: Optional[Client] = None

# ------------------------------------------------------------------------------
# 2. Strict Pydantic Data Models
# ------------------------------------------------------------------------------
class RegisterRequest(BaseModel):
    """
    Strict payload validation for the registration flow.
    Ensures the smart defaults generated by the frontend are correctly typed and sanitized.
    """
    email: EmailStr
    password: str = Field(..., min_length=8, description="Must be at least 8 characters.")
    full_name: str = Field(..., description="Fallback or actual user name")
    company_name: str = Field(..., description="Fallback or actual tenant company name")

@dataclass
class TenantContext:
    """
    Object-Oriented Security: Encapsulates the verified user and tenant data.
    Ensures downstream services rely on strict properties, preventing dictionary-key typos 
    and accidental data leakage across tenants.
    """
    user_id: str
    tenant_id: str
    email: str
    role: str = "authenticated"
    app_metadata: Optional[Dict[str, Any]] = None

# ------------------------------------------------------------------------------
# 3. Core Services & Performance Dependencies
# ------------------------------------------------------------------------------
def get_supabase_client() -> Client:
    """Lazy initialization of the Supabase client to prevent startup crashes."""
    global _supabase_client
    if _supabase_client is None:
        url = os.getenv("SUPABASE_URL")
        # Ensure we use the SERVICE_ROLE_KEY for admin actions like user creation
        key = os.getenv("SUPABASE_SERVICE_ROLE_KEY") or os.getenv("SUPABASE_ANON_KEY")
        
        if not url or not key:
            raise RuntimeError("Supabase URL or Key is missing from environment.")
            
        _supabase_client = create_client(url, key)
    return _supabase_client

def get_current_user(credentials: HTTPAuthorizationCredentials = Depends(security)) -> Dict[str, Any]:
    """
    SaaS Performance Upgrade: M2M Bypass -> Stateless JWT -> Network Verification
    """
    token = credentials.credentials

    # FAST PATH 0: Machine-to-Machine (M2M) Authentication
    # Permits Cloudflare Workers and Celery Tasks to act as the internal system
    if INTERNAL_SERVICE_KEY and token == INTERNAL_SERVICE_KEY:
        return {
            "sub": "system-worker-0000",
            "email": "system@arcli.tech",
            "role": "service_role",
            "app_metadata": {"tenant_id": "arcli.tech"}
        }

    jwt_secret = os.getenv("SUPABASE_JWT_SECRET")

    # FAST PATH 1: Stateless Local Verification
    # Local decoding reduces auth latency to <1ms, preventing API rate limits.
    if jwt_secret:
        try:
            # Supabase uses HS256 for signing standard JWTs
            decoded_payload = jwt.decode(
                token,
                jwt_secret,
                algorithms=["HS256"],
                options={"verify_aud": False} # Supabase audience varies by project config
            )
            return decoded_payload
        except jwt.ExpiredSignatureError:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Token has expired")
        except jwt.InvalidTokenError as e:
            logger.warning(f"Stateless JWT verification failed: {e}")
            # Fallthrough to network check if local decoding fails
            
    # SLOW PATH: Network Verification (Fallback)
    try:
        client = get_supabase_client()
        user_response = client.auth.get_user(token)
        
        if not user_response or not user_response.user:
            raise ValueError("Invalid user token")
            
        # Safely convert Supabase user object to dict
        return user_response.user.model_dump() if hasattr(user_response.user, 'model_dump') else dict(user_response.user)
        
    except Exception as e:
        logger.warning(f"Network Authentication failed: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authentication credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )

def verify_tenant(user_payload: Dict[str, Any] = Depends(get_current_user)) -> TenantContext:
    """
    Security by Design: Validates and locks the context to a specific tenant.
    Inject this dependency into your routes to enforce strict multi-tenant boundaries.
    """
    user_id = user_payload.get("sub") or user_payload.get("id")
    email = user_payload.get("email", "")
    app_metadata = user_payload.get("app_metadata", {})
    user_metadata = user_payload.get("user_metadata", {})
    
    if not user_id or not email:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Malformed identity profile.")

    # 0. M2M System Bypass
    if user_id == "system-worker-0000":
        return TenantContext(
            user_id=str(user_id),
            tenant_id=app_metadata.get("tenant_id", "arcli.tech"),
            email=email,
            role="admin",
            app_metadata=app_metadata
        )

    # 1. Zero-Config Organization Routing (Domain Extraction)
    tenant_domain = email.split("@")[1].lower() if "@" in email else "unknown"
    
    # 2. Global Admin Detection
    is_admin = tenant_domain == "arcli.tech"

    # 3. Explicit Override (If a user is manually assigned a tenant_id in Supabase metadata)
    explicit_tenant = app_metadata.get("tenant_id") or user_metadata.get("tenant_id")
    
    # Priority: Explicit Metadata > Extracted Domain > User ID (B2C Solo)
    final_tenant_id = explicit_tenant or tenant_domain or user_id
    
    return TenantContext(
        user_id=str(user_id),
        tenant_id=str(final_tenant_id),
        email=email,
        role="admin" if is_admin else "authenticated",
        app_metadata=app_metadata
    )

def get_current_tenant_id(tenant_context: TenantContext = Depends(verify_tenant)) -> str:
    """
    Convenience Dependency: Instantly extracts the tenant_id for rapid API route filtering.
    """
    return tenant_context.tenant_id


async def verify_internal_service(header: str = Security(internal_auth_header)) -> bool:
    """Reusable dependency for machine-to-machine internal endpoints."""
    token = (header or "").strip()
    if token.lower().startswith("bearer "):
        token = token[7:].strip()

    if not INTERNAL_SERVICE_KEY or not token or not hmac.compare_digest(token, INTERNAL_SERVICE_KEY):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Invalid Internal Service Signature",
        )

    return True


def _coerce_http_status(value: Any) -> Optional[int]:
    """Best-effort conversion of status-like values into a valid HTTP status code."""
    if isinstance(value, int) and 100 <= value <= 599:
        return value

    if isinstance(value, str):
        stripped = value.strip()
        if stripped.isdigit():
            numeric = int(stripped)
            if 100 <= numeric <= 599:
                return numeric

    return None


def _extract_supabase_error_context(exc: Exception) -> Dict[str, Any]:
    """Extract structured details from Supabase/Gotrue exceptions when available."""
    error_text = str(exc).strip() or exc.__class__.__name__
    error_lower = error_text.lower()

    status_code = _coerce_http_status(getattr(exc, "status_code", None))
    if status_code is None:
        status_code = _coerce_http_status(getattr(exc, "status", None))
    if status_code is None:
        status_code = _coerce_http_status(getattr(exc, "code", None))

    response = getattr(exc, "response", None)
    if status_code is None and response is not None:
        status_code = _coerce_http_status(getattr(response, "status_code", None))
    if status_code is None and response is not None:
        status_code = _coerce_http_status(getattr(response, "status", None))

    parsed_payload: Optional[Dict[str, Any]] = None
    if error_text.startswith("{") and error_text.endswith("}"):
        try:
            maybe_payload = json.loads(error_text)
            if isinstance(maybe_payload, dict):
                parsed_payload = maybe_payload
        except Exception:
            parsed_payload = None

    if parsed_payload:
        payload_message = (
            parsed_payload.get("msg")
            or parsed_payload.get("message")
            or parsed_payload.get("error_description")
            or parsed_payload.get("error")
            or parsed_payload.get("detail")
        )
        if payload_message:
            error_text = str(payload_message)
            error_lower = error_text.lower()

        if status_code is None:
            status_code = _coerce_http_status(parsed_payload.get("status"))
        if status_code is None:
            status_code = _coerce_http_status(parsed_payload.get("status_code"))
        if status_code is None:
            status_code = _coerce_http_status(parsed_payload.get("code"))

    if status_code is None:
        status_match = re.search(r"\b(?:status(?:_code)?\s*[:=]?\s*|http\s+)([45]\d\d)\b", error_lower)
        if status_match:
            status_code = int(status_match.group(1))

    return {
        "status_code": status_code,
        "error_text": error_text,
        "error_lower": error_lower,
    }


def _map_register_exception_to_http(exc: Exception) -> HTTPException:
    """Map Supabase registration errors into stable frontend-facing HTTP responses."""
    context = _extract_supabase_error_context(exc)
    status_code = context["status_code"]
    error_text = context["error_text"]
    error_lower = context["error_lower"]

    if status_code == status.HTTP_409_CONFLICT or "already registered" in error_lower or "user already exists" in error_lower:
        logger.warning("[DEBUG-API] Conflict: User already exists.")
        return HTTPException(status_code=status.HTTP_409_CONFLICT, detail="User already exists.")

    if (
        status_code in {status.HTTP_400_BAD_REQUEST, status.HTTP_422_UNPROCESSABLE_ENTITY}
        and "password" in error_lower
    ) or ("password" in error_lower and any(token in error_lower for token in ["weak", "characters", "at least", "minimum"])):
        logger.warning(f"[DEBUG-API] Bad Request: Password policy violation -> {error_text}")
        return HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"Password error: {error_text}")

    if status_code == status.HTTP_429_TOO_MANY_REQUESTS or "rate limit" in error_lower or "too many requests" in error_lower:
        logger.warning("[DEBUG-API] Rate limit hit on Supabase.")
        return HTTPException(status_code=status.HTTP_429_TOO_MANY_REQUESTS, detail="Rate limit exceeded. Try again later.")

    if (
        status_code in {status.HTTP_400_BAD_REQUEST, status.HTTP_422_UNPROCESSABLE_ENTITY}
        and "email" in error_lower
        and "invalid" in error_lower
    ) or "invalid email" in error_lower:
        logger.warning(f"[DEBUG-API] Bad Request: Invalid email rejected by Supabase -> {error_text}")
        return HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=f"Invalid email: {error_text}")

    if "supabase url or key is missing" in error_lower or "missing from environment" in error_lower:
        logger.error("[DEBUG-API] CONFIG ERROR: Missing Supabase environment variables.")
        return HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Backend configuration error: Supabase URL/keys are missing in environment variables.",
        )

    if status_code in {status.HTTP_401_UNAUTHORIZED, status.HTTP_403_FORBIDDEN} or any(
        token in error_lower for token in ["forbidden", "unauthorized", "jwt", "service role"]
    ):
        logger.error("[DEBUG-API] CONFIG ERROR: The SUPABASE_SERVICE_ROLE_KEY is likely missing or invalid.")
        return HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Backend configuration error: Supabase Admin permissions denied. Check backend Environment Variables.",
        )

    return HTTPException(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        detail=f"Backend creation failed: {error_text}",
    )

# ------------------------------------------------------------------------------
# 4. Endpoints
# ------------------------------------------------------------------------------
@router.post("/register", status_code=status.HTTP_201_CREATED)
async def register_user(payload: RegisterRequest):
    """
    Multi-tenant Registration Endpoint with granular debugging and typed error mapping.
    """
    request_id = f"reg-{int(time.time() * 1000)}-{os.getpid()}"
    request_start = time.perf_counter()

    logger.info(f"[DEBUG-API][{request_id}] === Incoming Registration for: {payload.email} ===")
    logger.info(
        f"[DEBUG-API][{request_id}] Payload snapshot: "
        f"full_name={payload.full_name!r}, company_name={payload.company_name!r}, password_length={len(payload.password)}"
    )

    try:
        client = get_supabase_client()
        extracted_domain = payload.email.split("@")[1].lower() if "@" in payload.email else payload.email

        logger.info(
            f"[DEBUG-API][{request_id}] Attempting Supabase Admin user creation. "
            f"target_tenant={extracted_domain}"
        )

        response = client.auth.admin.create_user({
            "email": payload.email,
            "password": payload.password,
            "email_confirm": True,
            "user_metadata": {
                "full_name": payload.full_name,
                "company_name": payload.company_name,
                "tenant_id": extracted_domain
            }
        })

        created_user = getattr(response, "user", None)
        created_user_id = getattr(created_user, "id", None) if created_user else None
        if not created_user_id:
            logger.error(f"[DEBUG-API][{request_id}] Supabase response did not include a created user ID.")
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail="Supabase returned an invalid user creation response.",
            )

        duration_ms = int((time.perf_counter() - request_start) * 1000)

        logger.info(
            f"[DEBUG-API][{request_id}] Supabase Admin creation SUCCESS. "
            f"user_id={created_user_id}, tenant_id={extracted_domain}, duration_ms={duration_ms}"
        )

        return {
            "status": "success", 
            "message": "User and tenant successfully provisioned.",
            "user_id": created_user_id,
            "tenant_id": extracted_domain
        }

    except HTTPException:
        raise

    except Exception as e:
        context = _extract_supabase_error_context(e)
        duration_ms = int((time.perf_counter() - request_start) * 1000)
        logger.error(
            f"[DEBUG-API][{request_id}] CRITICAL Supabase Registration Error after {duration_ms}ms: "
            f"status={context['status_code']}, message={context['error_text']}, exception_type={type(e).__name__}"
        )
        raise _map_register_exception_to_http(e)